github_api_url: "https://api.github.com/search/code"
github_token: "BOT"  # 替换为您的 GitHub Personal Access Token
search_query: "v2ray shadowsocks trojan hysteria hy2 ssr clash proxies nodes subscription config"
output_dir: "data"
nodes_file: "hy2.txt"
urls_file: "url.txt"
node_protocols:
  - "ss://"
  - "vmess://"
  - "trojan://"
  - "hy2://"
  - "ssr://"
