input:
  sub_file: data/sub.txt
  history_file: data/history_results.json
output:
  dir: data/
  nodes_file: enhanced_nodes.txt
  checksum_file: checksums.txt
test:
  timeout_seconds: 1
  max_concurrent: 50
log:
  level: INFO
  file: data/logfile.txt
