# config_proxy.yaml

# 日志级别
# DEBUG: 最详细的日志，包含调试信息
# INFO: 一般信息，程序运行的关键步骤
# WARNING: 警告信息，可能的问题
# ERROR: 错误信息，程序遇到问题但可能继续运行
# CRITICAL: 严重错误，程序可能无法继续运行
log_level: "INFO"

# GitHub 搜索配置
# 用于在 GitHub 上搜索代理链接的关键词列表。
# 请注意，移除了 'in:file' 等限定符，因为 GitHub API 会根据上下文自动匹配文件内容。
# 增加了更多精确匹配文件类型和常见配置片段的关键词。
search_keywords:
  # Shadowsocks (SS)
  - "ss://" # 直接搜索协议头
  - "shadowsocks method password" # 搜索典型的配置组合
  - "ss subscription"
  - "extension:txt ss://" # 在txt文件中搜索ss://
  - "extension:yaml ss://"
  - "extension:json ss://"
  - "shadowsocks list"
  - "free shadowsocks"
  - "public shadowsocks"
  - "ss panel" # 搜索面板相关
  - "ss-link"

  # Hysteria2 (Hy2)
  - "hy2://"
  - "hysteria2 server port" # 搜索典型的配置组合
  - "hy2 subscription"
  - "extension:txt hy2://"
  - "extension:yaml hy2://"
  - "hysteria2 list"
  - "free hysteria2"

  # V2Ray (VMess/VLESS)
  - "vmess://"
  - "vless://"
  - "v2ray config json" # 搜索v2ray的json配置
  - "v2ray subscription"
  - "extension:txt vmess://"
  - "extension:txt vless://"
  - "v2ray list"
  - "free v2ray"
  - "public v2ray"

  # Trojan
  - "trojan://"
  - "trojan password host" # 搜索典型的配置组合
  - "trojan subscription"
  - "extension:txt trojan://"
  - "extension:yaml trojan://"
  - "trojan list"
  - "free trojan"

  # Reality (Xray with Reality)
  - "reality://"
  - "xray reality host"
  - "reality subscription"
  - "grpc://"

  # Tuic
  - "tuic://"
  - "tuic password port"
  - "tuic config"
  - "tuic list"

  # WireGuard (wg)
  - "wg://"
  - "wireguard privatekey" # 搜索wireguard的关键信息
  - "wireguard config"
  - "wireguard.conf"
  - "wireguard list"

  # Warp (Cloudflare Warp)
  - "warp://"
  - "cloudflare warp private_key"
  - "warp config"

  # Shadow-Tls
  - "shadow-tls://"
  - "shadow-tls password host"
  - "shadow-tls config"

  # 通用订阅链接 / 文件名 / 内容片段
  - "subscribe url"
  - "subscription link"
  - "nodes.txt"
  - "config.txt"
  - "proxy.txt"
  - "sub.txt"
  - "nodes.yaml"
  - "config.yaml"
  - "proxy.yaml"
  - "sub.yaml"
  - "clash.yaml"
  - "surge.conf"
  - "v2rayN-sub"
  - "v2ray.json" # 补充常见的配置文件名
  - "ssr.txt"
  - "quantumultx.conf"

  # 额外平台/域名 (直接搜索原始URL) - 这些通常能直接命中原始文件链接
  - "raw.githubusercontent.com ss://"
  - "raw.githubusercontent.com vmess://"
  - "raw.githubusercontent.com hy2://"
  - "raw.githubusercontent.com trojan://"
  - "gist.github.com ss://"
  - "gist.github.com vmess://"
  - "gist.github.com hy2://"
  - "gist.github.com trojan://"
  - "cdn.jsdelivr.net ss://"
  - "fastly.net ss://"

  # 中文关键词 (非常重要，能覆盖更多本地分享资源)
  - "免费节点"
  - "v2ray免费节点"
  - "ss免费节点"
  - "trojan免费节点"
  - "hy2免费节点"
  - "clash订阅"
  - "v2ray订阅"
  - "ssr订阅"
  - "翻墙节点"
  - "梯子节点"
  - "机场订阅"
  - "最新节点"
  - "节点分享"
  - "公益节点"
  - "科学上网"
  - "vmess链接"
  - "vless链接"
  - "ss链接"
  - "hysteria2链接"
  - "trojan链接"
  - "reality链接"
  - "tuic链接"
  - "warp链接"
  - "shadow-tls链接"
  - "代理地址"
  - "代理配置"
  - "订阅地址"
  - "节点列表"
  - "分享节点"
  - "可v2rayN"
  - "小猫咪配置"
  - "免费机场"
  - "最新机场"

# GitHub API 每页返回的结果数量
per_page: 100

# GitHub API 最大搜索页数
# 增加此值可以获取更多搜索结果，但会增加 API 调用量和运行时间。
max_search_pages: 10

# GitHub API 请求超时时间（秒）
github_api_timeout: 20

# GitHub API 速率限制达到后等待时间（秒）
# 当 GitHub 剩余 API 请求次数低于 rate_limit_threshold 时，程序会等待此时间。
github_api_retry_wait: 30

# GitHub API 速率限制阈值
# 剩余 API 请求次数低于此值时，触发等待。
rate_limit_threshold: 5

# 代理节点验证超时时间（秒）
proxy_check_timeout: 5

# 最大 URL 数量 (从 GitHub 搜索到的原始文件链接)
# 程序最多会处理这些数量的 URL，超过则停止搜索。
max_urls: 500

# 缓存文件路径 (建议在数据目录中，方便管理)
search_cache_path: "data/search_cache_proxy.json" # 用于缓存 GitHub 搜索结果
proxy_states_path: "data/proxy_states.json"     # 用于缓存代理节点检测状态

# 缓存配置
# search_cache_ttl: GitHub 搜索缓存的生存时间（秒）。
# 超过此时间，将重新向 GitHub 发起搜索请求以获取最新数据。
search_cache_ttl: 43200 # 12 小时

# proxy_states_ttl: 代理可用性缓存的生存时间（秒）。
# 超过此时间，将重新检测代理节点以验证其可用性。
proxy_states_ttl: 21600 # 6 小时

# 代理提取的最大并发线程数 (用于下载原始文件内容)
channel_extract_workers: 10

# Requests 库的重试总次数
requests_retry_total: 3

# Requests 库的重试间隔回退因子 (例如，1.5 代表 1秒 -> 1.5秒 -> 2.25秒...)
requests_retry_backoff_factor: 1.5

# Requests 库的连接池大小
requests_pool_size: 100

# 最大并发工作线程数 (用于检测代理节点可用性)
proxy_check_workers: 50

# 输出文件名 (可用代理节点将保存到此文件中)
output_file: "data/available_proxies.txt"
