# GitHub API 每页结果数量
per_page: 100

# GitHub API 最大搜索页数
max_search_pages: 5

# GitHub API 请求超时时间（秒）
github_api_timeout: 20

# GitHub API 速率限制达到后等待时间（秒）
github_api_retry_wait: 30

# GitHub API 速率限制阈值
rate_limit_threshold: 5

# 代理节点验证超时时间（秒）
proxy_check_timeout: 5

# 最大 URL 数量 (用于搜索到的原始文件链接)
max_urls: 500

# 缓存文件路径
search_cache_path: "data/search_cache_proxy.json"
proxy_states_path: "data/proxy_states.json"

# 新增/调整的缓存配置
search_cache_ttl: 43200 # GitHub 搜索缓存 TTL（秒，建议12小时）
proxy_states_ttl: 21600 # 代理可用性缓存 TTL（秒，建议6小时）

# 日志级别
log_level: "INFO" # 验证节点时，INFO级别可以显示更多进展

# 最大并发工作线程数
proxy_check_workers: 50

# 频道提取的最大并发线程数 (用于下载原始文件内容)
channel_extract_workers: 10

# Requests 库的重试总次数
requests_retry_total: 3

# Requests 库的重试间隔回退因子
requests_retry_backoff_factor: 1.5

# Requests 库的连接池大小
requests_pool_size: 100

# 输出文件名
output_file: "data/available_proxies.txt"
