# 全局配置，用于控制脚本的行为和参数

# GitHub 搜索关键词配置
# 脚本会使用这些关键词在 GitHub 上搜索 m3u/m3u8 播放列表文件。
# 可以使用 # 符号注释掉暂时不想使用的关键词。
search_keywords:
  - "extension:m3u8 in:file"
  - "extension:m3u in:file"
  # - "iptv playlist extension:m3u,m3u8 in:file" # 暂时隐藏此关键词，加速测试
  # - "raw.githubusercontent.com path:.m3u8"      # 暂时隐藏此关键词
  # - "raw.githubusercontent.com path:.m3u"        # 暂时隐藏此关键词
  - "tv channels extension:m3u,m3u8 in:file"
  # - "live tv extension:m3u,m3u8 in:file"
  # - "playlist.m3u8 in:file"
  # - "index.m3u8 in:file"
  # - "channels.m3u in:file"
  # - "iptv links extension:m3u,m3u8 in:file"

# GitHub API 每页结果数量
per_page: 100

# GitHub API 最大搜索页数，限制搜索深度
max_search_pages: 5

# GitHub API 请求超时时间（秒）
github_api_timeout: 20

# GitHub API 速率限制达到后等待时间（秒）
github_api_retry_wait: 10

# 抓取频道列表 URL 内容的超时时间（秒）
channel_fetch_timeout: 15

# 检查单个频道链接可用性的超时时间（秒）
channel_check_timeout: 6

# 每个频道名称最多保留的 URL 数量，避免过多重复链接
max_channel_urls_per_group: 200

# Requests 库的连接池大小
requests_pool_size: 200

# Requests 库的重试总次数
requests_retry_total: 3

# Requests 库的重试间隔回退因子
requests_retry_backoff_factor: 1

# 频道名称过滤词列表
# 包含这些词的频道名称将被过滤掉。
name_filter_words:
  - "购物"
  - "理财"
  - "导视"
  - "指南"
  - "测试"
  - "芒果"
  - "CGTN"
  - "(480p)"
  - "(360p)"
  - "(240p)"
  - "(406p)"
  - " (540p)"
  - "(600p)"
  - "(576p)"
  - "[Not 24/7]"
  - "DJ"
  - "音乐"
  - "演唱会"
  - "舞曲"
  - "春晚"
  - "格斗"
  - "粤"
  - "祝"
  - "体育"
  - "广播"
  - "博斯"
  - "神话"

# URL 过滤词列表
# 包含这些词的 URL 将被过滤掉。
url_filter_words:
  - "example.com/test"
  - "badurl.xyz"

# 频道名称替换规则
# 键是要被替换的字符串，值是替换后的字符串。
# 如果值是空字符串 ""，则表示删除该部分。
channel_name_replacements:
  FHD: ""
  HD: ""
  hd: ""
  频道: ""
  高清: ""
  超清: ""
  "20M": "" # 包含数字或特殊字符的键最好加上引号，但不是必须的
  "-": ""
  "4k": ""
  "4K": ""
  "4kR": ""

# 最终输出 IPTV 列表时，频道分类的优先顺序
# 列表中的分类会首先被添加到 iptv_list.txt 中，然后才是其他分类。
ordered_categories:
  - "央视频道"
  - "卫视频道"
  - "湖南频道"
  - "港台频道"

# URL 预筛选配置
url_pre_screening:
  # 允许的 URL 协议类型
  allowed_protocols:
    - "http"
    - "https"
    - "rtmp"
    - "rtp"
    - "p3p"
  # 允许的流媒体文件扩展名（用于初步过滤）
  stream_extensions:
    - ".m3u8"
    - ".flv"
    - ".mp4"
    - ".ts"
    - ".aac"
    - ".mp3"
    - ".ogg"
    - ".webm"
    - ".avi"
    - ".mov"
    - ".wmv"
    - ".rm"
    - ".rmvb"
    - ".3gp"
    - ".mkv"
  # 无效 URL 的正则表达式模式列表
  invalid_url_patterns:
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "\\.png$"
    - "\\.jpg$"
    - "\\.jpeg$"
    - "\\.gif$"
    - "\\.css$"
    - "\\.js$"
    - "\\.html$"
    - "\\.xml$"
    - "(\\s|%20)" # 匹配空格或 URL 编码的空格
    - "null"
    - "invalid"
    - "error"
    - "blank"
