# GitHub 搜索配置
search_keywords:
  # 英文关键词
  - "extension:m3u8 in:file"
  - "extension:m3u in:file"
  - "iptv playlist extension:m3u,m3u8 in:file"
  - "raw.githubusercontent.com path:.m3u8"
  - "raw.githubusercontent.com path:.m3u"
  - "tv channels extension:m3u,m3u8 in:file"
  - "live tv extension:m3u,m3u8 in:file"
  - "playlist.m3u8 in:file"
  - "index.m3u8 in:file"
  - "channels.m3u in:file"
  - "iptv links extension:m3u,m3u8 in:file"
  - "m3u8 playlist"
  - "iptv list"
  - "m3u"
  - "m3u channels"
  - "iptv channels"
  - "live tv playlist"
  - "free iptv"
  - "public iptv"
  - "tv channels list"
  - "stream list"
  - "live stream list"
  - "m3u stream"
  - "m3u8 stream"
  - "iptv.m3u"
  - "raw.githubusercontent.com m3u" # 更通用地搜索raw链接
  - "gitee.com m3u" # 考虑到国内用户可能使用Gitee
  - "fastly.net m3u8" # 常见CDN
  - "cdn.jsdelivr.net m3u" # jsdelivr加速的raw文件
  - "gist.github.com m3u" # 从Gist中搜索
  - "raw.githubusercontents.com m3u" # 备用raw域名

  # 中文关键词
  - "直播源"
  - "电视直播"
  - "IPTV直播"
  - "M3U直播"
  - "M3U8直播"
  - "频道列表"
  - "免费直播"
  - "公共直播"
  - "聚合直播"
  - "直播源.txt"
  - "电视直播.m3u"
  - "电视直播.m3u8"
  - "iptv源"
  - "直播地址"
  - "网络电视"
  - "节目单"
  - "最新直播源"
  - "稳定直播源"
  - "CCTV1" # 具体的央视频道
  - "CCTV5"
  - "CCTV13"
  - "湖南卫视" # 具体的卫视频道
  - "浙江卫视"
  - "东方卫视"
  - "江苏卫视"
  - "北京卫视"
  - "凤凰卫视"
  - "港澳台直播" # 增加区域性关键词
  - "海外直播"
  - "体育直播"
  - "电影频道"
  - "少儿频道"
  - "纪录片频道"
  - "音乐频道"
  - "财经频道"
  - "教育频道"
  - "生活频道"
  - "iptvbox" # 常见聚合盒子关键词
  - "TVBOX"
  - "EPG" # 电子节目单相关
  - "组播源" # 组播地址，虽然少但可能存在

# GitHub API 每页结果数量
per_page: 100

# GitHub API 最大搜索页数，限制搜索深度
max_search_pages: 5

# GitHub API 请求超时时间（秒）
github_api_timeout: 60 # 调整为更宽松的60秒

# GitHub API 速率限制达到后等待时间（秒）
github_api_retry_wait: 60 # 调整为更宽松的60秒

# 抓取频道列表 URL 内容的超时时间（秒）
channel_fetch_timeout: 15

# 检查单个频道链接可用性的超时时间（秒）
channel_check_timeout: 6

# 每个频道名称最多保留的 URL 数量，避免过多重复链接
max_channel_urls_per_group: 200

# Requests 库的连接池大小
requests_pool_size: 200

# Requests 库的重试总次数
requests_retry_total: 3

# Requests 库的重试间隔回退因子
requests_retry_backoff_factor: 1

# 频道名称过滤词列表
# 包含这些词的频道名称将被过滤掉。
name_filter_words:
  - "购物"
  - "理财"
  - "导视"
  - "指南"
  - "测试"
  - "芒果"
  - "CGTN"
  - "(480p)"
  - "(360p)"
  - "(240p)"
  - "(406p)"
  - " (540p)"
  - "(600p)"
  - "(576p)"
  - "[Not 24/7]"
  - "DJ"
  - "音乐"
  - "演唱会"
  - "舞曲"
  - "春晚"
  - "格斗"
  - "粤"
  - "祝"
  - "体育"
  - "广播"
  - "博斯"
  - "神话"
  - "失效"
  - "demo"
  - "backup"
  - "内测"
  - "测试频道"
  - "广告"
  - "已过期"
  - "禁用"
  - "无效"
  - "勿扰"
  - "仅供参考"
  - "过期"
  - "不可用"
  - "样本"
  - "temp"
  - "临时"

# URL 过滤词列表
# 包含这些词的 URL 将被过滤掉。
url_filter_words:
  - "example.com" # 简化为只匹配域名
  - "test.com"
  - "badurl.xyz"
  - "localhost"
  - "127.0.0.1"
  - "0.0.0.0"
  - "privateip"
  - "dummy"
  - "demo"
  - "\\.(png|jpg|jpeg|gif|css|js|html|xml|txt|md|json|yml|yaml|csv)$" # 合并更多文件类型
  - "(\\s|%20)" # 匹配空格或 URL 编码的空格
  - "null"
  - "invalid"
  - "error"
  - "blank"
  - "expired"
  - "sample"
  - "temp"
  - "github\\.com(?!.*raw\\.)" # 排除github页面链接，但允许raw链接
  - "gitee\\.com(?!.*raw\\.)" # 排除gitee页面链接，但允许raw链接
  - "(youtube\\.com/watch|youtu\\.be)" # 排除YouTube
  - "youku\\.com"
  - "iqiyi\\.com"
  - "bilibili\\.com"
  - "live\\.bilibili\\.com"
  - "douyu\\.com"
  - "huya\\.com"
  - "twitch\\.tv"
  - "facebook\\.com"
  - "twitter\\.com"
  - "weibo\\.com"
  - "tiktok\\.com"
  - "douyin\\.com"
  - "kuaishou\\.com"
  - "music\\.163\\.com"
  - "mp\\.weixin\\.qq\\.com"
  - "\\.(zip|rar|7z|tar|gz|tgz|bz2|xz|pdf|doc|docx|xls|xlsx|ppt|pptx|exe|dll|msi|apk|dmg|pkg)$" # 合并各种压缩包和文档
  - "vpn"
  - "proxy"
  - "shadowsocks"
  - "v2ray"
  - "trojan"
  - "surge"
  - "clash"
  - "clashx"
  - "speedtest"
  - "tracker"
  - "torrent"
  - "magnet"
  - "(\\d{1,3}\\.){3}\\d{1,3}/(24|28|30|32)" # 排除CIDR IP段
  - "rtmp://.*:1935/(live|vod)/"
  # 更细化的CDN和云服务商排除
  - "akamaized\\.net"
  - "cloudfront\\.net"
  - "edgecastcdn\\.net"
  - "aliyuncs\\.com"
  - "wscloudcdn\\.com"
  - "ccgslb\\.com"
  - "myqcloud\\.com"
  - "qq\\.com(?!.*live\\.qq\\.com)" # 排除大部分qq.com链接，但保留腾讯官方直播域
  - "bokecc\\.com"
  - "huya\\.com"
  - "douyucdn\\.cn"
  - "hixp2p\\.com"
  - "cibn\\.cc"
  - "upgslb\\.com"
  - "aixiaoke\\.com"
  - "cloudvdn\\.com"
  - "fastweb\\.com\\.cn"
  - "qqurl\\.net"
  - "alicdn\\.com"
  - "liveplay\\.net"
  - "cdn\\.liveplay\\.net"
  - "cdn\\.live\\.com"
  - "live\\.cdn\\.com"
  - "live\\.com"
  - "live\\.tv"
  - "live\\.video"
  - "live\\.stream"
  - "teststream"
  - "nullstream"
  - "empty\\.m3u8"
  - "error\\.m3u8"
  - "playlist\\.m3u8\\?streamid=0"
  - "stream_not_found"
  - "http://.*/playlist.m3u8\\?uid="
  - "http://.*/\\?url="
  - "http://.*/live/.*\\?_sign="
  - "http://.*/live/.*\\?auth_key="
  - "live-streams-not-working"
  - "fake-stream"
  - "dead-stream"
  - "(ftp|sftp)://"
  - "http://.*?/playlist.m3u8\\?id="
  - "vnet\\.com"
  - "chinaunicom\\.com"
  - "chinatelecom\\.cn"
  - "chinamobile\\.com"
  - "alibabacloud\\.com"
  - "tencentcloud\\.com"
  - "huaweicloud\\.com"
  - "baidu\\.com"
  - "jd\\.com"
  - "taobao\\.com"
  - "raw\\.bgithub\\.xyz/.*\\.(md|json|xml|yml|yaml)$"


# 频道名称替换规则
# 键是要被替换的字符串，值是替换后的字符串。
# 如果值是空字符串 ""，则表示删除该部分。
channel_name_replacements:
  FHD: ""
  HD: ""
  hd: ""
  频道: ""
  高清: ""
  超清: ""
  "20M": ""
  "-": ""
  "4k": ""
  "4K": ""
  "4kR": ""
  "测试": ""
  "失效": ""
  "直播": ""
  "卫视": "卫视"
  "省台": ""
  "市台": ""
  "海外": "海外"
  "港台": "港台"
  "中央": "CCTV"
  "央视": "CCTV"
  "CCTV1综合": "CCTV1"
  "CCTV2财经": "CCTV2"
  "CCTV3综艺": "CCTV3"
  "CCTV4中文国际": "CCTV4"
  "CCTV5体育": "CCTV5"
  "CCTV6电影": "CCTV6"
  "CCTV7军事农业": "CCTV7"
  "CCTV8电视剧": "CCTV8"
  "CCTV9纪录": "CCTV9"
  "CCTV10科教": "CCTV10"
  "CCTV11戏曲": "CCTV11"
  "CCTV12社会与法": "CCTV12"
  "CCTV13新闻": "CCTV13"
  "CCTV14少儿": "CCTV14"
  "CCTV15音乐": "CCTV15"
  "CCTV16奥林匹克": "CCTV16"
  "CCTV17农业农村": "CCTV17"


# 最终输出 IPTV 列表时，频道分类的优先顺序
# 列表中的分类会首先被添加到 iptv_list.txt 中，然后才是其他分类。
ordered_categories:
  - "CCTV频道"
  - "央视"
  - "卫视频道"
  - "地方频道"
  - "湖南频道"
  - "上海频道"
  - "广东频道"
  - "江苏频道"
  - "浙江频道"
  - "北京频道"
  - "天津频道"
  - "重庆频道"
  - "河北频道"
  - "山西频道"
  - "内蒙频道"
  - "辽宁频道"
  - "吉林频道"
  - "黑龙江频道"
  - "安徽频道"
  - "福建频道"
  - "江西频道"
  - "山东频道"
  - "河南频道"
  - "湖北频道"
  - "湖南频道"
  - "广西频道"
  - "海南频道"
  - "四川频道"
  - "贵州频道"
  - "云南频道"
  - "西藏频道"
  - "陕西频道"
  - "甘肃频道"
  - "青海频道"
  - "宁夏频道"
  - "新疆频道"
  - "港台频道"
  - "国外频道"
  - "体育频道"
  - "电影频道"
  - "少儿频道"
  - "纪录片频道"
  - "音乐频道"
  - "财经频道"
  - "教育频道"
  - "生活频道"
  - "其他频道"

# URL 预筛选配置
url_pre_screening:
  # 允许的 URL 协议类型
  allowed_protocols:
    - "http"
    - "https"
    - "rtmp"
    - "rtp"
    - "p3p"
    - "udp"
    - "rtsp"
  # 允许的流媒体文件扩展名（用于初步过滤）
  stream_extensions:
    - ".m3u8"
    - ".flv"
    - ".mp4"
    - ".ts"
    - ".aac"
    - ".mp3"
    - ".ogg"
    - ".webm"
    - ".avi"
    - ".mov"
    - ".wmv"
    - ".rm"
    - ".rmvb"
    - ".3gp"
    - ".mkv"
    - ".f4m"
    - ".ism"
    - ".nis"
    - ".hls"
  # 无效 URL 的正则表达式模式列表
  invalid_url_patterns:
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "privateip"
    - "0\\.0\\.0\\.0"
    - "dummy"
    - "demo"
    - "\\.(png|jpg|jpeg|gif|css|js|html|xml|txt|md|json|yml|yaml|csv)$" # 合并更多文件类型
    - "(\\s|%20)" # 匹配空格或 URL 编码的空格
    - "null"
    - "invalid"
    - "error"
    - "blank"
    - "github\\.com(?!.*raw\\.)" # 排除github页面链接，但允许raw链接
    - "gitee\\.com(?!.*raw\\.)" # 排除gitee页面链接，但允许raw链接
    - "(youtube\\.com/watch|youtu\\.be)"
    - "youku\\.com"
    - "iqiyi\\.com"
    - "bilibili\\.com"
    - "live\\.bilibili\\.com"
    - "douyu\\.com"
    - "huya\\.com"
    - "twitch\\.tv"
    - "facebook\\.com"
    - "twitter\\.com"
    - "weibo\\.com"
    - "tiktok\\.com"
    - "douyin\\.com"
    - "kuaishou\\.com"
    - "music\\.163\\.com"
    - "mp\\.weixin\\.qq\\.com"
    - "\\.(zip|rar|7z|tar|gz|tgz|bz2|xz|pdf|doc|docx|xls|xlsx|ppt|pptx|exe|dll|msi|apk|dmg|pkg)$"
    - "vpn"
    - "proxy"
    - "shadowsocks"
    - "v2ray"
    - "trojan"
    - "surge"
    - "clash"
    - "clashx"
    - "speedtest"
    - "tracker"
    - "torrent"
    - "magnet"
    - "(\\d{1,3}\\.){3}\\d{1,3}/(24|28|30|32)"
    - "rtmp://.*:1935/(live|vod)/"
    - "akamaized\\.net"
    - "cloudfront\\.net"
    - "edgecastcdn\\.net"
    - "aliyuncs\\.com"
    - "wscloudcdn\\.com"
    - "ccgslb\\.com"
    - "myqcloud\\.com"
    - "qq\\.com(?!.*live\\.qq\\.com)"
    - "bokecc\\.com"
    - "huya\\.com"
    - "douyucdn\\.cn"
    - "hixp2p\\.com"
    - "cibn\\.cc"
    - "upgslb\\.com"
    - "aixiaoke\\.com"
    - "cloudvdn\\.com"
    - "fastweb\\.com\\.cn"
    - "qqurl\\.net"
    - "alicdn\\.com"
    - "liveplay\\.net"
    - "cdn\\.liveplay\\.net"
    - "cdn\\.live\\.com"
    - "live\\.cdn\\.com"
    - "live\\.com"
    - "live\\.tv"
    - "live\\.video"
    - "live\\.stream"
    - "teststream"
    - "nullstream"
    - "empty\\.m3u8"
    - "error\\.m3u8"
    - "playlist\\.m3u8\\?streamid=0"
    - "stream_not_found"
    - "http://.*/playlist.m3u8\\?uid="
    - "http://.*/\\?url="
    - "http://.*/live/.*\\?_sign="
    - "http://.*/live/.*\\?auth_key="
    - "live-streams-not-working"
    - "fake-stream"
    - "dead-stream"
    - "(ftp|sftp)://"
    - "http://.*?/playlist.m3u8\\?id="
    - "vnet\\.com"
    - "chinaunicom\\.com"
    - "chinatelecom\\.cn"
    - "chinamobile\\.com"
    - "alibabacloud\\.com"
    - "tencentcloud\\.com"
    - "huaweicloud\\.com"
    - "baidu\\.com"
    - "jd\\.com"
    - "taobao\\.com"
    - "raw\\.bgithub\\.xyz/.*\\.(md|json|xml|yml|yaml)$"
