# 频道抓取和检查配置
check_timeout: 8 # 例如，频道检查的默认超时时间
request_timeout: 10 # 例如，网络请求的默认超时时间
channel_check_workers: 100 # 例如，多线程检查频道的工作线程数

# 配置日志级别 (请确保在 config.yaml 中设置，而不是在脚本中硬编码)
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

# URL 状态的过期清理逻辑
url_state_expiration_days: 90

# 新增的历史url配置项，用于控制频道保留策略
stream_fail_threshold: 18
stream_retention_hours: 1368

# GitHub API 配置
per_page: 100
max_search_pages: 5
github_api_timeout: 30
github_api_retry_wait: 30
rate_limit_threshold: 5
search_updated_within_days: 30

# Requests 配置
requests_pool_size: 100
requests_retry_total: 3
requests_retry_backoff_factor: 1.5

# 缓存配置
url_states_ttl: 604800
channel_cache_ttl: 86400

# 输出格式
output_format: "m3u"

# EPG 配置（暂时禁用）
epg_enabled: false
epg_search_keywords:
  - "epg xmltv"
  - "iptv epg xml"
epg_max_urls: 10

# 文件路径配置
paths:
  channels_dir: "地方频道"
  output_dir: "output"
  final_iptv_file: "iptv_list.txt"
  channel_cache_file: "config/channel_cache.json"
  keyword_stats_file: "config/keyword_stats.json"

# --- 核心过滤规则 ---
# 这些规则将由脚本的 check_channel 函数使用
rules:
  # URL 预筛选规则 (初步筛选)
  url_pre_screening:
    allowed_protocols:
      - "http"
      - "https"
      - "rtmp"
      - "rtp"
      - "p3p"
      - "udp"
      - "rtsp"
    stream_extensions:
      - ".m3u8"
      - ".m3u"
      - ".flv"
      - ".mp4"
      - ".ts"
      - ".hls"
      - ".dash"

  # 无效 URL 模式 (进一步排除)
  invalid_url_patterns:
    - "vdse\\.bdstatic\\.com"
    - "vd2\\.bdstatic\\.com"
    - "vd3\\.bdstatic\\.com"
    - "vd4\\.bdstatic\\.com"
    - "vodcdn\\.video\\.taobao\\.com"
    - "cloud\\.video\\.taobao\\.com"
    - "15799848\\.s21v\\.faiusr\\.com"
    - "txmov2\\.a\\.kwimgs\\.com"
    - "video30\\.avnyg\\.com"
    - "videomy\\.yongaomy\\.com"
    - "antiserver\\.kuwo\\.cn"
    - "youtube\\.com\\/(watch|embed|live)"
    - "bilibili\\.com"
    - "twitch\\.tv"
    - "facebook\\.com\\/(watch|live)"
    - "twitter\\.com"
    - "instagram\\.com"
    - "linkedin\\.com"
    - "pinterest\\.com"
    - "plus\\.google\\.com"
    - "weibo\\.com"
    - "douyin\\.com"
    - "kuaishou\\.com"
    - "satellitepull\\.cnr\\.cn"
    - "ali-m-l\\.cztv\\.com"
    - "epg\\.pw"
    - "live\\.pull\\.hebtv\\.com"
    - "\\.(png|jpe?g|gif|bmp|webp|svg|ico|mov|avi|wmv|flv|webm|mp3|wav|ogg|aac|pdf|docx?|xlsx?|pptx?|epub|zip|rar|7z|tar|gz|tgz|bz2|xz|exe|dll|msi|apk|dmg|pkg|iso|img|css|js|xml|txt|md|json|ya?ml|csv|log|bak|ini|cfg|conf|woff2?|ttf|otf|eot)$"
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "0\\.0\\.0\\.0"
    - "expired"
    - "failed"
    - "blocked"
    - "private"
    - "auth"
    - "login"
    - "signup"
    - "register"
    - "forgot-password"
    - "reset-password"
    - "forbidden"
    - "denied"
    - "vip"
    - "paywall"
    - "subscribe"
    - "cart"
    - "checkout"
    - "order"
    - "account"
    - "profile"
    - "dashboard"
    - "admin"
    - "settings"
    - "preferences"
    - "security"
    - "privacy"
    - "terms"
    - "sitemap(\\.xml|\\.html)?"
    - "robots\\.txt"
    - "404|error"
    - "search\\?q="
    - "page=\\d+"
    - "sort="
    - "filter="
    - "category="
    - "\\?(.*&)?utm_(source|medium|campaign|term|content|id)="
    - "\\?(.*&)?_ga="
    - "\\?(.*&)?gclid="
    - "ad(s)?(click)?|banner|affiliate|tracking|pixel|conversion"
    - "doubleclick\\.net"
    - "googlesyndication\\.com"
    - "adservice\\.google\\.com"
    - "cdn-.*?\\.ads|.*?\\.adman|.*?\\.adserver"
    - "click\\?|redirect\\?|outlink\\?"
    - "^mailto:"
    - "^tel:"
    - "^javascript:"
    - "^ftp:"

  # 频道名称过滤词列表
  name_filter_words:
    - "[not 24/7]"
    - "测试"
    - "demo"
    - "backup"
    - "内测"
    - "测试频道"
    - "失效"
    - "已过期"
    - "禁用"
    - "无效"
    - "勿扰"
    - "仅供参考"
    - "过期"
    - "不可用"
    - "样本"
    - "temp"
    - "无效源"
    - "错误"
    - "故障"
    - "未授权"
    - "维护"
    - "调试"
    - "离线"
    - "断流"
    - "待定"
    - "静默"
    - "黑屏"
    - "无信号"
    - "卡顿"
    - "删除"
    - "替换"
    - "备用"
    - "(480p)"
    - "(360p)"
    - "(240p)"
    - "(406p)"
    - "(540p)"
    - "(600p)"
    - "(576p)"
    - "低清"
    - "标清"
    - "流畅"
    - "渣画质"
    - "LQ"
    - "SD"
    - "2K"
    - "4K"
    - "8K"
    - "购物"
    - "理财"
    - "导视"
    - "指南"
    - "广告"
    - "宣传"
    - "推销"
    - "促销"
    - "节目单"
    - "dj"
    - "背景音乐"
    - "纯音乐"
    - "演唱会"
    - "舞曲"
    - "春晚"
    - "粤语歌曲"
    - "粤语音乐"
    - "音乐"
    - "歌曲"
    - "KTV"
    - "MV"
    - "演唱"
    - "剧场"
    - "戏曲"
    - "歌剧"
    - "舞蹈"
    - "脱口秀"
    - "相声"
    - "小品"
    - "体育"
    - "格斗"
    - "足球"
    - "篮球"
    - "排球"
    - "乒乓"
    - "羽毛球"
    - "赛事"
    - "比赛"
    - "游戏"
    - "电竞"
    - "直播"
    - "全景"
    - "祝"
    - "广播"
    - "radio"
    - "fm"
    - "卫星"
    - "芒果"
    - "cgtn"
    - "博斯"
    - "神话"
    - "pcnlid"
    - "sem moderação"
    - "eixo do mal"
    - "卫视"
    - "教育"
    - "纪实"
    - "科教"
    - "生活"
    - "时尚"
    - "旅游"
    - "美食"
    - "健康"
    - "军事"
    - "财经"
    - "访谈"
    - "专题"
    - "回放"
    - "点播"
    - "系列"
    - "精华"
    - "片段"
    - "剪辑"
    - "花絮"
    - "预告"
    - "推荐"
    - "精选"
    - "会员"
    - "加密"
    - "付费"
    - "vip"
    - "订阅"
    - "限定"
    - "独家"
    - "自制"
    - "内部"
    - "私享"
    - "(安徽|北京|重庆|福建|甘肃|广西|贵州|海南|河北|河南|黑龙江|湖北|湖南|吉林|江苏|江西|辽宁|内蒙古|宁夏|青海|山东|山西|陕西|上海|四川|天津|西藏|新疆|云南|浙江)(频道|卫视|电视台|影视频道|新闻频道|综合|教育|都市|生活|公共|综艺|少儿|文化|经济|体育|农村|法制|青少|旅游|艺术|影视|剧|影)$"
    - "^(安徽|北京|重庆|福建|甘肃|广西|贵州|海南|河北|河南|黑龙江|湖北|湖南|吉林|江苏|江西|辽宁|内蒙古|宁夏|青海|山东|山西|陕西|上海|四川|天津|西藏|新疆|云南|浙江)$"
    - "(地方|省级|市级|区级)"

# 频道名称替换规则
channel_name_replacements:
  "AMC电影": "AMC"
  "DWEnglish": "DW"
  "amc电影频英": "AMC"
  "ArirangEnglish": "Arirang"
  "ArirangTV": "Arirang"
  "Arirang综": "Arirang"
  "AXN電影": "AXN"
  "AXN頻道": "AXN"
  "BBC_News": "BBC News"
  "BBCNews": "BBC News"
  "BBC新闻": "BBC News"
  "Bloomberg_TV": "Bloomberg TV"
  "CBSN": "CBS News"
  "CHC动作电影": "CHC动作"
  "CHC家庭电影": "CHC家庭"
  "CHC家庭影院": "CHC家庭"
  "CHC影迷电影": "CHC影迷"
  "CNA": "CNA"
  "CNA亚洲新闻": "CNA"
  "CNN News": "CNN"
  "CNN新闻": "CNN"
  "FOX NEWS": "Fox News"
  "HBo": "HBO"
  "HBO_HD": "HBO"
  "HBOFamily": "HBO家庭"
  "HBO家庭": "HBO家庭"
  "HBO强档": "HBO强档"
  "HBO原创": "HBO原创"
  "MyTime Movie Network": "MyTime Movies"
  "Mytime Movie Network": "MyTime Movies"
  "NBC NEWS": "NBC News"
  "NowNews": "Now新闻"
  "Now新聞": "Now新闻"
  "TVBS": "TVBS新闻"
  "TVBS-Asia": "TVBS亚洲"
  "TVBSAsia(TVBS亚洲)": "TVBS亚洲"
  "NHK新闻英": "NHK"
  "华视戲劇": "华视戏剧"
  "TVBSHD": "TVBS新闻"
  "TVBSNEWS": "TVBS新闻"
  "TVBS新闻": "TVBS新闻"
  "tvbs新闻": "TVBS新闻"
  "TVBS新闻Asia": "TVBS亚洲"
  "TVBS新闻HD": "TVBS新闻"
  "TVBS新闻NEW": "TVBS新闻"
  "TVBS新闻NEWS": "TVBS新闻"
  "TVBS新闻新闻": "TVBS新闻"
  "TVBS新闻新聞": "TVBS新闻"
  "TVBS新闻亚洲": "TVBS亚洲"
  "TVBS新闻亞洲": "TVBS亚洲"
  "tvbs欢乐": "TVBS欢乐"
  "TVBS新闻欢乐": "TVBS欢乐"
  "TVBS亚洲台": "TVBS亚洲"
  "TVBS亞洲": "TVBS亚洲"
  "ELta影剧": "爱尔达影剧"
  "TVBTVBTVB翡翠": "TVB翡翠"
  "TVBTVBTVB翡翠（）": "TVB翡翠"
  "TVBTVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠": "TVB翡翠"
  "TVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠*": "TVB翡翠"
  "TVBTVB翡翠版TVBJ1": "TVB翡翠"
  "TVBTVB翡翠剧集": "TVB翡翠"
  "TVBTVB翡翠台": "TVB翡翠"
  "TVBTVB明珠": "TVB明珠"
  "TVBTVB明珠*": "TVB明珠"
  "TVBTVB明珠剧集": "TVB明珠"
  "TVB翡翠（）": "TVB翡翠"
  "TVB功夫": "TVB功夫"
  "TVB华丽": "TVB华丽"
  "TVB经典电影*": "TVB经典电影"
  "TVB美亚电影": "美亚电影"
  "TVB明珠": "TVB明珠"
  "TVB明珠台": "TVB明珠"
  "TVB千禧经典电影": "TVB千禧经典电影"
  "TVB无线新闻": "TVB新闻"
  "TVB无线新闻*": "TVB新闻"
  "TVB新聞": "TVB新闻"
  "TVB无线星河": "TVB星河"
  "TVB星河国语": "TVB星河"
  "TVB亚洲剧": "TVB亚洲剧"
  "TVB亚洲武侠": "TVB亚洲武侠"
  "TVB娱乐新闻": "TVB娱乐新闻"
  "TW视新闻": "台视新闻"
  "阿里郎": "Arirang"
  "澳门卫星": "澳视资讯"
  "澳門MACAU衛星道": "澳视资讯"
  "澳門資訊": "澳视资讯"
  "澳视澳门": "澳视资讯"
  "澳视综艺": "澳视综艺"
  "澳視澳門": "澳视资讯"
  "八大第1": "八大第一"
  "八大第一": "八大第一"
  "八大综合": "八大綜合"
  "八大綜合": "八大綜合"
  "半·新闻": "半岛新闻"
  "半岛英语": "半岛新闻"
  "半島新聞「英語」": "半岛新闻"
  "东森": "东森新闻"
  "东森卫视": "东森新闻"
  "东森新闻": "东森新闻"
  "东森新闻美洲2": "东森新闻美洲"
  "东森新闻财经新闻": "东森新闻"
  "东森新闻超视": "东森超视"
  "东森新闻超视*": "东森超视"
  "东森新闻电影": "东森电影"
  "东森新闻新闻": "东森新闻"
  "东森新闻亚洲新闻": "东森新闻"
  "东森新闻洋片": "东森洋片"
  "东森新闻洋片*": "东森洋片"
  "东森新闻综合": "东森新闻"
  "东森新闻综合*": "东森新闻"
  "東森財經新聞": "东森新闻"
  "东森新闻[720p]": "东森新闻"
  "東森超視": "东森超视"
  "東森超視34.5": "东森超视"
  "东森超视34.5": "东森超视"
  "東森美洲": "东森美洲"
  "東森新聞": "东森新闻"
  "東森洋片": "东森洋片"
  "東森綜合": "东森新闻"
  "番薯": "番薯台"
  "翡翠": "TVB翡翠"
  "翡翠台": "TVB翡翠"
  "凤凰卫视*": "凤凰中文"
  "凤凰卫视中文": "凤凰中文"
  "凤凰卫视资讯": "凤凰资讯"
  "凤凰中文": "凤凰中文"
  "凤凰资讯": "凤凰资讯"
  "凤凰资讯*": "凤凰资讯"
  "鳳凰中文": "凤凰中文"
  "鳳凰資訊": "凤凰资讯"
  "湖北衛视": "湖北卫视"
  "湖南衛视": "湖南卫视"
  "华视": "华视"
  "华视HD": "华视"
  "华视新闻": "华视新闻"
  "華麗HD": "无线华丽"
  "華視": "华视"
  "華語电视2": "华语电视2"
  "華語电视3": "华语电视3"
  "寰宇新闻": "寰宇新闻"
  "寰宇新聞": "寰宇新闻"
  "寰宇湾[720p]": "寰宇新闻"
  "经典": "经典电影"
  "经典电影": "经典电影"
  "经典影视": "经典电影"
  "靖天國際": "靖天国际"
  "靖天卡通": "靖天卡通"
  "靖天戏剧*": "靖天戏剧"
  "靖天映电影画": "靖天电影"
  "靖天资讯": "靖天资讯"
  "靖天资讯*": "靖天资讯"
  "靖洋戏剧": "靖洋戏剧"
  "镜电视新闻": "镜电视"
  "鏡新聞": "镜电视"
  "镜新闻[720p]": "镜电视"
  "開电视视": "开电视"
  "龍華偶像": "龙华偶像"
  "龍華戲劇": "龙华戏剧"
  "龍華洋片": "龙华洋片"
  "龙华电影[720p]": "龙华电影"
  "龙华经典电影": "龙华电影"
  "龍祥电视影": "龙祥电影"
  "美亚电影粤": "美亚电影"
  "面包": "香港面包"
  "民视": "民视第一"
  "民视湾": "民视第一"
  "民视第一第一": "民视第一"
  "民视新闻": "民视新闻"
  "民视第一新闻HD": "民视新闻"
  "民视新闻*": "民视新闻"
  "民视新闻HD": "民视新闻"
  "民视新闻台HD": "民视新闻"
  "民視": "民视新闻"
  "民視第一": "民视第一"
  "民視第一臺": "民视第一"
  "民視新聞": "民视新闻"
  "明珠": "TVB明珠"
  "求索纪录高清": "求索纪录"
  "三立": "三立综合"
  "三立iNEWS": "三立新闻"
  "三立新闻iNEWS": "三立新闻"
  "三立综合INEWS": "三立新闻"
  "三立综合NEWS+": "三立新闻"
  "三立综合台live": "三立综合"
  "三立综合台新聞": "三立新闻"
  "三立综合湾": "三立新闻"
  "三立综合戏剧": "三立戏剧"
  "三立综合戏剧*": "三立戏剧"
  "三立综合新闻": "三立新闻"
  "三立综合新闻2": "三立新闻"
  "三立综合新聞": "三立新闻"
  "三立综合新聞+": "三立新闻"
  "台視新闻": "台视新闻"
  "臺视新闻": "台视新闻"
  "探索亚洲": "探索亚洲"
  "天映": "天映电影"
  "天映电影": "天映电影"
  "天映电影电影": "天映电影"
  "天映电影经典电影": "天映电影"
  "天映电影经典电影*": "天映电影"
  "天映经典*": "天映电影"
  "无线TVBTVB翡翠": "TVB翡翠"
  "无线TVB翡翠": "TVB翡翠"
  "无线TVB明珠": "TVB明珠"
  "无线TVB明珠粤高": "TVB明珠"
  "无线翡翠台": "TVB翡翠"
  "无线华丽": "TVB华丽"
  "无线华丽国标": "TVB华丽"
  "无线星河": "TVB星河"
  "无线亚洲": "TVBS亚洲"
  "無線新闻": "无线新闻"
  "香港面包": "香港面包"
  "香港卫视HKS": "香港卫视"
  "香港香港面包": "香港面包"
  "新加坡国际": "CNA"
  "新加坡中文": "CNA"
  "新视觉HD": "新视觉"
  "星河台": "TVB星河"
  "亚洲新闻1080P": "CNA"
  "亚洲新闻720P": "CNA"
  "有线新闻": "有线新闻"
  "有線新闻": "有线新闻"
  "有線新闻HD": "有线新闻"
  "中视": "中视经典"
  "中视经典青采[720p]": "中视经典"
  "中视经典": "中视经典"
  "中视新闻": "中视新闻"
  "中视经典新聞": "民视新闻"
  "中視": "中视经典"
  "中視新闻": "中视新闻"
  "中视经典新闻": "中视新闻"
  "中天": "中天新闻"
  "中天新闻台新闻": "中天新闻"
  "中天新闻台新聞": "中天新闻"
  "中天新闻台亚洲": "中天新闻亚洲"
  "中天新闻台娱乐": "中天新闻"
  "中天新闻台综合": "中天新闻"
  "中天新闻新闻": "中天新闻"
  "中天新闻新闻*": "中天新闻"
  "中天新闻新闻2": "中天新闻"
  "中天新闻新聞": "中天新闻"
  "中天新闻新聞「迴圈」": "中天新闻"
  "中天新闻娱乐": "中天新闻"
  "中天新聞台 (1080p)": "中天新闻"
  "[HD]tvb星河(备)": "TVB星河"
  "HKS": "香港卫视"
  "fhd": ""
  "hd": ""
  "频道": ""
  "超清": ""
  "4k": ""
  "4kr": ""
  "20m": ""
  "-": " "
  "测试": ""
  "失效": ""
  "直播": ""
  "省台": ""
  "市台": ""
  "标清": ""
  "低清": ""
  "sd": ""
  "(直播)": ""
  "测试源": ""
  "备用": ""
  "backup": ""
  "临时": ""
  "temp": ""
  "高码": ""
  "梅州": ""
  "东联": ""
  "山东": ""
  "斯特": ""
  "标测": ""
  "频高": ""
  "频标": ""
  "频特": ""
  "限效": ""
  " ": ""
  "▶️": ""
  "🎞️": ""
  "🐼": ""
  "(1080p)": ""
  "(720p)": ""
  "[Geo blocked]": ""
  "(JP)": ""
  "(Korea)": ""
  "(Chile)": ""
  "(Rusia)": ""
  "(Taiwan)": ""
  "(Turquia)": ""
  "(Colombia/USA)": ""
  "(España/UK)": ""
  "(Brasil)": ""
  "(Australia)": ""
  "(Canada)": ""
  "(Alemania)": ""
  "(Ucrania)": ""
  "(Peru)": ""
  "(Uruguay)": ""
  "(Costa Rica)": ""
  "(Ecuador)": ""
  "(El Salvador)": ""
  "(Nicaragua)": ""
  "(Rep. Dominicana)": ""
  "(Italia)": ""
  "(Kosovo)": ""
  "(AU)": ""
  "(BR)": ""
  "(US)": ""
  "(GB)": ""
  "(FR)": ""
  "(DE)": ""
  "(IT)": ""
  "(CA)": ""
  "(IE)": ""
  "(FI)": ""
  "(NL)": ""
  "(AT)": ""
  "(CH)": ""
  "(MX)": ""
  "(ES)": ""
  "(KR)": ""
  "中央": "CCTV"
  "央视": "CCTV"
  "CCTV01": "CCTV1"
  "CCTV02": "CCTV2"
  "CCTV03": "CCTV3"
  "CCTV04": "CCTV4"
  "CCTV05": "CCTV5"
  "CCTV06": "CCTV6"
  "CCTV07": "CCTV7"
  "CCTV08": "CCTV8"
  "CCTV09": "CCTV9"
  "CCTV1 综合": "CCTV1"
  "CCTV2 财经": "CCTV2"
  "CCTV3 综艺": "CCTV3"
  "CCTV4 中文国际": "CCTV4"
  "CCTV4 美洲": "CCTV4美洲"
  "CCTV4 欧洲": "CCTV4欧洲"
  "CCTV5 体育": "CCTV5"
  "CCTV5+ 体育赛事": "CCTV5+"
  "CCTV6 电影": "CCTV6"
  "CCTV7 国防军事": "CCTV7"
  "CCTV8 电视剧": "CCTV8"
  "CCTV9 纪录": "CCTV9"
  "CCTV10 科教": "CCTV10"
  "CCTV11 戏曲": "CCTV11"
  "CCTV12 社会与法": "CCTV12"
  "CCTV13 新闻": "CCTV13"
  "CCTV14 少儿": "CCTV14"
  "CCTV15 音乐": "CCTV15"
  "CCTV16 奥林匹克": "CCTV16"
  "CCTV17 农业农村": "CCTV17"
  "CCTV+": "CCTV"
  "CCTVCCTN 国际": "CCTV国际"
  "CCTVCCTV台球": "CCTV台球"
  "CCTVCCTV文化精品": "CCTV文化精品"
  "CCTV兵器": "CCTV兵器"
  "CCTV精品": "CCTV精品"
  "CCTV赛事": "CCTV赛事"
  "CCTV综合频高": "CCTV1"
  "频道": "频道"
  "视频": "视频"
  "电": "电视"
  "台": ""
  "频": ""
  "标加": ""
  "频国": "粤"
  "频贰": "2"
  "频壹": "1"
  "高特": "2"
  "(HK)": ""
  "[HD]": ""

# 动态分类规则
categories: # 这里的 `categories` 是必须的，用于频道分类和 M3U 排序
  - name: "央视频道"
    pattern: "央视|CCTV"
    file: "CCTV.m3u" # 示例：如果希望将此类别频道单独保存为文件
  - name: "卫视频道"
    pattern: "卫视"
    file: "SatelliteTV.m3u"
  - name: "新闻频道"
    pattern: "新闻|资讯|News|CNN|BBC|Bloomberg|CNA|TVBS新闻|中天新闻|民视新闻|华视新闻|有线新闻|凤凰资讯|半岛新闻|寰宇新闻"
    file: "News.m3u"
  - name: "电影频道"
    pattern: "电影|影院|Movie|Film|HBO|AXN|CHC|经典电影|天映|龙华电影|美亚电影"
    file: "Movies.m3u"
  - name: "体育频道"
    pattern: "体育|Sport|NBA|足球|CCTV5"
    file: "Sports.m3u"
  - name: "少儿和动画频道"
    pattern: "少儿|动画|卡通|Kids|Anime"
    file: "KidsAndAnime.m3u"
  - name: "港澳台频道"
    pattern: "香港|澳门|台湾|TVB|Now|ViuTV|ATV|澳视|八大|东森|三立|华视|民视|中天|台视|镜电视|龙华|靖天"
    file: "HK_MO_TW.m3u"
  - name: "国际频道"
    pattern: "国际|World|International|DW|Arirang"
    file: "International.m3u"
  - name: "娱乐综艺频道"
    pattern: "娱乐|综艺|Variety|Show"
    file: "Entertainment.m3u"
  - name: "综合频道"
    pattern: "综合"
    file: "General.m3u"
  # 可以继续添加其他分类
  - name: "其他" # 默认分类，未匹配的频道将归入此类别
    pattern: ".*" # 匹配所有未被前面规则匹配的频道
    file: "Other.m3u"


# GitHub 搜索配置
search_keywords:
  # 英文关键词
  - "extension:m3u8 in:file"
  - "extension:m3u in:file"
  - "playlist.m3u8 in:file"
  - "index.m3u8 in:file"
  - "channels.m3u in:file"
  - "m3u8 playlist"
  - "m3u channels"
  - "iptv channels"
  - "live tv playlist"
  - "free iptv"
  - "live stream list"
  - "m3u stream"
  - "m3u8 stream"
  - "iptv.m3u"
  - "raw.bgithub.xyz m3u"
  - "cdn.jsdelivr.net m3u"
  - "fastly.net m3u8"
  - "gitee.com m3u"
  - "iptv source"
  - "m3u8 source"
  - "CCTV6"
  - "m3u8 source"
  - "m3u playlist 2025"
  - "m3u playlist 2026"
  - "live channels m3u"
  - "iptv m3u8 2025"
  - "iptv m3u8 2026"
  - "hls stream"
  - "Arirang"
  - "iptv epg"
  - "iptv github"
  - "cloudflare stream m3u8"
  # 中文关键词
  - "阿里郎"
  - "天映电影"
  - "TVB"
  - "TVBS"
  - "年代新闻"
  - "CNA"
  - "CCTV6"
  - "CCTV1"
  - "CCTV5"
  - "CCTV13"
  - "湖南卫视"
  - "浙江卫视"
  - "东方卫视"
  - "江苏卫视"
  - "北京卫视"
  - "凤凰卫视"
  - "海外直播"
  - "体育直播"
  - "电影频道"
  - "少儿频道"
  - "纪录片频道"
  - "音乐频道"
  - "财经频道"
  - "教育频道"
  - "生活频道"
  - "中天新闻"
  - "EPG"
  - "RTHK"
  - "电影"
  - "高清直播"
  - "4K直播"
  - "IPTV2025"
