# IPTV 频道处理脚本的配置文件

# 网络配置
network:
  check_timeout: 8                    # 检查单个频道链接可用性的超时时间（秒）
  request_timeout: 10                 # HTTP 请求超时时间（秒）
  channel_check_workers: 50           # 频道检查的最大线程数
  url_fetch_workers: 10               # URL 内容抓取的最大线程数
  requests_pool_size: 100             # Requests 连接池大小
  requests_retry_total: 0             # Requests 重试总次数
  requests_retry_backoff_factor: 1.5  # Requests 重试间隔回退因子
  max_retries_per_url: 0              # 单个 URL 的最大重试次数

# 日志配置
logging:
  log_level: "DEBUG"                 # 日志级别（DEBUG, INFO, WARNING, ERROR）
  log_file: "logs/iptv.log"          # 日志文件路径

# GitHub API 配置
github: # 合并后的 GitHub 配置块，请确保此行顶格写，无前导空格
  repo_owner: "qjlxg" # 您的GitHub用户名，请保持双引号
  repo_name: "vt" # 您的仓库名称，请保持双引号
  per_page: 100                      # 每页搜索结果数量
  max_search_pages: 5                # 最大搜索页数
  api_timeout: 60                    # GitHub API 请求超时时间（秒）
  retry_wait: 60                     # 速率限制达到后的等待时间（秒）
  rate_limit_threshold: 3            # 触发速率限制的剩余请求阈值
  search_updated_within_days: 30     # 搜索最近更新的文件（天）

# URL 状态管理
url_state: # 请确保此行顶格写，无前导空格
  expiration_days: 10                 # URL 状态过期时间（天）
  cache_enabled: true                # 是否启用内容缓存
  cache_dir: "cache"                 # 缓存目录
  cache_ttl: 604800                  # 缓存有效期（秒，默认为7天）

# 频道保留策略
channel_retention: # 请确保此行顶格写，无前导空格
  stream_fail_threshold: 5            # 流媒体失败次数阈值，超过后移除
  stream_retention_hours: 168        # 流媒体保留时间（小时）
  channel_fail_threshold: 0          # 频道失败次数阈值
  url_fail_threshold: 2              # URL 失败次数阈值，已调整为2，避免过度清理
  url_retention_hours: 72            # URL 保留时间（小时）

# 输出配置
output: # 请确保此行顶格写，无前导空格
  format: "txt"                      # 输出格式（目前支持 txt）
  paths:
    channels_dir: "temp_channels"    # 临时频道文件目录
    output_dir: "output"             # 最终输出目录
    final_iptv_file: "iptv_list.txt" # 最终 IPTV 列表文件
    uncategorized_channels_file: "uncategorized_iptv.txt" # 未分类频道文件
    channel_cache_file: "config/channel_cache.json" # 频道缓存文件
    keyword_stats_file: "config/keyword_stats.json" # 关键词统计文件

# 性能监控
performance_monitor: # 请确保此行顶格写，无前导空格
  enabled: true                      # 是否启用性能监控
  log_interval: 100                  # 性能日志记录间隔（每处理 N 个频道/URL）

# GitHub 搜索关键词
search_keywords: # 请确保此行顶格写，无前导空格
  - "IPTV"                         # 搜索 IPTV 直播源
  - "playlist.m3u8 in:file"        # 直接搜索常见播放列表文件名

# 备用 URL 源
backup_urls: # 请确保此行顶格写，无前导空格
  - "https://raw.githubusercontent.com/example/repo/main/iptv_urls.txt" # 示例备用 URL 1
  - "https://example.com/iptv_list.txt" # 示例备用 URL 2

# 频道名称过滤词（小写匹配）
name_filter_words: # 请确保此行顶格写，无前导空格
  - "购物"                           # 过滤购物频道
  - "理财"                           # 过滤理财频道
  - "导视"                           # 过滤导视频道
  - "指南"                           # 过滤指南频道
  - "芒果"                           # 过滤芒果TV（视具体需求调整）
  - "cgtn"                           # 保留 CGTN（官方媒体）
  - "(480p)"                         # 过滤低分辨率标识
  - "(360p)"                         # 过滤低分辨率标识
  - "(240p)"                         # 过滤低分辨率标识
  - "[not 24/7]"                     # 过滤非全天候直播
  - "dj"                             # 过滤 DJ 相关频道
  - "演唱会"                         # 过滤演唱会内容
  - "舞曲"                           # 过滤舞曲内容
  - "春晚"                           # 过滤春晚内容
  - "格斗"                           # 过滤格斗内容
  - "广播"                           # 过滤广播频道
  - "博斯"                           # 过滤台湾博斯体育频道系列
  - "神话"                           # 过滤神话相关频道
  - "失效"                           # 过滤标有“失效”的频道
  - "demo"                           # 过滤测试频道
  - "backup"                         # 过滤备份频道
  - "内测"                           # 过滤内测频道
  - "测试频道"                       # 过滤测试频道
  - "广告"                           # 过滤广告频道
  - "已过期"                         # 过滤已过期频道
  - "禁用"                           # 过滤禁用频道
  - "无效"                           # 过滤无效频道
  - "勿扰"                           # 过滤标有“勿扰”的频道
  - "仅供参考"                       # 过滤仅供参考的频道
  - "过期"                           # 过滤过期频道
  - "不可用"                         # 过滤不可用频道
  - "样本"                           # 过滤样本频道
  - "temp"                           # 过滤临时频道
  - "radio"                          # 过滤广播频道
  - "fm"                             # 过滤 FM 广播
  - "低清"                           # 过滤低清频道
  - "标清"                           # 过滤标清频道
  - "无效源"                         # 过滤无效源
  - "错误"                           # 过滤错误频道
  - "故障"                           # 过滤故障频道
  - "未授权"                         # 过滤未授权频道
  - "付费"                           # 过滤付费频道
  - "vip"                            # 过滤 VIP 频道
  - "订阅"                           # 过滤订阅频道
  - "sem moderação"                  # 过滤葡萄牙语“无审查”频道
  - "eixo do mal"                    # 过滤葡萄牙语“邪恶轴心”频道

# 频道名称替换规则（键: 待替换内容, 值: 替换后内容，小写匹配）
channel_name_replacements: # 请确保此行顶格写，无前导空格
  fhd: ""                            # 移除 FHD 标识
  hd: ""                             # 移除 HD 标识
  sd: ""                             # 移除 SD 标识
  频道: ""                           # 移除“频道”字样
  高清: ""                           # 移除“高清”字样
  超清: ""                           # 移除“超清”字样
  标清: ""                           # 移除“标清”字样
  低清: ""                           # 移除“低清”字样
  "4k": ""                           # 移除 4K 标识
  "4kr": ""                          # 移除 4KR 标识
  "8k": ""                           # 移除 8K 标识
  "hevc": "H.265"                    # 替换 HEVC 为 H.265
  "h265": "H.265"                    # 替换 H265 为 H.265
  "av1": "AV1"                       # 替换 AV1
  "hdr10+": "HDR"                    # 替换 HDR10+ 为 HDR
  "hdr": "HDR"                       # 保留 HDR
  "(直播)": ""                       # 移除“直播”标识
  "测试": ""                         # 移除“测试”标识
  "失效": ""                         # 移除“失效”标识
  直播: ""                           # 移除“直播”字样
  省台: ""                           # 移除“省台”字样
  市台: ""                           # 移除“市台”字样
  中央: "CCTV"                       # 替换“中央”为 CCTV
  央视: "CCTV"                       # 替换“央视”为 CCTV
  cctv1综合: "CCTV1"                # 替换 CCTV1 综合
  cctv2财经: "CCTV2"                # 替换 CCTV2 财经
  cctv3综艺: "CCTV3"                # 替换 CCTV3 综艺
  cctv4中文国际: "CCTV4"            # 替换 CCTV4 中文国际
  cctv4亚洲: "CCTV4"                # 替换 CCTV4 亚洲
  cctv4欧洲: "CCTV4"                # 替换 CCTV4 欧洲
  cctv4美洲: "CCTV4"                # 替换 CCTV4 美洲
  cctv5体育: "CCTV5"                # 替换 CCTV5 体育
  "cctv5+体育赛事": "CCTV5+"        # 替换 CCTV5+ 体育赛事
  cctv6电影: "CCTV6"                # 替换 CCTV6 电影
  cctv7国防军事: "CCTV7"            # 替换 CCTV7 国防军事
  cctv7军事农业: "CCTV7"            # 替换 CCTV7 军事农业
  cctv8电视剧: "CCTV8"              # 替换 CCTV8 电视剧
  cctv9纪录: "CCTV9"                # 替换 CCTV9 纪录
  cctv10科教: "CCTV10"              # 替换 CCTV10 科教
  cctv11戏曲: "CCTV11"              # 替换 CCTV11 戏曲
  cctv12社会与法: "CCTV12"          # 替换 CCTV12 社会与法
  cctv13新闻: "CCTV13"              # 替换 CCTV13 新闻
  cctv14少儿: "CCTV14"              # 替换 CCTV14 少儿
  cctv15音乐: "CCTV15"              # 替换 CCTV15 音乐
  cctv16奥林匹克: "CCTV16"          # 替换 CCTV16 奥林匹克
  cctv17农业农村: "CCTV17"          # 替换 CCTV17 农业农村
  "cctv-1": "CCTV1"                 # 替换 CCTV-1
  "cctv-5": "CCTV5"                 # 替换 CCTV-5
  湖南卫视高清: "湖南卫视"          # 替换湖南卫视高清
  北京卫视高清: "北京卫视"          # 替换北京卫视高清
  浙江卫视高清: "浙江卫视"          # 替换浙江卫视高清
  江苏卫视高清: "江苏卫视"          # 替换江苏卫视高清
  山东卫视高清: "山东卫视"          # 替换山东卫视高清
  "-": " "                           # 替换连字符为空格
  备用: ""                           # 移除“备用”字样
  backup: ""                         # 移除“backup”字样
  临时: ""                           # 移除“临时”字样
  temp: ""                           # 移除“temp”字样

# 分类配置
ordered_categories: # 请确保此行顶格写，无前导空格
  - CCTV频道
  - 港台频道
  - 国际频道
  - 新闻频道
  - 体育频道
  - 纪录片频道
  - 少儿频道
  - 教育频道
  - 财经频道
  - 音乐频道
  - 生活频道
  - 卫视频道
  - 地方频道

category_keywords: # 请确保此行顶格写，无前导空格
  CCTV频道:
    - CCTV
    - 央视
  卫视频道:
    - 卫视
    - 凤凰
    - 东方
    - 东南
    - 深圳
    - 湖南
    - 浙江
    - 江苏
    - 安徽
    - 湖北
    - 河南
    - 河北
    - 山东
    - 辽宁
    - 吉林
    - 黑龙江
    - 四川
    - 重庆
    - 云南
    - 贵州
    - 陕西
    - 甘肃
    - 青海
    - 宁夏
    - 新疆
    - 福建
    - 江西
    - 广东
    - 广西
    - 海南
    - 天津
    - 上海
    - 北京
    - 西藏
    - 内蒙古
    - 兵团
  地方频道:
    - 城市
    - 镇
    - 县
    - 区
    - 地方
    - 北京卫视
    - 东方卫视
    - 天津卫视
    - 重庆卫视
    - 延边
    - 德州
    - 青州
    - 河源
    - 晋江
    - 徐州
    - 张家港
    - 靖江
    - 栖霞
    - 武进
    - 余姚
    - 余杭
    - 兰考
    - 农安
    - 双滦
    - 吉林市
    - 松原
    - 四平
    - 尚志
    - 嵊州
    - 新昌
    - 柯桥
    - 江阴
    - 清苑
    - 白山
    - 萧山
    - 西安
    - 辽源
    - 通化
    - 鹿邑
    - 黄岛
    - 宿州
    - 邯郸
    - 镇平
    - 龙游
    - 定州
    - 晋城
    - 西宁
    - 乌海
    - 东莞
    - 上虞
  港台频道:
    - 台湾
    - 香港
    - 澳门
    - TVB
    - TVBS
    - 三立
    - 澳视
    - 莲花
    - 华视
    - 中视
    - 公视
  国际频道:
    - CNN
    - BBC
    - NHK
    - RT
    - DW
    - Al Jazeera
    - France 24
    - EuroNews
    - CGTN
    - VOA
    - 越南
    - 乌克兰
    - 意大利
    - 卡塔尔
    - 亚洲新闻
    - Bloomberg
    - Discovery
    - National Geographic
    - Sky News
    - Fox News
  新闻频道:
    - 新闻
    - 资讯
    - News
  体育频道:
    - 体育
    - Sport
    - Sports
    - F1
    - NBA
    - CCTV5
  纪录片频道:
    - 纪录
    - Documentary
    - Geo
    - History
  少儿频道:
    - 少儿
    - 卡通
    - 儿童
    - Kids
    - Manga
    - Ani
  教育频道:
    - 教育
    - 科教
    - Edu
    - Learning
  财经频道:
    - 财经
    - 经济
    - Business
    - Finance
    - stock
    - 证券
    - 股票
  音乐频道:
    - 音乐
    - Music
    - M2
    - V2
    - GOODTV
    - MTV
  生活频道:
    - 生活
    - 都市
    - 民生
    - 休闲
    - 社会
    - 综合
    - 娱乐
    - 综艺
    - 人间
    - 幸福
    - Variety
    - Lifestyle

category_aliases: # 请确保此行顶格写，无前导空格
  新闻综合: 新闻频道
  经济生活: 财经频道
  钱江都市: 卫视频道
  民生休闲: 生活频道
  科教影视: 教育频道
  娱乐: 生活频道
  综艺: 生活频道
  社会生活: 生活频道
  都市生活: 生活频道
  体育: 体育频道
  卡通: 少儿频道
  教育: 教育频道
  财经: 财经频道
  音乐: 音乐频道
  北京频道: 地方频道
  港台频道: 港台频道
  国际频道: 国际频道

# URL 预筛选配置
url_pre_screening: # 请确保此行顶格写，无前导空格
  allowed_protocols:
    - "http"
    - "https"
    - "rtmp"
    - "rtsp"
    - "rtp"
    - "udp"
    - "p3p"
    - "hls"
    - "dash"
    - "webrtc"
  stream_extensions:
    - ".m3u8"
    - ".m3u"
    - ".ts"
    - ".flv"
    - ".mp4"
    - ".aac"
    - ".mp3"
    - ".f4m"
    - ".mpd"
    - ".ism"
  invalid_url_patterns:
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "0\\.0\\.0\\.0"
    - "privateip"
    - "(^|[:/@])10\\."
    - "(^|[:/@])172\\.(1[6-9]|2[0-9]|3[01])\\."
    - "(^|[:/@])192\\.168\\."
    - "dummy"
    - "demo"
    - "null"
    - "invalid"
    - "error"
    - "blank"
    - "sample"
    - "temp"
    - "radio"
    - "fm"
    - "\\.(png|jpg|jpeg|gif|bmp|webp|svg|ico)$"
    - "\\.(css|js|html|htm|xml|txt|md|json|yml|yaml|csv|log|bak|ini|cfg|conf|map|woff|ttf|eot)$"
    - "\\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$"
    - "\\.(pdf|doc|docx|xls|xlsx|ppt|pptx|odt|ods|odp)$"
    - "\\.(exe|dll|msi|apk|dmg|pkg|iso|img|bin|deb|rpm)$"
    - "(\\s|%20)"
    - "github\\.com/(?!.*raw\\.githubusercontent\\.com)"
    - "gist\\.github\\.com/(?!.*raw\\.githubusercontent\\.com)"
    - "gitee\\.com/(?!.*raw)"
    - "youtube\\.com/(watch|embed|live)|youtu\\.be/"
    - "vimeo\\.com"
    - "dailymotion\\.com"
    - "youku\\.com"
    - "iqiyi\\.com"
    - "bilibili\\.com/(video|bangumi|live)"
    - "douyu\\.com"
    - "huya\\.com"
    - "twitch\\.tv"
    - "facebook\\.com/(watch|live|videos)"
    - "twitter\\.com"
    - "instagram\\.com"
    - "tiktok\\.com"
    - "douyin\\.com"
    - "kuaishou\\.com"
    - "music\\.163\\.com"
    - "qq\\.com(?!.*live\\.qq\\.com)"
    - "mp\\.weixin\\.qq\\.com"
    - "api\\."
    - "/api/"
    - "google\\.com/search"
    - "baidu\\.com/s\\?"
    - "swagger"
    - "admin"
    - "login"
    - "register"
    - "signup"
    - "auth"
    - "token="
    - "key="
    - "password="
    - "payment"
    - "subscribe"
    - "vpn"
    - "proxy"
    - "shadowsocks"
    - "v2ray"
    - "trojan"
    - "clash"
    - "surge"
    - "speedtest"
    - "tracker"
    - "torrent"
    - "magnet:"
    - "teststream"
    - "nullstream"
    - "placeholder"
    - "example_stream"
    - "your_stream_url_here"
    - "stream_not_found"
    - "live_streams_not_working"
    - "fake_stream"
    - "dead_stream"
    - "empty\\.m3u8"
    - "error\\.m3u8"
    - "expired\\.m3u8"
    - "failed\\.m3u8"
    - "broken\\.m3u8"
    - "notfound\\.m3u8"
    - "invalid\\.m3u8"
    - "blocked\\.m3u8"
    - "private\\.m3u8"
    - "auth\\.m3u8"
    - "login\\.m3u8"
    - "signup\\.m3u8"
    - "forbidden\\.m3u8"
    - "denied\\.m3u8"
    - "vip\\.m3u8"
    - "paywall\\.m3u8"
    - "subscribe\\.m3u8"
    - "playlist\\.m3u8\\?streamid=0"
    - "/playlist\\.m3u8\\?(uid|userid|token|key)=[^&]+"
    - "/live/.*\\?(_sign|auth_key|playauth|st|wssecret|wstoken|txsecret|txtime|us|ct)=[^&]+"
    - "(ftp|sftp|ftps|telnet|ssh|smb|nfs|rdp|vnc|git|svn|irc|mailto|skype|spotify):"
    - "chinaunicom\\.com"
    - "chinatelecom\\.cn"
    - "chinamobile\\.com"
    - "vnet\\.com"
    - "taobao\\.com"
    - "tmall\\.com"
    - "jd\\.com"
    - "amazon\\.com"
    - "ebay\\.com"
    - "wikipedia\\.org"
    - "apple\\.com"
    - "microsoft\\.com"
