# 频道抓取和检查配置
check_timeout: 15  # 增加到 15 秒以处理慢响应或 HLS 流
request_timeout: 15  # 同步增加请求超时
channel_check_workers: 10
url_fetch_workers: 10

# 日志级别
log_level: "DEBUG"

# URL 状态过期清理
url_state_expiration_days: 90

# 频道保留策略
stream_fail_threshold: 5
stream_retention_hours: 168
channel_fail_threshold: 5
url_fail_threshold: 5
url_retention_hours: 72

# GitHub API 配置（未使用，可保留）
per_page: 30
max_search_pages: 3
github_api_timeout: 20
github_api_retry_wait: 60
rate_limit_threshold: 3
search_updated_within_days: 30

# Requests 配置
requests_pool_size: 100
requests_retry_total: 3
requests_retry_backoff_factor: 1.5

# 缓存配置
url_states_ttl: 604800
channel_cache_ttl: 86400

# 输出格式
output_format: "m3u"

# 文件路径配置
paths:
  channels_dir: "temp_channels"
  output_dir: "output"
  final_iptv_file: "iptv_list.txt"
  uncategorized_channels_file: "uncategorized_channels.txt"
  invalid_urls_file: "config/invalid_urls.txt"
  channel_cache_file: "config/channel_cache.json"
  keyword_stats_file: "config/keyword_stats.json"

# 搜索关键词（未使用，可保留）
search_keywords:
  - "iptv"

# 核心过滤规则
rules:
  url_pre_screening:
    allowed_protocols:
      - "http"
      - "https"
      - "rtmp"
      - "rtp"
      - "p3p"
      - "udp"
      - "rtsp"
    stream_extensions:
      - ".m3u8"
      - ".m3u"
      - ".flv"
      - ".mp4"
      - ".ts"
      - ".hls"
      - ".dash"
      - ".fmp4.m3u8"  # 新增支持 Fragmented MP4 M3U8
  invalid_url_patterns:
    - "\\.(png|jpe?g|gif|bmp|webp|svg|ico|mov|avi|wmv|flv|webm|mp3|wav|ogg|aac|pdf|docx?|xlsx?|pptx?|epub|zip|rar|7z|tar|gz|tgz|bz2|xz|exe|dll|msi|apk|dmg|pkg|iso|img|css|js|xml|txt|md|json|ya?ml|csv|log|bak|ini|cfg|conf|woff2?|ttf|otf|eot)$"
    - "youtube\\.com\\/(watch|embed|live)"
    - "bilibili\\.com"
    - "twitch\\.tv"
    - "facebook\\.com\\/(watch|live)"
    - "twitter\\.com"
    - "instagram\\.com"
    - "linkedin\\.com"
    - "pinterest\\.com"
    - "weibo\\.com"
    - "douyin\\.com"
    - "kuaishou\\.com"
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "0\\.0\\.0\\.0"
    - "login"
    - "signup"
    - "register"
    - "forbidden"
    - "denied"
    - "vip"
    - "paywall"
    - "subscribe"
    - "ad(s)?|banner|affiliate|tracking"
    - "doubleclick\\.net"
    - "googlesyndication\\.com"
    - "^mailto:"
    - "^tel:"
    - "^javascript:"
    - "^ftp:"
  name_filter_words:
    - "测试"
    - "demo"
    - "backup"
    - "失效"
    - "已过期"
    - "禁用"
    - "无效"
    - "过期"
    - "不可用"
    - "temp"
    - "错误"
    - "故障"
    - "未授权"
    - "维护"
    - "离线"
    - "黑屏"
    - "无信号"
    - "购物"
    - "广告"
    - "宣传"
    - "推销"
    - "低清"
    - "标清"
    - "(480p)"
    - "(360p)"
    - "(240p)"
    - "会员"
    - "加密"
    - "付费"
    - "vip"

# 频道名称替换规则（保持不变）
channel_name_replacements:
  "AMC电影": "AMC"
  "DWEnglish": "DW"
  "amc电影频英": "AMC"
  "ArirangEnglish": "Arirang"
  "ArirangTV": "Arirang"
  "Arirang综": "Arirang"
  "AXN電影": "AXN"
  "AXN頻道": "AXN"
  "BBC_News": "BBC News"
  "BBCNews": "BBC News"
  "BBC新闻": "BBC News"
  "Bloomberg_TV": "Bloomberg TV"
  "CBSN": "CBS News"
  "CHC动作电影": "CHC动作"
  "CHC家庭电影": "CHC家庭"
  "CHC家庭影院": "CHC家庭"
  "CHC影迷电影": "CHC影迷"
  "CNA": "CNA"
  "CNA亚洲新闻": "CNA"
  "CNN News": "CNN"
  "CNN新闻": "CNN"
  "FOX NEWS": "Fox News"
  "HBo": "HBO"
  "HBO_HD": "HBO"
  "HBOFamily": "HBO家庭"
  "HBO家庭": "HBO家庭"
  "HBO强档": "HBO强档"
  "HBO原创": "HBO原创"
  "MyTime Movie Network": "MyTime Movies"
  "Mytime Movie Network": "MyTime Movies"
  "NBC NEWS": "NBC News"
  "NowNews": "Now新闻"
  "Now新聞": "Now新闻"
  "TVBS": "TVBS新闻"
  "TVBS-Asia": "TVBS亚洲"
  "TVBSAsia(TVBS亚洲)": "TVBS亚洲"
  "NHK新闻英": "NHK"
  "华视戲劇": "华视戏剧"
  "TVBSHD": "TVBS新闻"
  "TVBSNEWS": "TVBS新闻"
  "TVBS新闻": "TVBS新闻"
  "tvbs新闻": "TVBS新闻"
  "TVBS新闻Asia": "TVBS亚洲"
  "TVBS新闻HD": "TVBS新闻"
  "TVBS新闻NEW": "TVBS新闻"
  "TVBS新闻NEWS": "TVBS新闻"
  "TVBS新闻新闻": "TVBS新闻"
  "TVBS新闻新聞": "TVBS新闻"
  "TVBS新闻亚洲": "TVBS亚洲"
  "TVBS新闻亞洲": "TVBS亚洲"
  "tvbs欢乐": "TVBS欢乐"
  "TVBS新闻欢乐": "TVBS欢乐"
  "TVBS亚洲台": "TVBS亚洲"
  "TVBS亞洲": "TVBS亚洲"
  "ELta影剧": "爱尔达影剧"
  "TVBTVBTVB翡翠": "TVB翡翠"
  "TVBTVBTVB翡翠（）": "TVB翡翠"
  "TVBTVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠": "TVB翡翠"
  "TVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠*": "TVB翡翠"
  "TVBTVB翡翠版TVBJ1": "TVB翡翠"
  "TVBTVB翡翠剧集": "TVB翡翠"
  "TVBTVB翡翠台": "TVB翡翠"
  "TVBTVB明珠": "TVB明珠"
  "TVBTVB明珠*": "TVB明珠"
  "TVBTVB明珠剧集": "TVB明珠"
  "TVB翡翠（）": "TVB翡翠"
  "TVB功夫": "TVB功夫"
  "TVB华丽": "TVB华丽"
  "TVB经典电影*": "TVB经典电影"
  "TVB美亚电影": "美亚电影"
  "TVB明珠": "TVB明珠"
  "TVB明珠台": "TVB明珠"
  "TVB千禧经典电影": "TVB千禧经典电影"
  "TVB无线新闻": "TVB新闻"
  "TVB无线新闻*": "TVB新闻"
  "TVB新聞": "TVB新闻"
  "TVB无线星河": "TVB星河"
  "TVB星河国语": "TVB星河"
  "TVB亚洲剧": "TVB亚洲剧"
  "TVB亚洲武侠": "TVB亚洲武侠"
  "TVB娱乐新闻": "TVB娱乐新闻"
  "TW视新闻": "台视新闻"
  "阿里郎": "Arirang"
  "澳门卫星": "澳视资讯"
  "澳門MACAU衛星道": "澳视资讯"
  "澳門資訊": "澳视资讯"
  "澳视澳门": "澳视资讯"
  "澳视综艺": "澳视综艺"
  "澳視澳門": "澳视资讯"
  "八大第1": "八大第一"
  "八大第一": "八大第一"
  "八大综合": "八大綜合"
  "八大綜合": "八大綜合"
  "半·新闻": "半岛新闻"
  "半岛英语": "半岛新闻"
  "半島新聞「英語」": "半岛新闻"
  "东森": "东森新闻"
  "东森卫视": "东森新闻"
  "东森新闻": "东森新闻"
  "东森新闻美洲2": "东森新闻美洲"
  "东森新闻财经新闻": "东森新闻"
  "东森新闻超视": "东森超视"
  "东森新闻超视*": "东森超视"
  "东森新闻电影": "东森电影"
  "东森新闻新闻": "东森新闻"
  "东森新闻亚洲新闻": "东森新闻"
  "东森新闻洋片": "东森洋片"
  "东森新闻洋片*": "东森洋片"
  "东森新闻综合": "东森新闻"
  "东森新闻综合*": "东森新闻"
  "東森財經新聞": "东森新闻"
  "东森新闻[720p]": "东森新闻"
  "東森超視": "东森超视"
  "東森超視34.5": "东森超视"
  "东森超视34.5": "东森超视"
  "東森美洲": "东森美洲"
  "東森新聞": "东森新闻"
  "東森洋片": "东森洋片"
  "東森綜合": "东森新闻"
  "番薯": "番薯台"
  "翡翠": "TVB翡翠"
  "翡翠台": "TVB翡翠"
  "凤凰卫视*": "凤凰中文"
  "凤凰卫视中文": "凤凰中文"
  "凤凰卫视资讯": "凤凰资讯"
  "凤凰中文": "凤凰中文"
  "凤凰资讯": "凤凰资讯"
  "凤凰资讯*": "凤凰资讯"
  "鳳凰中文": "凤凰中文"
  "鳳凰資訊": "凤凰资讯"
  "湖北衛视": "湖北卫视"
  "湖南衛视": "湖南卫视"
  "华视": "华视"
  "华视HD": "华视"
  "华视新闻": "华视新闻"
  "華麗HD": "无线华丽"
  "華視": "华视"
  "華語电视2": "华语电视2"
  "華語电视3": "华语电视3"
  "寰宇新闻": "寰宇新闻"
  "寰宇新聞": "寰宇新闻"
  "寰宇湾[720p]": "寰宇新闻"
  "经典": "经典电影"
  "经典电影": "经典电影"
  "经典影视": "经典电影"
  "靖天國際": "靖天国际"
  "靖天卡通": "靖天卡通"
  "靖天戏剧*": "靖天戏剧"
  "靖天映电影画": "靖天电影"
  "靖天资讯": "靖天资讯"
  "靖天资讯*": "靖天资讯"
  "靖洋戏剧": "靖洋戏剧"
  "镜电视新闻": "镜电视"
  "鏡新聞": "镜电视"
  "镜新闻[720p]": "镜电视"
  "開电视视": "开电视"
  "龍華偶像": "龙华偶像"
  "龍華戲劇": "龙华戏剧"
  "龍華洋片": "龙华洋片"
  "民视": "民视"
  "民视新闻": "民视新闻"
  "民視": "民视"
  "民視新聞": "民视新闻"
  "民视台湾": "民视台湾"
  "民視台灣": "民视台湾"
  "民视综艺": "民视综艺"
  "民視綜合": "民视综艺"
  "三立": "三立新闻"
  "三立LIVE": "三立新闻"
  "三立LIVE新闻": "三立新闻"
  "三立LIVE新聞": "三立新闻"
  "三立新闻": "三立新闻"
  "三立新聞": "三立新闻"
  "三立財經": "三立财经"
  "三立综合": "三立综合"
  "三立綜合": "三立综合"
  "台視": "台视"
  "台視新聞": "台视新闻"
  "台视新闻": "台视新闻"
  "纬来": "纬来"
  "纬来电影": "纬来电影"
  "纬来体育": "纬来体育"
  "纬来綜合": "纬来综合"
  "無綫新聞": "TVB新闻"
  "無線新聞": "TVB新闻"
  "无线新闻": "TVB新闻"
  "无线星河": "TVB星河"
  "无线娱乐新闻": "TVB娱乐新闻"
  "无线娱乐新聞": "TVB娱乐新闻"
  "新闻台": "新闻台"
  "壹新闻": "壹新闻"
  "壹新聞": "壹新闻"
  "中天": "中天新闻"
  "中天新闻": "中天新闻"
  "中天新聞": "中天新闻"
  "中天综合": "中天综合"
  "中天綜合": "中天综合"
  "中視": "中视"
  "中視新聞": "中视新闻"
  "中视新闻": "中视新闻"

# 频道分类规则
categories:
  - name: "CCTV"
    file: "output/CCTV.m3u"
    pattern: "CCTV|中央电视台|中央台"
  - name: "News"
    file: "output/News.m3u"
    pattern: "News|新闻|資訊|财经|財經"
  - name: "Movies"
    file: "output/Movies.m3u"
    pattern: "Movie|电影|影院|洋片|動作|家庭|影迷"
  - name: "Sports"
    file: "output/Sports.m3u"
    pattern: "Sports|体育|運動"
  - name: "Entertainment"
    file: "output/Entertainment.m3u"
    pattern: "Entertainment|娱乐|綜藝|综合|戲劇|戏剧|偶像|卡通"
  - name: "International"
    file: "output/International.m3u"
    pattern: "International|國際|BBC|CNN|NHK|DW|Arirang|CNA"
