# IPTV 频道处理脚本的配置文件
# 说明：此配置文件用于 tv.py 脚本，控制 IPTV 源抓取、分类、过滤和输出。
# 格式：YAML，所有字段需遵循 YAML 语法，顶级字段顶格写，子字段缩进 2 个空格。

# GitHub 搜索关键词
search_keywords:

 # 核心英文关键词 (精确匹配文件扩展名和路径)
  - "extension:m3u8 in:file"
  - "extension:m3u in:file"
  - "iptv playlist extension:m3u,m3u8 in:file"
  - "raw.githubusercontent.com path:.m3u8"
  - "raw.githubusercontent.com path:.m3u"
  - "tv channels extension:m3u,m3u8 in:file"
  - "live tv extension:m3u,m3u8 in:file"
  - "playlist.m3u8 in:file" # 直接搜索常见播放列表文件名
  - "index.m3u8 in:file"
  - "channels.m3u in:file"
  - "iptv.m3u in:file" # 增加常见iptv文件名搜索

# URL 预筛选配置：定义 URL 筛选规则
url_pre_screening:
  invalid_url_patterns: # 无效 URL 的正则模式
    - '\.jpg$'
    - '\.png$'
    - '\.gif$'
    - '\.pdf$'
    - '\.exe$'
    - 'login'
    - 'signup'
    - 'private'
    - 'localhost'
    - '^http://171\.8\.247\.154:808' # 排除特定 URL: http://171.8.247.154:808
    - '^https://vv\.jisuzyv\.com' # 排除特定 URL: https://vv.jisuzyv.com
    - '^https://t\.me/'
    - '\.php$'

# 网络配置
network:
  check_timeout: 20                  # 检查单个频道链接可用性的超时时间（秒，默认 20）
  request_timeout: 10                # HTTP 请求超时时间（秒，默认 10）
  channel_check_workers: 50          # 频道检查的最大线程数（默认 50，视机器性能调整）
  url_fetch_workers: 10              # URL 内容抓取的最大线程数（默认 10）
  requests_pool_size: 100            # Requests 连接池大小（默认 100）
  requests_retry_total: 1            # Requests 重试总次数（默认 3）
  requests_retry_backoff_factor: 1   # Requests 重试间隔回退因子（默认 1）
  max_retries_per_url: 1            # 单个 URL 的最大重试次数（默认 3）

# 日志配置
logging:
  log_level: "INFO"                 # 日志级别（DEBUG, INFO, WARNING, ERROR，默认 INFO）
  log_file: "logs/iptv.log"         # 日志文件路径（默认 logs/iptv.log）

# GitHub API 配置
github:
  repo_owner: "qjlxg"               # GitHub 用户名
  repo_name: "vt"                   # GitHub 仓库名称
  per_page: 100                     # 每页搜索结果数量（默认 100）
  max_search_pages: 10              # 最大搜索页数（默认 10）
  api_timeout: 60                   # GitHub API 请求超时时间（秒，默认 60）
  retry_wait: 30                    # 速率限制达到后的等待时间（秒，默认 30）
  rate_limit_threshold: 3           # 触发速率限制的剩余请求阈值（默认 3）
  search_updated_within_days: 30    # 搜索最近更新的文件（天，默认 30）

# URL 状态管理
url_state:
  expiration_days: 7                # URL 状态过期时间（天，默认 7）
  cache_enabled: true               # 是否启用内容缓存（默认 true）
  cache_dir: "cache"                # 缓存目录（默认 cache）
  cache_ttl: 604800                 # 缓存有效期（秒，默认 7 天）

# 频道保留策略
channel_retention:
  stream_fail_threshold: 5          # 流媒体失败次数阈值，超过后移除（默认 5）
  stream_retention_hours: 168       # 流媒体保留时间（小时，默认 168）
  channel_fail_threshold: 0         # 频道失败次数阈值（默认 0，禁用）
  url_fail_threshold: 3             # URL 失败次数阈值（默认 3）
  url_retention_hours: 72           # URL 保留时间（小时，默认 72）

# 输出配置
output:
  format: "txt"                     # 输出格式（目前支持 txt）
  paths:
    channels_dir: "temp_channels"   # 临时频道文件目录（默认 temp_channels）
    output_dir: "output"            # 最终输出目录（默认 output）
    final_iptv_file: "output/iptv_list.txt" # 最终 IPTV 列表文件
    uncategorized_channels_file: "output/uncategorized_iptv.txt" # 未分类频道输出文件
    high_quality_iptv_file: "output/high_quality_iptv.txt" # 高质量频道列表文件
    channel_cache_file: "config/channel_cache.json" # 频道缓存文件
    keyword_stats_file: "config/keyword_stats.json" # 关键词统计文件

# 性能监控
performance_monitor:
  enabled: true                     # 是否启用性能监控（默认 true）
  log_interval: 100                # 性能日志记录间隔（每处理 N 个频道/URL，默认 100）



# 备用 URL 源
backup_urls:
  - "https://raw.githubusercontent.com/example/repo/main/iptv_urls.txt" # 示例备用 URL 1
  - "https://example.com/iptv_list.txt" # 示例备用 URL 2

# 频道名称过滤词（小写匹配，过滤包含以下词的频道）
name_filter_words:
  - "之声"                         # 过滤广播类频道
  - "购物"                         # 过滤购物频道
  - "理财"                         # 过滤理财频道
  - "导视"                         # 过滤导视频道
  - "指南"                         # 过滤指南频道
  - "芒果"                         # 过滤芒果TV（可根据需求调整）
  - "(480p)"                       # 过滤低分辨率标识
  - "(360p)"                       # 过滤低分辨率标识
  - "(240p)"                       # 过滤低分辨率标识
  - "[not 24/7]"                   # 过滤非全天候直播
  - "dj"                           # 过滤 DJ 相关频道
  - "演唱会"                       # 过滤演唱会内容
  - "舞曲"                         # 过滤舞曲内容
  - "春晚"                         # 过滤春晚内容
  - "格斗"                         # 过滤格斗内容
  - "广播"                         # 过滤广播频道
  - "博斯"                         # 过滤台湾博斯体育频道
  - "神话"                         # 过滤神话相关频道
  - "失效"                         # 过滤标有“失效”的频道
  - "demo"                         # 过滤测试频道
  - "backup"                       # 过滤备份频道
  - "内测"                         # 过滤内测频道
  - "测试频道"                     # 过滤测试频道
  - "广告"                         # 过滤广告频道
  - "已过期"                       # 过滤已过期频道
  - "禁用"                         # 过滤禁用频道
  - "无效"                         # 过滤无效频道
  - "勿扰"                         # 过滤标有“勿扰”的频道
  - "仅供参考"                     # 过滤仅供参考的频道
  - "过期"                         # 过滤过期频道
  - "不可用"                       # 过滤不可用频道
  - "样本"                         # 过滤样本频道
  - "temp"                         # 过滤临时频道
  - "radio"                        # 过滤广播频道
  - "fm"                           # 过滤 FM 广播
  - "低清"                         # 过滤低清频道
  - "标清"                         # 过滤标清频道
  - "无效源"                       # 过滤无效源
  - "错误"                         # 过滤错误频道
  - "故障"                         # 过滤故障频道
  - "未授权"                       # 过滤未授权频道
  - "付费"                         # 过滤付费频道
  - "vip"                          # 过滤 VIP 频道
  - "订阅"                         # 过滤订阅频道
  - "预告片"                       # 过滤预告片频道
  - "重播"                         # 过滤重播频道
  - "试播"                         # 过滤试播频道
  - "4g"                           # 过滤 4G 低速频道
  - "低速"                         # 过滤低速频道
  - "sem moderação"                # 过滤葡萄牙语“无审查”频道
  - "eixo do mal"                  # 过滤葡萄牙语“邪恶轴心”频道

# 频道名称替换规则（键: 待替换内容, 值: 替换后内容，小写匹配）
channel_name_replacements:
  fhd: ""                          # 移除 FHD 标识
  hd: ""                           # 移除 HD 标识
  sd: ""                           # 移除 SD 标识
  频道: ""                         # 移除“频道”字样
  高清: ""                         # 移除“高清”字样
  超清: ""                         # 移除“超清”字样
  标清: ""                         # 移除“标清”字样
  低清: ""                         # 移除“低清”字样
  "4k": ""                         # 移除 4K 标识
  "4kr": ""                        # 移除 4KR 标识
  "8k": ""                         # 移除 8K 标识
  "hevc": "H.265"                  # 替换 HEVC 为 H.265
  "h265": "H.265"                  # 替换 H265 为 H.265
  "av1": "AV1"                     # 替换 AV1
  "hdr10+": "HDR"                  # 替换 HDR10+ 为 HDR
  "hdr": "HDR"                     # 保留 HDR
  "(直播)": ""                     # 移除“直播”标识
  "测试": ""                       # 移除“测试”标识
  "失效": ""                       # 移除“失效”标识
  直播: ""                         # 移除“直播”字样
  省台: ""                         # 移除“省台”字样
  市台: ""                         # 移除“市台”字样
  备用: ""                         # 移除“备用”字样
  backup: ""                       # 移除“backup”字样
  临时: ""                         # 移除“临时”字样
  temp: ""                         # 移除“temp”字样
  测试源: ""                       # 移除“测试源”字样
  备用源: ""                       # 移除“备用源”字样
  中央: "CCTV"                     # 替换“中央”为 CCTV
  央视: "CCTV"                     # 替换“央视”为 CCTV
  中央电视台: "CCTV"               # 替换“中央电视台”为 CCTV
  cctv1综合: "CCTV1"              # 替换 CCTV1 综合
  cctv2财经: "CCTV2"              # 替换 CCTV2 财经
  cctv3综艺: "CCTV3"              # 替换 CCTV3 综艺
  cctv4中文国际: "CCTV4"          # 替换 CCTV4 中文国际
  cctv4亚洲: "CCTV4"              # 替换 CCTV4 亚洲
  cctv4欧洲: "CCTV4"              # 替换 CCTV4 欧洲
  cctv4美洲: "CCTV4"              # 替换 CCTV4 美洲
  cctv5体育: "CCTV5"              # 替换 CCTV5 体育
  "cctv5+体育赛事": "CCTV5+"      # 替换 CCTV5+ 体育赛事
  cctv6电影: "CCTV6"              # 替换 CCTV6 电影
  cctv7国防军事: "CCTV7"          # 替换 CCTV7 国防军事
  cctv7军事农业: "CCTV7"          # 替换 CCTV7 军事农业
  cctv8电视剧: "CCTV8"            # 替换 CCTV8 电视剧
  cctv9纪录: "CCTV9"              # 替换 CCTV9 纪录
  cctv10科教: "CCTV10"            # 替换 CCTV10 科教
  cctv11戏曲: "CCTV11"            # 替换 CCTV11 戏曲
  cctv12社会与法: "CCTV12"        # 替换 CCTV12 社会与法
  cctv13新闻: "CCTV13"            # 替换 CCTV13 新闻
  cctv14少儿: "CCTV14"            # 替换 CCTV14 少儿
  cctv15音乐: "CCTV15"            # 替换 CCTV15 音乐
  cctv16奥林匹克: "CCTV16"        # 替换 CCTV16 奥林匹克
  cctv17农业农村: "CCTV17"        # 替换 CCTV17 农业农村
  "cctv-1": "CCTV1"               # 替换 CCTV-1
  "cctv-2": "CCTV2"               # 替换 CCTV-2
  "cctv-5": "CCTV5"               # 替换 CCTV-5
  "cctv-5+": "CCTV5+"             # 替换 CCTV-5+
  湖南卫视高清: "湖南卫视"        # 替换湖南卫视高清
  北京卫视高清: "北京卫视"        # 替换北京卫视高清
  浙江卫视高清: "浙江卫视"        # 替换浙江卫视高清
  江苏卫视高清: "江苏卫视"        # 替换江苏卫视高清
  山东卫视高清: "山东卫视"        # 替换山东卫视高清
  安徽卫视高清: "安徽卫视"        # 替换安徽卫视高清
  湖北卫视高清: "湖北卫视"        # 替换湖北卫视高清
  河南卫视高清: "河南卫视"        # 替换河南卫视高清
  河北卫视高清: "河北卫视"        # 替换河北卫视高清
  辽宁卫视高清: "辽宁卫视"        # 替换辽宁卫视高清
  吉林卫视高清: "吉林卫视"        # 替换吉林卫视高清
  黑龙江卫视高清: "黑龙江卫视"    # 替换黑龙江卫视高清
  四川卫视高清: "四川卫视"        # 替换四川卫视高清
  重庆卫视高清: "重庆卫视"        # 替换重庆卫视高清
  云南卫视高清: "云南卫视"        # 替换云南卫视高清
  贵州卫视高清: "贵州卫视"        # 替换贵州卫视高清
  陕西卫视高清: "陕西卫视"        # 替换陕西卫视高清
  甘肃卫视高清: "甘肃卫视"        # 替换甘肃卫视高清
  青海卫视高清: "青海卫视"        # 替换青海卫视高清
  宁夏卫视高清: "宁夏卫视"        # 替换宁夏卫视高清
  新疆卫视高清: "新疆卫视"        # 替换新疆卫视高清
  福建卫视高清: "福建卫视"        # 替换福建卫视高清
  江西卫视高清: "江西卫视"        # 替换江西卫视高清
  广东卫视高清: "广东卫视"        # 替换广东卫视高清
  广西卫视高清: "广西卫视"        # 替换广西卫视高清
  海南卫视高清: "海南卫视"        # 替换海南卫视高清
  天津卫视高清: "天津卫视"        # 替换天津卫视高清
  上海卫视高清: "东方卫视"        # 替换上海卫视高清
  西藏卫视高清: "西藏卫视"        # 替换西藏卫视高清
  内蒙古卫视高清: "内蒙古卫视"    # 替换内蒙古卫视高清
  兵团卫视高清: "兵团卫视"        # 替换兵团卫视高清
  "-": " "                         # 替换连字符为空格
  "AMC电影": "AMC"
  "DWEnglish": "DW"
  "amc电影频英": "AMC"
  "ArirangEnglish": "Arirang"
  "ArirangTV": "Arirang"
  "Arirang综": "Arirang"
  "AXN電影": "AXN"
  "AXN頻道": "AXN"
  "BBC_News": "BBC News"
  "BBCNews": "BBC News"
  "BBC新闻": "BBC News"
  "Bloomberg_TV": "Bloomberg TV"
  "CBSN": "CBS News"
  "CHC动作电影": "CHC动作"
  "CHC家庭电影": "CHC家庭"
  "CHC家庭影院": "CHC家庭"
  "CHC影迷电影": "CHC影迷"
  "CNA": "CNA"
  "CNA亚洲新闻": "CNA"
  "CNN News": "CNN"
  "CNN新闻": "CNN"
  "FOX NEWS": "Fox News"
  "HBo": "HBO"
  "HBO_HD": "HBO"
  "HBOFamily": "HBO家庭"
  "HBO家庭": "HBO家庭"
  "HBO强档": "HBO强档"
  "HBO原创": "HBO原创"
  "MyTime Movie Network": "MyTime Movies"
  "Mytime Movie Network": "MyTime Movies"
  "NBC NEWS": "NBC News"
  "NowNews": "Now新闻"
  "Now新聞": "Now新闻"
  "TVBS": "TVBS新闻"
  "TVBS-Asia": "TVBS亚洲"
  "TVBSAsia(TVBS亚洲)": "TVBS亚洲"
  "NHK新闻英": "NHK"
  "华视戲劇": "华视戏剧"
  "TVBSHD": "TVBS新闻"
  "TVBSNEWS": "TVBS新闻"
  "TVBS新闻": "TVBS新闻"
  "tvbs新闻": "TVBS新闻"
  "TVBS新闻Asia": "TVBS亚洲"
  "TVBS新闻HD": "TVBS新闻"
  "TVBS新闻NEW": "TVBS新闻"
  "TVBS新闻NEWS": "TVBS新闻"
  "TVBS新闻新闻": "TVBS新闻"
  "TVBS新闻新聞": "TVBS新闻"
  "TVBS新闻亚洲": "TVBS亚洲"
  "TVBS新闻亞洲": "TVBS亚洲"
  "tvbs欢乐": "TVBS欢乐"
  "TVBS新闻欢乐": "TVBS欢乐"
  "TVBS亚洲台": "TVBS亚洲"
  "TVBS亞洲": "TVBS亚洲"
  "ELta影剧": "爱尔达影剧"
  "TVBTVBTVB翡翠": "TVB翡翠"
  "TVBTVBTVB翡翠（）": "TVB翡翠"
  "TVBTVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠": "TVB翡翠"
  "TVBTVB翡翠4K": "TVB翡翠"
  "TVBTVB翡翠*": "TVB翡翠"
  "TVBTVB翡翠版TVBJ1": "TVB翡翠"
  "TVBTVB翡翠剧集": "TVB翡翠"
  "TVBTVB翡翠台": "TVB翡翠"
  "TVBTVB明珠": "TVB明珠"
  "TVBTVB明珠*": "TVB明珠"
  "TVBTVB明珠剧集": "TVB明珠"
  "TVB翡翠（）": "TVB翡翠"
  "TVB功夫": "TVB功夫"
  "TVB华丽": "TVB华丽"
  "TVB经典电影*": "TVB经典电影"
  "TVB美亚电影": "美亚电影"
  "TVB明珠": "TVB明珠"
  "TVB明珠台": "TVB明珠"
  "TVB千禧经典电影": "TVB千禧经典电影"
  "TVB无线新闻": "TVB新闻"
  "TVB无线新闻*": "TVB新闻"
  "TVB新聞": "TVB新闻"
  "TVB无线星河": "TVB星河"
  "TVB星河国语": "TVB星河"
  "TVB亚洲剧": "TVB亚洲剧"
  "TVB亚洲武侠": "TVB亚洲武侠"
  "TVB娱乐新闻": "TVB娱乐新闻"
  "TW视新闻": "台视新闻"
  "阿里郎": "Arirang"
  "澳门卫星": "澳视资讯"
  "澳門MACAU衛星道": "澳视资讯"
  "澳門資訊": "澳视资讯"
  "澳视澳门": "澳视资讯"
  "澳视综艺": "澳视综艺"
  "澳視澳門": "澳视资讯"
  "八大第1": "八大第一"
  "八大第一": "八大第一"
  "八大综合": "八大綜合"
  "八大綜合": "八大綜合"
  "半·新闻": "半岛新闻"
  "半岛英语": "半岛新闻"
  "半島新聞「英語」": "半岛新闻"
  "东森": "东森新闻"
  "东森卫视": "东森新闻"
  "东森新闻": "东森新闻"
  "东森新闻美洲2": "东森新闻美洲"
  "东森新闻财经新闻": "东森新闻"
  "东森新闻超视": "东森超视"
  "东森新闻超视*": "东森超视"
  "东森新闻电影": "东森电影"
  "东森新闻新闻": "东森新闻"
  "东森新闻亚洲新闻": "东森新闻"
  "东森新闻洋片": "东森洋片"
  "东森新闻洋片*": "东森洋片"
  "东森新闻综合": "东森新闻"
  "东森新闻综合*": "东森新闻"
  "東森財經新聞": "东森新闻"
  "东森新闻[720p]": "东森新闻"
  "東森超視": "东森超视"
  "東森超視34.5": "东森超视"
  "东森超视34.5": "东森超视"
  "東森美洲": "东森美洲"
  "東森新聞": "东森新闻"
  "東森洋片": "东森洋片"
  "東森綜合": "东森新闻"
  "番薯": "番薯台"
  "翡翠": "TVB翡翠"
  "翡翠台": "TVB翡翠"
  "凤凰卫视*": "凤凰中文"
  "凤凰卫视中文": "凤凰中文"
  "凤凰卫视资讯": "凤凰资讯"
  "凤凰中文": "凤凰中文"
  "凤凰资讯": "凤凰资讯"
  "凤凰资讯*": "凤凰资讯"
  "鳳凰中文": "凤凰中文"
  "鳳凰資訊": "凤凰资讯"
  "湖北衛视": "湖北卫视"
  "湖南衛视": "湖南卫视"
  "华视": "华视"
  "华视HD": "华视"
  "华视新闻": "华视新闻"
  "華麗HD": "无线华丽"
  "華視": "华视"
  "華語电视2": "华语电视2"
  "華語电视3": "华语电视3"
  "寰宇新闻": "寰宇新闻"
  "寰宇新聞": "寰宇新闻"
  "寰宇湾[720p]": "寰宇新闻"
  "经典": "经典电影"
  "经典电影": "经典电影"
  "经典影视": "经典电影"
  "靖天國際": "靖天国际"
  "靖天卡通": "靖天卡通"
  "靖天戏剧*": "靖天戏剧"
  "靖天映电影画": "靖天电影"
  "靖天资讯": "靖天资讯"
  "靖天资讯*": "靖天资讯"
  "靖洋戏剧": "靖洋戏剧"
  "镜电视新闻": "镜电视"
  "鏡新聞": "镜电视"
  "镜新闻[720p]": "镜电视"
  "開电视视": "开电视"
  "龍華偶像": "龙华偶像"
  "龍華戲劇": "龙华戏剧"
  "龍華洋片": "龙华洋片"
  "民视": "民视"
  "民视新闻": "民视新闻"
  "民視": "民视"
  "民視新聞": "民视新闻"
  "民视台湾": "民视台湾"
  "民視台灣": "民视台湾"
  "民视综艺": "民视综艺"
  "民視綜合": "民视综艺"
  "三立": "三立新闻"
  "三立LIVE": "三立新闻"
  "三立LIVE新闻": "三立新闻"
  "三立LIVE新聞": "三立新闻"
  "三立新闻": "三立新闻"
  "三立新聞": "三立新闻"
  "三立財經": "三立财经"
  "三立综合": "三立综合"
  "三立綜合": "三立综合"
  "台視": "台视"
  "台視新聞": "台视新闻"
  "台视新闻": "台视新闻"
  "纬来": "纬来"
  "纬来电影": "纬来电影"
  "纬来体育": "纬来体育"
  "纬来綜合": "纬来综合"
  "無綫新聞": "TVB新闻"
  "無線新聞": "TVB新闻"
  "无线新闻": "TVB新闻"
  "无线星河": "TVB星河"
  "无线娱乐新闻": "TVB娱乐新闻"
  "无线娱乐新聞": "TVB娱乐新闻"
  "新闻台": "新闻台"
  "壹新闻": "壹新闻"
  "壹新聞": "壹新闻"
  "中天": "中天新闻"
  "中天新闻": "中天新闻"
  "中天新聞": "中天新闻"
  "中天综合": "中天综合"
  "中天綜合": "中天综合"
  "中視": "中视"
  "中視新聞": "中视新闻"
  "中视新闻": "中视新闻"
# 分类配置
ordered_categories:
  - CCTV频道
  - 卫视频道
  - 地方频道
  - 港台频道
  - 国际频道
  - 新闻频道
  - 体育频道
  - 电影频道
  - 综艺频道
  - 纪录片频道
  - 少儿频道
  - 教育频道
  - 财经频道
  - 音乐频道
  - 生活频道
  - 戏曲频道

category_keywords:
  CCTV频道:
    - CCTV
    - 央视
    - 中央
    - 中央电视台
  卫视频道:
    - 卫视
    - 凤凰
    - 东方
    - 东南
    - 深圳
    - 湖南
    - 浙江
    - 江苏
    - 安徽
    - 湖北
    - 河南
    - 河北
    - 山东
    - 山西
    - 辽宁
    - 吉林
    - 黑龙江
    - 四川
    - 重庆
    - 云南
    - 贵州
    - 陕西
    - 甘肃
    - 青海
    - 宁夏
    - 新疆
    - 福建
    - 江西
    - 广东
    - 广西
    - 海南
    - 天津
    - 上海
    - 北京
    - 西藏
    - 内蒙古
    - 兵团
  地方频道:
    - 城市
    - 镇
    - 县
    - 区
    - 地方
    - 北京卫视
    - 东方卫视
    - 天津卫视
    - 重庆卫视
    - 延边
    - 德州
    - 青州
    - 河源
    - 晋江
    - 徐州
    - 张家港
    - 靖江
    - 栖霞
    - 武进
    - 余姚
    - 余杭
    - 兰考
    - 农安
    - 双滦
    - 吉林市
    - 松原
    - 四平
    - 尚志
    - 嵊州
    - 新昌
    - 柯桥
    - 江阴
    - 清苑
    - 白山
    - 萧山
    - 西安
    - 辽源
    - 通化
    - 鹿邑
    - 黄岛
    - 宿州
    - 邯郸
    - 镇平
    - 龙游
    - 定州
    - 晋城
    - 西宁
    - 乌海
    - 东莞
    - 上虞
    - 苏州
    - 宁波
    - 温州
    - 杭州
    - 南京
    - 成都
    - 广州
    - 深圳
    - 武汉
  港台频道:
    - 台湾
    - 香港
    - 澳门
    - TVB
    - TVBS
    - 三立
    - 澳视
    - 莲花
    - 华视
    - 中视
    - 公视
  国际频道:
    - CNN
    - BBC
    - NHK
    - RT
    - DW
    - Al Jazeera
    - France 24
    - EuroNews
    - CGTN
    - VOA
    - 越南
    - 乌克兰
    - 意大利
    - 卡塔尔
    - 亚洲新闻
    - Bloomberg
    - Discovery
    - National Geographic
    - Sky News
    - Fox News
  新闻频道:
    - 新闻
    - 资讯
    - News
  体育频道:
    - 体育
    - Sport
    - Sports
    - F1
    - NBA
    - CCTV5
  电影频道:
    - 电影
    - 影视
    - Movie
    - Cinema
    - Film
  综艺频道:
    - 综艺
    - 娱乐
    - Variety
    - Show
  纪录片频道:
    - 纪录
    - Documentary
    - Geo
    - History
  少儿频道:
    - 少儿
    - 卡通
    - 儿童
    - Kids
    - Manga
    - Ani
  教育频道:
    - 教育
    - 科教
    - Edu
    - Learning
  财经频道:
    - 财经
    - 经济
    - Business
    - Finance
    - stock
    - 证券
    - 股票
  音乐频道:
    - 音乐
    - Music
    - M2
    - V2
    - GOODTV
    - MTV
  生活频道:
    - 生活
    - 都市
    - 民生
    - 休闲
    - 社会
    - 综合
    - 娱乐
    - 综艺
    - 人间
    - 幸福
    - Variety
    - Lifestyle
  戏曲频道:
    - 戏曲
    - Opera
    - 京剧
    - 豫剧
    - 黄梅戏

category_aliases:
  新闻综合: 新闻频道
  经济生活: 财经频道
  钱江都市: 卫视频道
  民生休闲: 生活频道
  科教影视: 教育频道
  娱乐: 生活频道
  综艺: 综艺频道
  社会生活: 生活频道
  都市生活: 生活频道
  体育: 体育频道
  卡通: 少儿频道
  教育: 教育频道
  财经: 财经频道
  音乐: 音乐频道
  影视: 电影频道
  娱乐综艺: 综艺频道
  北京频道: 地方频道
  港台频道: 港台频道
  国际频道: 国际频道

# URL 预筛选配置
url_pre_screening:
  allowed_protocols:
    - "http"
    - "https"
    - "rtmp"
    - "rtsp"
    - "rtp"
    - "udp"
    - "p3p"
    - "hls"
    - "dash"
    - "webrtc"
  stream_extensions:
    - ".m3u8"
    - ".m3u"
    - ".ts"
    - ".flv"
    - ".mp4"
    - ".aac"
    - ".mp3"
    - ".f4m"
    - ".mpd"
    - ".ism"
    - ".m4s"
    - ".m4a"
  invalid_url_patterns:
    - "example\\.com"
    - "test\\.com"
    - "localhost"
    - "127\\.0\\.0\\.1"
    - "0\\.0\\.0\\.0"
    - "privateip"
    - "(^|[:/@])10\\."
    - "(^|[:/@])172\\.(1[6-9]|2[0-9]|3[01])\\."
    - "(^|[:/@])192\\.168\\."
    - "dummy"
    - "demo"
    - "null"
    - "invalid"
    - "error"
    - "blank"
    - "sample"
    - "temp"
    - "radio"
    - "fm"
    - "\\.(png|jpg|jpeg|gif|bmp|webp|svg|ico)$"
    - "\\.(css|js|html|htm|xml|txt|md|json|yml|yaml|csv|log|bak|ini|cfg|conf|map|woff|ttf|eot)$"
    - "\\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$"
    - "\\.(pdf|doc|docx|xls|xlsx|ppt|pptx|odt|ods|odp)$"
    - "\\.(exe|dll|msi|apk|dmg|pkg|iso|img|bin|deb|rpm)$"
    - "(\\s|%20)"
    - "github\\.com/(?!.*raw\\.githubusercontent\\.com)"
    - "gist\\.github\\.com/(?!.*raw\\.githubusercontent\\.com)"
    - "gitee\\.com/(?!.*raw)"
    - "youtube\\.com/(watch|embed|live)"
    - "youtu\\.be/"
    - "vimeo\\.com"
    - "dailymotion\\.com"
    - "youku\\.com"
    - "iqiyi\\.com"
    - "bilibili\\.com/(video|bangumi|live)"
    - "live\\.bilibili\\.com"
    - "douyu\\.com"
    - "huya\\.com"
    - "twitch\\.tv"
    - "facebook\\.com/(watch|live|videos)"
    - "twitter\\.com"
    - "instagram\\.com"
    - "tiktok\\.com"
    - "douyin\\.com"
    - "kuaishou\\.com"
    - "music\\.163\\.com"
    - "qq\\.com(?!.*live\\.qq\\.com)"
    - "mp\\.weixin\\.qq\\.com"
    - "api\\."
    - "/api/"
    - "google\\.com/search"
    - "baidu\\.com/s\\?"
    - "swagger"
    - "admin"
    - "login"
    - "register"
    - "signup"
    - "auth"
    - "token="
    - "key="
    - "password="
    - "payment"
    - "subscribe"
    - "vpn"
    - "proxy"
    - "shadowsocks"
    - "v2ray"
    - "trojan"
    - "clash"
    - "surge"
    - "speedtest"
    - "tracker"
    - "torrent"
    - "magnet:"
    - "teststream"
    - "nullstream"
    - "placeholder"
    - "example_stream"
    - "your_stream_url_here"
    - "stream_not_found"
    - "live_streams_not_working"
    - "fake_stream"
    - "dead_stream"
    - "empty\\.m3u8"
    - "error\\.m3u8"
    - "expired\\.m3u8"
    - "failed\\.m3u8"
    - "broken\\.m3u8"
    - "notfound\\.m3u8"
    - "invalid\\.m3u8"
    - "blocked\\.m3u8"
    - "private\\.m3u8"
    - "auth\\.m3u8"
    - "login\\.m3u8"
    - "signup\\.m3u8"
    - "forbidden\\.m3u8"
    - "denied\\.m3u8"
    - "vip\\.m3u8"
    - "paywall\\.m3u8"
    - "subscribe\\.m3u8"
    - "playlist\\.m3u8\\?streamid=0"
    - "/playlist\\.m3u8\\?(uid|userid|token|key)=[^&]+"
    - "/live/.*\\?(_sign|auth_key|playauth|st|wssecret|wstoken|txsecret|txtime|us|ct)=[^&]+"
    - "(ftp|sftp|ftps|telnet|ssh|smb|nfs|rdp|vnc|git|svn|irc|mailto|skype|spotify):"
    - "chinaunicom\\.com"
    - "chinatelecom\\.cn"
    - "chinamobile\\.com"
    - "vnet\\.com"
    - "taobao\\.com"
    - "tmall\\.com"
    - "jd\\.com"
    - "amazon\\.com"
    - "ebay\\.com"
    - "wikipedia\\.org"
    - "apple\\.com"
    - "microsoft\\.com"
    - "test\\.m3u8"
    - "demo\\.m3u8"
