ffmpeg:
  default:
    timeout: 3000000  # 3 秒
    probesize: 500000  # 500KB
    analyzeduration: 500000  # 0.5 秒
    loglevel: error
  http:
    timeout: 3000000
    headers: "User-Agent: Mozilla/5.0"
    reconnect: 1
    reconnect_delay_max: 5
  rtmp:
    timeout: 5000000
    rtmp_transport: tcp
    rtmp_buffer: 1000
  rtp:
    timeout: 2000000
    buffer_size: 200000
    rtcpport: 5005
  video_quality:
    resolution: "1280x720"
    bitrate: "2000k"
    crf: 23
    preset: medium
  ad_filter:
    scene_threshold: 0.3
    skip_segments:
      - start: 0
        end: 30
  loop_handling:
    stream_loop: -1
    discard_corrupt: true
