
logging:
  log_level: INFO
  log_file: logs/iptv.log

performance_monitor:
  enabled: true
  log_interval: 10

stream_quality:
  stream_check_workers: 10
  max_check_duration: 120
  min_resolution_width: 640
  min_resolution_height: 480
  min_bitrate: 100000
  max_buffer_time: 60
  max_keyframe_interval: 20
  ad_keywords:
    - advertisement
    - ad
    - commercial
    - promo

url_pre_screening:
  invalid_url_patterns:
    - '\.jpg$'
    - '\.png$'
    - '\.gif$'
    - '\.pdf$'
    - '\.exe$'
    - 'login'
    - 'signup'
    - 'private'
    - 'localhost'
    - '^http://171\.8\.247\.154:808'
    - '^https://vv\.jisuzyv\.com'
    - '^https://t\.me/'
    - '\.php$'
    - '\.mp4$'
    - '^http://video\.dztv\.tv'
    - '^http://live\.ahsz\.tv'

output:
  paths:
    high_quality_iptv_file: output/high_quality_iptv.txt
