name: Test Nodes with Mihomo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Download Mihomo Core
      run: |
        wget https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64 -O mihomo
        chmod +x mihomo

    - name: Start Mihomo Core
      run: |
        ./mihomo -f config.yaml &
        sleep 5  # 等待 Mihomo Core 启动

    - name: Run node testing script
      run: |
        python test_nodes.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: successful-nodes
        path: data/all.txt
