name: Test and Parse Nodes

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Clash.Meta
      run: |
        wget https://github.com/MetaCubeX/Clash.Meta/releases/latest/download/clash-linux-amd64.tar.gz
        tar -xzf clash-linux-amd64.tar.gz
        sudo mv clash /usr/local/bin/
        chmod +x /usr/local/bin/clash

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Run node parser and tester
      run: python parse_and_test_nodes.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: node-results
        path: data/all.txt
