name: Test and Save Proxy Nodes

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify Python 3.9 for consistency

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip curl

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests aiofiles certifi

    - name: Test network connectivity
      run: |
        echo "Testing network connectivity..."
        curl -v http://1.1.1.1
        ping -c 4 1.1.1.1
      continue-on-error: true # Continue even if network test fails

    - name: Run node processing script
      run: python tester.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add data/all.txt
        git commit -m "Update working proxy nodes" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
