
name: Test and Parse Nodes

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Install Clash.Meta
      run: |
        wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz
        gunzip mihomo-linux-amd64-v1.18.9.gz
        sudo mv mihomo-linux-amd64-v1.18.9 /usr/local/bin/clash
        chmod +x /usr/local/bin/clash
        clash --version

    - name: Install Python dependencies
      run: |
        pip install requests pyyaml

    - name: Run node parser and tester
      run: |
        python parse_and_test_nodes.py || echo "Script failed, check logs for details"

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: node-results
        path: data/all.txt
        if-no-files-found: warn
