name: all_clash
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'subscribe/all_clash.py'
  schedule:
    - cron: '0 */23 * * *'
jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create data directory
      run: |
        mkdir -p data
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install requests tqdm PyYAML
        pip list
    - name: Run collection script
      env:
        URL_SOURCE: ${{ secrets.URL_SOURCE }}
      run: |
        echo "=== 列出 Python 脚本 ==="
        ls -lh subscribe/*.py || echo "No Python scripts found"
        python subscribe/all_clash.py --output data/all_clash.yaml --timeout ${{ vars.REQUEST_TIMEOUT || 60 }} --max_success ${{ vars.MAX_SUCCESS_NODES || 99999 }}
        echo "Script exit code: $?"
        echo "=== 检查生成文件 ==="
        ls -lh data/ || echo "No files found in data/"
        echo "=== URL 统计 CSV 文件 ==="
        cat data/url_statistics.csv || echo "url_statistics.csv not found"
        echo "=== 成功 URL 数量 ==="
        wc -l data/successful_urls.txt || echo "successful_urls.txt not found"
        echo "=== 失败 URL 数量 ==="
        wc -l data/failed_urls.txt || echo "failed_urls.txt not found"
        echo "=== 输出文件内容预览（前10行） ==="
        head -n 10 data/all_clash.yaml || echo "data/all_clash.yaml not found"
    - name: 提交更改
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        for file in data/all_clash.yaml.gz data/url_statistics.csv data/successful_urls.txt data/failed_urls.txt; do
          if [ -f "$file" ]; then
            echo "Adding $file"
            git add "$file"
          else
            echo "File $file not found"
          fi
        done
        git diff --staged --quiet || git commit -m "Update proxy nodes: $(date '+%Y-%m-%d %H:%M:%S %Z')"
        git diff --staged --quiet && echo "No changes to commit"
    - name: 拉取远程并变基
      run: |
        git status
        git diff --name-only
        git fetch origin
        git checkout -- .
        git pull --rebase origin main || {
          echo "Rebase failed, attempting to resolve conflicts";
          git rebase --abort;
          git pull --merge origin main;
        }
    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
