name: all_clash

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'subscribe/all_clash.py' # 确保脚本路径正确
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保有写入权限来提交文件

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true

    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        # 只安装脚本实际需要的依赖：requests, tqdm, PyYAML
        pip install requests tqdm PyYAML
        pip list  # 调试：列出安装的依赖版本

    - name: Run collection script
      env:
        URL_SOURCE: ${{ secrets.URL_SOURCE }}
      run: |
        # 运行主脚本，使用其自身的命令行参数
        # --output 指定输出文件路径，这里使用 data/all_clash.yaml
        # --timeout 使用 workflow vars 或默认值 60
        # --max_success 使用 workflow vars 或默认值 99999
        python subscribe/all_clash.py --output data/all_clash.yaml --timeout ${{ vars.REQUEST_TIMEOUT || 60 }} --max_success ${{ vars.MAX_SUCCESS_NODES || 99999 }}
        
        echo "=== 生成文件列表 ==="
        ls -lh data/ || echo "data/ directory not found"
        echo "=== 错误日志 ==="
        cat error.log || echo "error.log not found"
        echo "=== URL 统计 CSV 文件 ==="
        cat data/url_statistics.csv || echo "url_statistics.csv not found" # 新增
        echo "=== 成功 URL 数量 ==="
        wc -l data/successful_urls.txt || echo "successful_urls.txt not found" # 更新
        echo "=== 失败 URL 数量 ==="
        wc -l data/failed_urls.txt || echo "failed_urls.txt not found" # 更新
        echo "=== 输出文件内容预览（前10行） ==="
        head -n 10 data/all_clash.yaml || echo "data/all_clash.yaml not found" # 更新文件名

    - name: 提交更改
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        # 添加所有新生成的文件以及原有的 all_clash.yaml 和 error.log
        git add data/all_clash.yaml data/url_statistics.csv data/successful_urls.txt data/failed_urls.txt error.log
        
        # 检查是否有实际更改，有更改才提交
        git diff --staged --quiet || git commit -m "Update proxy nodes: $(date '+%Y-%m-%d %H:%M:%S %Z')"
        # 如果没有更改，打印提示
        git diff --staged --quiet && echo "No changes to commit"

    - name: 拉取远程并变基
      run: |
        git fetch origin
        git pull --rebase origin main || {
          echo "Rebase failed, attempting to resolve conflicts";
          git rebase --abort;
          git pull --merge origin main;
        }

    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
