name: all_clash

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'subscribe/all_clash.py'
  schedule:
    - cron: '0 */3 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true

    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests python-dotenv tqdm

    - name: Run collection script
      env:
        URL_SOURCE: ${{ secrets.URL_SOURCE }}
      run: |
        python subscribe/all_clash.py
        ls -lh data/  # 调试：查看生成的文件
        cat error.log  # 调试：查看错误日志
        echo "成功 URL 数量:"
        wc -l data/successful_urls.txt || echo "successful_urls.txt not found"
        echo "失败 URL 数量:"
        wc -l data/failed_urls.txt || echo "failed_urls.txt not found"

    - name: 提交更改
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/all_clash_*.txt  # 添加所有分割后的输出文件
        git add data/successful_urls.txt data/failed_urls.txt error.log  # 添加成功/失败URL记录和日志
        git add .
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"

    - name: 拉取远程并变基
      run: |
        git pull --rebase origin main

    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main
