name: Test Node Latency and Generate Clash Config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-latency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Download mihomo binary
        run: |
          chmod +x ./mihomo/mihomo-linux-amd64-compatible-v1.19.13
          
      - name: Run latency test script
        run: python test_node_latency.py

      - name: Upload clash_config.yaml
        uses: actions/upload-artifact@v4
        with:
          name: clash-config
          path: clash_config.yaml
