name: Classify TV Channels

on:
  push:
    paths:
      - 'iptv_list.txt'  # 当 iptv_list.txt 更新时触发

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install zhconv

      - name: Run classification script
        run: python classify_tv.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tv_list.txt
          git commit -m "自动分类 TV 频道" || echo "没有更改需要提交"
          git push
