name: ClashForge

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - '.github/workflows/ClashForge.yml'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai # 时区环境变量

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements2.txt

      - name: Run ClashForge.py
        run: |
          echo "INPUT=${{ vars.INPUT }}" >> $GITHUB_ENV
          python ClashForge.py

      - name: Commit and push file
        run: |
          # actions/checkout v2+ 会自动设置 git config，所以这些命令是多余的
          
          git add clash_config.yaml
          
          if ! git diff --staged --quiet; then
            git commit -m "update"
            
            for i in {1..3}; do
              echo "Attempt $i to pull, rebase, and push..."
              git pull --rebase origin main
              
              if [ $? -eq 0 ]; then
                git push origin main
                if [ $? -eq 0 ]; then
                  echo "Push successful on attempt $i."
                  exit 0
                fi
              fi
              
              sleep 5
            done
            
            echo "Failed to push after multiple attempts. Manual intervention may be required."
            exit 1
          else
            echo "No changes to commit. Exiting."
          fi
