name: ClashForge

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    paths:
      - '.github/workflows/ClashForge.yml'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai # 添加时区环境变量

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # ⚠️ 注意：这里使用 token: ${{ secrets.BOT }}，请确保你的 BOT secret
          # 具有写入权限，否则推送会失败。
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements2.txt

      - name: Run ClashForge.py
        run: python ClashForge.py

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 添加更改的文件
          git add clash_config.yaml
          
          # 检查是否有文件更改，如果没有则跳过提交和推送
          if ! git diff --staged --quiet; then
            git commit -m "update"
            
            # 循环尝试拉取、rebase 和推送，最多重试 3 次
            for i in {1..3}; do
              echo "Attempt $i to pull, rebase, and push..."
              # 使用 origin main 指定分支，避免歧义
              git pull --rebase origin main
              
              if [ $? -eq 0 ]; then
                git push origin main
                if [ $? -eq 0 ]; then
                  echo "Push successful on attempt $i."
                  exit 0 # 成功后退出
                fi
              fi
              
              sleep 5 # 失败后等待5秒再重试
            done
            
            echo "Failed to push after multiple attempts. Manual intervention may be required."
            exit 1 # 循环结束仍失败，则退出
          else
            echo "No changes to commit. Exiting."
          fi
