name: Generate main.yaml with Valid Proxies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-main-yaml:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: pip install pyyaml requests

      # Run script to generate main.yaml
      - name: Generate main.yaml
        run: python generate_proxies.py

      # Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add main.yaml
          git commit -m 'Generate main.yaml with valid proxies'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
