
name: Generate main.yaml

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run generate_proxies.py
      run: |
        python generate_proxies.py
        echo "=== main.yaml content ==="
        cat main.yaml
        echo "=== skipped_nodes.log content ==="
        cat skipped_nodes.log

    - name: Check for changes
      id: check_changes
      run: |
        git add main.yaml skipped_nodes.log
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git commit -m "Update main.yaml and skipped_nodes.log"
        git push

    - name: Report failure if no changes
      if: steps.check_changes.outputs.changes == 'false'
      run: |
        echo "No changes to commit, but continuing workflow"
