name: Merge Files to main.yaml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install PyYAML
        run: pip install pyyaml requests

      # Run merge script
      - name: Merge files to main.yaml
        run: python merge_files.py

      # Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add main.yaml
          git commit -m 'Merge files into main.yaml'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
