name: Deduplicate Nodes

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行 (北京时间早上8点)

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 与你的环境一致

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Run deduplication script
        run: python deduplicate_nodes.py --debug  # 启用调试模式，便于分析去重问题
        continue-on-error: false # 脚本失败时停止工作流

      - name: Check output file
        run: |
          if [ ! -f data/all.txt ]; then
            echo "错误：未找到去重后的输出文件 data/all.txt"
            exit 1
          fi

      - name: Upload log file as artifact
        if: always() # 即使脚本失败也上传日志
        uses: actions/upload-artifact@v4
        with:
          name: deduplication-log
          path: node_deduplication.log
          retention-days: 7

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/all.txt
          if git diff --cached --exit-code; then
            echo "无变更需要提交"
          else
            git commit -m "自动更新: 去重节点 [skip ci]"
            git push || echo "推送失败，可能是无变更或权限问题"
          fi
