name: Deduplicate Nodes

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (8 AM Beijing time)

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Ensure this matches your environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Run deduplication script
        # The script now defaults to 100 concurrent workers and a 1-second Ping timeout.
        # You can override these defaults using --max-ping-workers and --ping-timeout.
        run: python deduplicate_nodes.py # Removed --debug to reduce log volume
        continue-on-error: false # Stop workflow if the script fails

      - name: Check output files
        run: |
          if [ ! -f data/all.txt ]; then
            echo "Error: Deduplicated output file data/all.txt not found."
            exit 1
          fi
          if [ -z "$(ls data/*.txt 2>/dev/null)" ]; then
            echo "Warning: No protocol-specific output files found."
          fi
          if [ ! -f data/ping_successful_nodes.txt ]; then
            echo "Warning: Ping successful nodes file data/ping_successful_nodes.txt not found."
          fi
          if [ ! -f data/ping_failed_nodes.txt ]; then
            echo "Warning: Ping failed nodes file data/ping_failed_nodes.txt not found."
          fi

      - name: Upload log file as artifact
        if: always() # Upload log even if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: deduplication-log
          path: node_deduplication.log
          retention-days: 7

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Add all .txt files in the data/ directory, including new Ping result files
          git add data/*.txt
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            # Update commit message to reflect Ping functionality
            git commit -m "Auto-update: Deduplicated nodes, output by protocol, and performed node Ping test [skip ci]"
            git push || echo "Push failed, possibly no changes or permission issues."
          fi
