name: Deduplicate Nodes

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行 (北京时间早上8点)

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 与你的环境一致

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Run deduplication script
        run: python deduplicate_nodes.py
        continue-on-error: false # 脚本失败时停止工作流

      - name: Check output files
        run: |
          if [ -z "$(ls data/part_*.txt 2>/dev/null)" ]; then
            echo "错误：未找到去重后的分片文件"
            exit 1
          fi
          echo "OUTPUT_FILES=$(ls data/part_*.txt)" >> $GITHUB_ENV

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/part_*.txt
          git diff --cached --exit-code || git commit -m "自动更新: 去重节点分片 [skip ci]"
          git push || echo "无变更需要推送或推送失败"
