name: Download and Validate M3U8 URLs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 280

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Cache data directory
      uses: actions/cache@v4
      with:
        path: data/
        key: ${{ runner.os }}-data-${{ github.run_id }}  # 回退到使用 run_id
        restore-keys: |
          ${{ runner.os }}-data-

    - name: Run script
      env:
        BOT: ${{ secrets.BOT }}
        REPO_URL: ${{ secrets.REPO_URL }}
      run: |
        python download_m3u8.py 2>&1 | tee script_output.log
      continue-on-error: false

    - name: Upload script logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: script-logs
        path: script_output.log
        if-no-files-found: warn

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: m3u8-results
        path: data/
        if-no-files-found: warn

    - name: Commit and push results
      if: always()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update M3U8 results [ci skip]"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const runId = context.runId;
          // 创建新的 issue 用于通知
          await github.rest.issues.create({
            owner,
            repo,
            title: `Workflow Failure: Run ${runId}`,
            body: `Workflow failed for run ${runId}. Check logs: https://github.com/${owner}/${repo}/actions/runs/${runId}`
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
