name: Download and Validate M3U8 URLs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 530  # 设置 530 分钟超时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 拉取完整历史以支持 rebase

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Clear data directory before script
      run: |
        rm -rf data/
        mkdir -p data/
      continue-on-error: true

    - name: Cache data directory
      uses: actions/cache@v4
      with:
        path: data/
        key: ${{ runner.os }}-data-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-data-

    - name: Run script
      env:
        BOT: ${{ secrets.BOT }}
        REPO_URL: ${{ secrets.REPO_URL }}
      run: python download_m3u8.py

    - name: Debug git status
      run: |
        git status
        git diff
        ls -la data/
      continue-on-error: true

    - name: Clean untracked files
      run: |
        git clean -fd data/
        git reset --hard
      continue-on-error: true

    - name: Commit and push results
      if: always()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/
        git commit -m "Update M3U8 results [ci skip]" || echo "No changes to commit"
        git fetch origin
        git rebase origin/main || {
          echo "Rebase failed, resetting and forcing push"
          git rebase --abort
          git reset --hard origin/main
          git add data/
          git commit -m "Update M3U8 results [ci skip]" || echo "No changes to commit"
          git push origin main --force
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: m3u8-results
        path: data/
        if-no-files-found: warn
