name: Proxy Fetch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # 替换为您的实际默认分支，例如 'main' 或 'master'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m 'Update proxy lists' || echo "No changes to commit"
          git push origin main  # 替换为您的实际默认分支，例如 'main' 或 'master'
