name: ClashForge

on:
  schedule:
    - cron: 0 */3 * * *
  push:
    paths-ignore:
      - '**'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai 
jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements2.txt

      - name: Run ClashForge.py
        run: python ClashForge.py

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add clash_config.yaml
          git commit -m "update" || echo "No changes to commit"
          
          # 在推送前，先拉取远程最新更改
          # --rebase 选项可以避免创建多余的合并提交
          git pull --rebase
          
          # 推送更改
          git push https://${{ secrets.BOT }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git
