name: 测试

on:
  push:
    branches:
      - '.github/workflows/ffmpeg.yml'
  workflow_dispatch:
  schedule:
    # Runs every 6 hours
    # cron expression format: (minute hour day-of-month month day-of-week)
    - cron: '0 */6 * * *'

jobs:
  check-and-categorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests tenacity cachetools tqdm psutil
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run channel check and categorization script
        run: |
          python check_and_categorize_channels.py

      - name: Commit and push changes
        run: |
          # Configure Git user
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add all changes
          git add .
          
          # Check if there are changes to commit. If not, exit gracefully.
          if git diff --staged --quiet; then
            echo "No changes to commit. Exiting."
            exit 0
          fi
          
          # Commit local changes
          git commit -m "Update categorized IPTV lists"
          
          # Rebase local commits on top of the remote branch
          git pull --rebase origin main
          
          # Push the final changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
