name: 测试 IPTV 频道检查和分类

on:
  push:
    paths:
      - '.github/workflows/ffmpeg.yml'
      - 'check_and_categorize_channels.py'
      - 'config/**'
      - 'output/iptv.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  check-and-categorize:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Check input file
        run: |
          if [ ! -f output/iptv.txt ]; then
            echo "错误：未找到 output/iptv.txt"
            exit 1
          fi
          if [ ! -s output/iptv.txt ]; then
            echo "错误：output/iptv.txt 为空"
            exit 1
          fi

      - name: Create log directory
        run: |
          mkdir -p logs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo -e "PyYAML==6.0\nrequests==2.31.0\ntenacity==8.2.3\ncachetools==5.3.1\ntqdm==4.66.4\npsutil==5.9.5" > requirements.txt
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run channel check and categorization script
        run: |
          python check_and_categorize_channels.py
        continue-on-error: false

      - name: Store logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iptv-checker-logs
          path: logs/iptv_checker.log
          retention-days: 7
          if-no-files-found: warn

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update categorized IPTV lists and demo.txt"
            git push origin main --no-verify
          else
            echo "没有需要提交的更改，退出。"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "IPTV check failed. Check logs at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          exit 1
