name: 测试

on:
  push:
    branches:
      - '.github/workflows/ffmpeg.yml'
  workflow_dispatch:
  schedule:
    # 每 6 小时运行一次
    # cron 表达式的语法: (分 时 日 月 周)
    - cron: '0 */6 * * *'

jobs:
  check-and-categorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests tenacity cachetools tqdm psutil
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run channel check and categorization script
        run: |
          python check_and_categorize_channels.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update categorized IPTV lists" --allow-empty || echo "No changes to commit"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
