name: FFprobe Stream Checker

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  check_streams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Set up FFmpeg and FFprobe
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: 'release' # 安装最新稳定版

    - name: Install dependencies (if any, not strictly needed for this script)
      run: |
        python -m pip install --upgrade pip
        pip install tqdm aiohttp aiohttp-socks
        
    - name: Run FFprobe Checker
      run: python ffprobe_checker.py

    - name: Commit changes to ff.txt and failed_links.txt
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated: Update ff.txt and failed_links.txt after stream check"
        files: |
          ff.txt
          failed_links.txt
        # 添加此行以避免每次运行都创建新的提交，如果文件没有变化
        skip_dirty_check: true
