name: Find and Save Proxies via Google

on:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间中午 12 点运行
  workflow_dispatch:

jobs:
  run-google-search:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googlesearch-python beautifulsoup4 PyYAML requests
      
      - name: Run Google script
        run: |
          python google.py
          
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add google.yaml
          git commit -m "Auto update proxies from Google search" || echo "No changes to commit"
          git push
