name: 测速

on:
  push:
    paths:
      - '.github/workflows/xiecang-speed-test.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run-speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: 安装 clash-speedtest 工具
        run: go install github.com/faceair/clash-speedtest@latest

      - name: 备份上次运行结果
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          cp clash.yaml sc/clash_$TIMESTAMP.yaml
          echo "已成功备份 clash.yaml 到 sc/clash_$TIMESTAMP.yaml"

      - name: 根据IP地址筛选节点
        run: |
          pip install pyyaml requests
          cat > filter_proxies.py << 'EOF'
import yaml
import requests

def get_country_code(ip):
    try:
        response = requests.get(f'http://ip-api.com/json/{ip}', timeout=2)
        response.raise_for_status()
        data = response.json()
        if data['status'] == 'success':
            return data['countryCode']
    except Exception:
        return None
    return None

def main():
    include_codes = {'JP', 'KR', 'HK', 'TW', 'SG', 'MY', 'PH', 'VN', 'TH', 'LA', 'MM', 'RU', 'MN'}
    
    response = requests.get('https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/clash_config.yaml')
    response.raise_for_status()
    config = yaml.safe_load(response.text)
    
    if 'proxies' not in config:
        print('没有找到 proxies 列表。')
        return

    filtered_proxies = []
    for proxy in config['proxies']:
        ip_address = proxy.get('server')
        if ip_address:
            country_code = get_country_code(ip_address)
            if country_code and country_code in include_codes:
                filtered_proxies.append(proxy)
    
    config['proxies'] = filtered_proxies
    
    with open('filtered_by_ip.yaml', 'w') as f:
        yaml.dump(config, f, allow_unicode=True)
    
if __name__ == '__main__':
    main()
EOF
          python3 filter_proxies.py

      - name: 运行测速并筛选节点
        run: |
          clash-speedtest -c filtered_by_ip.yaml \
                            -output clash.yaml \
                            -max-latency 386ms \
                            -min-download-speed 28.8 \
                            -rename

      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add clash.yaml sc/
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update and filter Clash nodes via speedtest"
            for i in {1..3}; do
              git pull --rebase
              git push && break
              sleep 5
            done
          else
            echo "没有节点更改，无需提交。"
          fi
