name: IPTV Source Processor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  process_sources:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 安装 Python 依赖
        run: |
          pip install requests

      - name: 确保 output 目录存在并包含脚本
        run: |
          mkdir -p output 

      - name: 运行 IPTV 节目源处理脚本
        env:
          # === 修改开始：现在从 secrets 中获取完整的 URL ===
          PRIVATE_REMOTE_URLS_TXT_BASE_URL: ${{ secrets.PRIVATE_REMOTE_URLS_TXT_URL }}
          # === 修改结束 ===
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 保持不变，这是内置的 Secret
        run: python output/iptv_processor.py

      - name: 保存生成的文件
        uses: actions/upload-artifact@v4
        with:
          name: iptv-processing-results
          path: |
            output/urls.txt
            output/url_processing_state.json
            output/final_iptv_sources.txt
            output/iptv_processor.py
          retention-days: 7
          if-no-files-found: warn

      - name: 检查文件更改
        id: check_changes
        run: |
          git add output/urls.txt output/url_processing_state.json output/final_iptv_sources.txt output/iptv_processor.py
          if git diff --staged --quiet; then
            echo "没有文件更改"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件更改"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "更新 IPTV 源列表和处理状态 ($(date +'%Y-%m-%d %H:%M'))"

      - name: 推送更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git pull origin main --rebase
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - name: 发送运行结果通知
        if: always()
        run: |
          echo "IPTV 节目源处理工作流完成，状态: ${{ job.status }}"
