name: IPTV Channel Update

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'tv.py'
      - 'config/**'
      - '频道模板/**'

jobs:
  update-channels:
    runs-on: ubuntu-latest

    env:
      BOT: ${{ secrets.BOT_TOKEN }}
      REPO_OWNER: ${{ vars.REPO_OWNER }}
      REPO_NAME: ${{ vars.REPO_NAME }}
      CONFIG_PATH: ${{ vars.CONFIG_PATH }}
      URLS_PATH: ${{ vars.URLS_PATH }}
      URL_STATES_PATH: ${{ vars.URL_STATES_PATH }}
      KEYWORD_STATS_PATH: ${{ vars.KEYWORD_STATS_PATH }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install requests pyyaml retrying python-telegram-bot python-gitlab httpx aiohttp pypraw

      - name: Create necessary directories
        run: |
          mkdir -p config
          mkdir -p output
          mkdir -p 频道模板

      - name: Run IPTV script
        run: python tv.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/iptv_results.txt output/iptv_results.m3u config/*.json config/*.txt
          git add iptv_results.txt iptv_results.m3u
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update IPTV results and config"
            git push
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iptv-results
          path: |
            output/iptv_results.txt
            output/iptv_results.m3u
            iptv_results.txt
            iptv_results.m3u
            config/*.json
            config/*.txt
            iptv_crawler.log
          retention-days: 7
          if-no-files-found: warn
