
name: IPTV Channel Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      url_batches: ${{ steps.split_urls.outputs.url_batches }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT }}

      - name: Split URLs into Batches
        id: split_urls
        run: |
          mkdir -p config
          if [ -f "config/urls.txt" ]; then
            split -l 50 config/urls.txt config/urls_batch_ -d -a 3
            batches=$(ls config/urls_batch_* | jq -R -s -c 'split("\n")[:-1]')
            echo "url_batches=$batches" >> $GITHUB_OUTPUT
          else
            echo "Error: urls.txt not found"
            exit 1
          fi
        shell: bash

  process_batch:
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
    strategy:
      matrix:
        batch_file: ${{ fromJson(needs.prepare.outputs.url_batches) }}
    steps:
      - name: Check BOT Secret
        run: |
          if [ -z "${{ secrets.BOT }}" ]; then
            echo "Error: BOT secret is not set."
            exit 1
          fi
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT }}

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          pip install requests aiohttp beautifulsoup4 tenacity psutil pyyaml dnspython aiofiles tqdm

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Create Output Directories
        run: |
          mkdir -p temp_channels output config
        shell: bash

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Verify ffprobe
        run: |
          if command -v ffprobe >/dev/null 2>&1; then
            echo "ffprobe found and available! Version info:"
            ffprobe -version
          else
            echo "Error: ffprobe not found or not executable!"
            exit 1
          fi

      - name: Run IPTV Script for Batch
        env:
          BOT: ${{ secrets.BOT }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          CONFIG_PATH: config/config.yaml
          URLS_PATH: ${{ matrix.batch_file }}
          URL_STATES_PATH: config/url_states.yaml
          INVALID_URLS_PATH: config/invalid_urls.txt
        run: python ${{ github.workspace }}/tv3.py

      - name: Check uncategorized_channels.txt
        run: |
          if [ -f "uncategorized_channels.txt" ]; then
            echo "uncategorized_channels.txt generated successfully"
            cat uncategorized_channels.txt
          else
            echo "Error: uncategorized_channels.txt not generated"
            exit 1
          fi
        shell: bash

      - name: Check File Changes
        id: check_changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No file changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "File changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --allow-empty -m "Update IPTV channel list for batch ${{ matrix.batch_file }} ($(date +'%Y-%m-%d %H:%M'))"

      - name: Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git fetch origin
          git rebase origin/main || (git rebase --abort && git pull origin main --no-rebase)
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

  finalize:
    needs: process_batch
    runs-on: ubuntu-latest
    steps:
      - name: Send Run Result Notification
        run: |
          echo "IPTV channel update workflow completed, status: ${{ job.status }}"
          echo "Check iptv_script.log in the repository for details"
