name: IPTV 更新频道

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # 每 8 小时

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: Check BOT secret
        run: |
          if [ -z "${{ secrets.BOT }}" ]; then
            echo "错误：未设置 BOT secret"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.BOT }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install requests pyyaml tenacity

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Debug environment variables
        run: env | grep -E 'BOT|REPO|CONFIG|PATH'

      - name: Run IPTV script
        env:
          BOT: ${{ secrets.BOT }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          CONFIG_PATH: ${{ vars.CONFIG_PATH }}
          URLS_PATH: ${{ vars.URLS_PATH }}
          URL_STATES_PATH: ${{ vars.URL_STATES_PATH }}
          KEYWORD_STATS_PATH: ${{ vars.KEYWORD_STATS_PATH }}
        run: python tv.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iptv-results
          path: |
            output/iptv_results.txt
            output/iptv_results.m3u
            config/*.json
            config/*.txt
            iptv_crawler.log
          retention-days: 7
          if-no-files-found: warn

      - name: Check for changes
        id: check_changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Updated IPTV results and M3U playlist ($(date +'%Y-%m-%d %H:%M'))"

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
        run: |
          git push https://x-access-token:${{ secrets.BOT }}@github.com/${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}.git main
