name: Check IPTV Streams

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 午夜运行

jobs:
  check-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main-repo
          
      - name: Checkout m3u-validator repository
        uses: actions/checkout@v4
        with:
          repository: fanzila/m3u-validator
          path: m3u-validator
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install m3u-validator Python dependencies
        run: |
          cd m3u-validator
          pip install -r requirements.txt
          
      - name: Convert custom IPTV list to M3U8 format
        run: |
          # 您的转换脚本
          cat << 'EOF' > convert.py
          import csv
          import requests
          import os
          from io import StringIO
          import sys

          input_url = sys.argv[1]
          output_file = sys.argv[2]

          os.makedirs(os.path.dirname(output_file), exist_ok=True)

          print(f"Downloading from: {input_url}")
          response = requests.get(input_url)
          response.raise_for_status()
          content = response.text
          print("Download successful. Starting conversion.")

          with StringIO(content) as infile, open(output_file, "w", encoding="utf-8") as outfile:
              outfile.write("#EXTM3U\n")
              reader = csv.reader(infile)
              for row in reader:
                  if len(row) < 2 or row[0].startswith("更新时间") or row[0] == "#genre#":
                      continue
                  channel_name, url = row[0], row[1]
                  outfile.write(f"#EXTINF:-1,{channel_name}\n{url}\n")
          print(f"M3U8 file generated: {output_file}")
          EOF

          # 运行转换脚本
          python3 convert.py \
            "https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/output/iptv_list.txt" \
            "m3u-validator/iptv_list.m3u8"
        
      - name: Run m3u-validator script
        id: check_script
        run: |
          # 运行 m3u-validator 脚本，并将结果输出到文件
          cd m3u-validator
          # `-o` 参数指定输出文件名，`--format` 指定输出格式
          python3 m3u-validator.py -o ../main-repo/output/list.txt --format m3u --timeout 5 --processes 10 iptv_list.m3u8
        
      - name: List generated files
        run: |
          echo "=== Files in main-repo/output directory ==="
          ls -lR main-repo/output/
          echo "=== End of File List ==="

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          cd main-repo
          
          if [ -f "output/list.txt" ]; then
            git add output/list.txt
            git commit -m "Update IPTV stream check results" || true
            git push
          else
            echo "output/list.txt not found, skipping commit."
          fi
