name: Run Node Fetcher

on:
  push:
    paths:
      - 'link.py'
      - 'ip_geolocation.py'
      - 'link.txt'
      - '.github/workflows/link.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml geoip2 tqdm beautifulsoup4

      - name: Run the script
        run: python link.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add link.yaml link.csv
          git commit -m "Auto update nodes from script"
          git push
