name: Run Node Fetcher

on:
  push:
    paths:
      - 'link.py'
      - 'ip_geolocation.py'
      - 'link.txt'
      - '.github/workflows/link.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每日0点运行主任务
    - cron: '0 0 5 * *'  # 每月5号0点更新 GeoLite2-Country.mmdb

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml geoip2 tqdm beautifulsoup4

      - name: Update GeoLite2-Country database on 5th of each month
        if: github.event.schedule == '0 0 5 * *'  # 仅在每月5号运行
        run: |
          echo "Updating GeoLite2-Country.mmdb..."
          wget -O GeoLite2-Country.mmdb https://git.io/GeoLite2-Country.mmdb
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add GeoLite2-Country.mmdb
          git commit -m "Update GeoLite2-Country.mmdb on $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # 允许下载失败继续运行

      - name: Verify GeoLite2-Country database
        if: github.event.schedule != '0 0 5 * *'  # 非每月5号时检查文件
        run: |
          if [ ! -f GeoLite2-Country.mmdb ]; then
            echo "Error: GeoLite2-Country.mmdb not found in repository."
            exit 1
          else
            echo "GeoLite2-Country.mmdb found, proceeding."
          fi
        continue-on-error: false  # 文件缺失时终止

      - name: Run the script
        if: github.event.schedule != '0 0 5 * *'  # 非每月5号时运行脚本
        run: python link.py
        continue-on-error: true  # 允许脚本运行出错继续执行

      - name: Commit and push changes
        if: github.event.schedule != '0 0 5 * *'  # 非每月5号时提交结果
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add link.yaml link.csv cache.json
          git commit -m "Auto update nodes and cache from script on $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
