name: Clash Speedtest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clash
        run: |
          # 下载 Clash（请替换为适合的版本和架构，示例为 Clash Meta Linux AMD64）
          wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz
          gunzip mihomo-linux-amd64-v1.18.9.gz
          chmod +x mihomo-linux-amd64-v1.18.9
          mv mihomo-linux-amd64-v1.18.9 /usr/local/bin/clash

      - name: Download clash-speedtest
        run: |
          wget https://github.com/starudream/clash-speedtest/releases/download/v3.0.1/clash-speedtest_v3.0.1_linux_amd64.tar.gz
          tar -zxvf clash-speedtest_v3.0.1_linux_amd64.tar.gz
          chmod +x clash-speedtest

      - name: Check link.yaml
        run: |
          if [ ! -f "link.yaml" ]; then
            echo "Error: link.yaml not found"
            exit 1
          fi

      - name: Run Clash
        run: |
          clash -f link.yaml &
          CLASH_PID=$!
          sleep 5  # 等待 Clash 启动
          echo "CLASH_PID=$CLASH_PID" >> $GITHUB_ENV

      - name: Run clash-speedtest
        run: |
          ./clash-speedtest \
            --clash-addr http://127.0.0.1:9090 \
            --clash-proxy http://127.0.0.1:7890 \
            -d cloudflare \
            -r 20 \
            -t 3 \
            -y \
            -o ./clash.yaml

      - name: Check clash.yaml
        run: |
          if [ -f "clash.yaml" ]; then
            echo "Test completed, results saved to clash.yaml"
          else
            echo "Error: Failed to generate clash.yaml"
            exit 1
          fi

      - name: Cleanup Clash
        if: always()
        run: |
          if [ -n "${CLASH_PID}" ]; then
            kill ${CLASH_PID}
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: clash-yaml
          path: clash.yaml
