name: Clash Speedtest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clash
        run: |
          # 下载 Clash Meta（替换为适合的版本和架构）
          wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz
          gunzip mihomo-linux-amd64-v1.18.9.gz
          chmod +x mihomo-linux-amd64-v1.18.9
          mv mihomo-linux-amd64-v1.18.9 /usr/local/bin/clash

      - name: Download clash-speedtest
        run: |
          wget https://github.com/starudream/clash-speedtest/releases/download/v3.0.1/clash-speedtest_v3.0.1_linux_amd64.tar.gz
          tar -zxvf clash-speedtest_v3.0.1_linux_amd64.tar.gz
          chmod +x clash-speedtest

      - name: Check link.yaml
        run: |
          if [ ! -f "link.yaml" ]; then
            echo "Error: link.yaml not found"
            exit 1
          fi

      - name: Fix link.yaml Configuration
        run: |
          # 备份原始 link.yaml
          cp link.yaml link.yaml.bak
          # 检查并添加 external-controller 和 mixed-port
          if ! grep -q "external-controller" link.yaml; then
            echo "external-controller: 127.0.0.1:9090" >> link.yaml
            echo "Added external-controller to link.yaml"
          fi
          if ! grep -q "mixed-port\|port\|socks-port" link.yaml; then
            echo "mixed-port: 7890" >> link.yaml
            echo "Added mixed-port to link.yaml"
          fi
          # 验证 proxies 字段是否存在
          if ! grep -q "proxies:" link.yaml; then
            echo "Error: link.yaml must include 'proxies' field"
            exit 1
          fi
          # 输出修改后的 link.yaml 供调试
          echo "Modified link.yaml content:"
          cat link.yaml

      - name: Run Clash
        run: |
          clash -f link.yaml &
          CLASH_PID=$!
          sleep 10  # 等待 Clash 完全启动
          # 验证 Clash 外部控制器
          if ! curl -s --connect-timeout 5 http://127.0.0.1:9090/version; then
            echo "Error: Failed to connect to Clash external controller at http://127.0.0.1:9090"
            kill $CLASH_PID
            exit 1
          fi
          echo "CLASH_PID=$CLASH_PID" >> $GITHUB_ENV

      - name: Run clash-speedtest
        run: |
          ./clash-speedtest \
            --clash-addr http://127.0.0.1:9090 \
            --clash-proxy http://127.0.0.1:7890 \
            -d cloudflare \
            -r 20 \
            -t 3 \
            -y \
            -o ./clash.yaml

      - name: Check clash.yaml
        run: |
          if [ -f "clash.yaml" ]; then
            echo "Test completed, results saved to clash.yaml"
            cat clash.yaml  # 输出 clash.yaml 内容供调试
          else
            echo "Error: Failed to generate clash.yaml"
            exit 1
          fi

      - name: Cleanup Clash
        if: always()
        run: |
          if [ -n "${CLASH_PID}" ] && ps -p ${CLASH_PID} > /dev/null; then
            kill ${CLASH_PID}
          fi

      - name: Upload Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: clash-yaml
          path: clash.yaml
