name: VPN Speed Test

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  push:
    branches: [main]
  workflow_dispatch:  # 支持手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 安装 xray-core
          wget https://github.com/XTLS/Xray-core/releases/latest/download/xray-linux-64.zip
          unzip xray-linux-64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/xray

      - name: Run speed test
        run: python fetch_and_test_nodes.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results.json results.md
          git commit -m "Update VPN speed test results" || echo "No changes to commit"
          git push
