name: Node Connectivity Test with Sing-box

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Sing-box
      run: |
        wget -q https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-linux-amd64.tar.gz
        tar -xzf sing-box-linux-amd64.tar.gz
        mv sing-box-*/sing-box /usr/local/bin/
        chmod +x /usr/local/bin/sing-box
        sing-box version || exit 1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml || exit 1

    - name: Run node processing script
      run: python process_nodes_singbox.py || exit 1

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/all.txt data/failed.txt
        git commit -m 'Update test results' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
