name: Search and Extract Nodes from GitHub

on:
  workflow_dispatch:
    inputs:
      search_query_override:
        description: '可选：自定义搜索查询以覆盖脚本默认值（例如 "my_specific_keyword in:file extension:json"）'
        required: false
        default: ''
  schedule:
    - cron: '0 2 * * *'

jobs:
  run_node_extractor:
    runs-on: ubuntu-latest
    timeout-minutes: 380 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub PyYAML tqdm

    - name: Create data directory
      run: |
        mkdir -p data

    - name: Run Node Extraction Script
      env:
        BOT: ${{ secrets.BOT }}
        OVERRIDE_SEARCH_QUERY: ${{ github.event.inputs.search_query_override }}
        PYTHONUNBUFFERED: "1"
        PYTHON_LOG_LEVEL: "DEBUG"  # 启用调试日志
      run: |
        python extract_nodes.py --output data/clash_config.yaml --history data/nodes_history.json --config config.yaml

    - name: Upload Clash config as artifact
      if: always()  # 即使失败也上传
      uses: actions/upload-artifact@v4
      with:
        name: clash-config
        path: data/clash_config.yaml
        retention-days: 7

    - name: Upload node history as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: node-history
        path: data/nodes_history.json
        retention-days: 30

    - name: Upload log file as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: node-extractor-log
        path: node_extractor.log
        retention-days: 7
