name: Discover and Process Proxy Nodes # 工作流名称，现在包含“发现”功能

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 注意这里需要安装 requests, aiohttp, pyyaml
          pip install aiohttp pyyaml requests

      - name: Create data directory if not exists
        run: mkdir -p data

      # --- 关键更改：新增此步骤，运行 extract_nodes.py ---
      - name: Run URL Discovery Script (extract_nodes.py)
        env:
          BOT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python extract_nodes.py | tee extract_nodes_discovery.log
          cat extract_nodes_discovery.log
        timeout-minutes: 10 # 搜索可能需要一些时间
      # --- 关键更改结束 ---

      - name: Run Node Extraction and Testing Script (extract_nodes_from_hy2.py)
        env:
          BOT: ${{ secrets.GITHUB_TOKEN }}
          TEST_NODES: "true"
          TEST_MAX_NODES: "50"
          TEST_TIMEOUT: "1"
        run: |
          # 这个脚本现在会读取由 extract_nodes.py 生成的 data/hy2.txt
          python extract_nodes_from_hy2.py | tee extract_nodes_processing.log
          cat extract_nodes_processing.log
        timeout-minutes: 15 # 提取和测试可能需要更多时间

      - name: Upload logs and data as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: processed-proxy-nodes-artifacts
          path: |
            extract_nodes_discovery.log # 搜索脚本的日志
            extract_nodes_processing.log # 处理脚本的日志
            data/search_debug.log # 搜索脚本的调试日志
            data/extract_debug.log # 处理脚本的调试日志
            data/temp_nodes.txt
            data/protocol_nodes.txt
            data/yaml_nodes.yaml
            data/hy2.txt # 这是 extract_nodes.py 发现的 URL 列表
            data/invalid_urls.txt
          if-no-files-found: warn

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # 添加所有可能被修改或生成的文件
          git add data/hy2.txt data/invalid_urls.txt data/protocol_nodes.txt data/yaml_nodes.yaml data/search_debug.log data/extract_debug.log data/temp_nodes.txt || true
          git commit -m "Automated: Update proxy nodes and logs" || echo "No changes to commit"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
