name: Node Connectivity Test

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC 凌晨 3:00
  workflow_dispatch:

jobs:
  test_node_connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl netcat-openbsd # 确保安装 netcat-openbsd
        # dnsutils 的安装已移至脚本内部，但也可以放这里以确保
        # sudo apt-get install -y dnsutils

    - name: Make script executable
      run: chmod +x speed_test.sh

    - name: Run node connectivity test
      run: ./speed_test.sh

    - name: Upload connectivity test results
      uses: actions/upload-artifact@v4
      with:
        name: node-connectivity-results
        path: node_connectivity_results.log
        retention-days: 7

    - name: Upload successful nodes
      uses: actions/upload-artifact@v4
      with:
        name: successful-nodes
        path: successful_nodes.log # 上传成功节点的日志文件
        retention-days: 7
