name: Node Speed Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Fail if job runs longer than 60 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Cache Clash core
      id: cache-clash
      uses: actions/cache@v4
      with:
        path: clash_bin
        key: ${{ runner.os }}-clash-core-v1.18.0-v1 # Update if CLASH_VERSION_TO_DOWNLOAD changes
        restore-keys: |
          ${{ runner.os }}-clash-core-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run node speed test script
      run: |
        mkdir -p data
        python speed_tester.py

    - name: Commit and push results
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/collectSub.txt
        if [ -s data/collectSub.txt ] && ! git diff --cached --exit-code; then
          git commit -m "Update node speed test results [skip ci]"
          git push
        else
          echo "No valid changes to commit (file empty or unchanged)."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.BOT }}
