name: Extract Nodes Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  extract-nodes:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 使用最新 Python 3.x 版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 运行 extract_nodes.py 脚本
      - name: Run extract_nodes.py
        env:
          BOT: ${{ secrets.BOT }}  # 从 GitHub Secrets 获取 BOT token
        run: python extract_nodes.py

      # 提交生成的文件（如果有更改）
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/hy2.txt
          git commit -m "Update hy2.txt with extracted URLs" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于推送更改
