name: Speed Test sh

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bash
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run speed test
        env:
          BOT_TOKEN: ${{ secrets.BOT }}
        run: |
          chmod +x speed_test.sh
          ./speed_test.sh

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/sub.txt data/failed_proxies.json
          git commit -m "Update speed test results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
