name: Test Nodes

on:
  schedule:
    - cron: '0 4 * * *'  # 每天 UTC 04:00 运行（北京时间 12:00）
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: qjlxg/sh
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          python -m pip install --upgrade pip
          pip install requests

      - name: Cache sing-box Binary
        id: cache-sing-box
        uses: actions/cache@v4
        with:
          path: clash_bin
          key: Linux-sing-box-v1.9.7
          restore-keys: Linux-sing-box-

      - name: Download sing-box
        if: steps.cache-sing-box.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.9.7/sing-box-1.9.7-linux-amd64.tar.gz
          tar -xzf sing-box-1.9.7-linux-amd64.tar.gz
          mkdir -p clash_bin
          mv sing-box-1.9.7-linux-amd64/sing-box clash_bin/sing-box
          chmod +x clash_bin/sing-box

      - name: Run Speed Tester
        env:
          SINGBOX_LOG_PATH: data/sing-box.log
        run: |
          mkdir -p data
          python speed_tester.py || true

      - name: Display sing-box Debug Log
        run: |
          cat data/sing-box.log || echo "No debug log available."

      - name: Display collectSub Output
        run: |
          cat data/collectSub.txt || echo "No collectSub output available."

      - name: Upload sing-box Config
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-config-file
          path: sing-box-config.json
          if-no-files-found: ignore

      - name: Upload sing-box Debug Log
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-debug-log
          path: data/sing-box.log
          if-no-files-found: ignore

      - name: Upload collectSub Output
        uses: actions/upload-artifact@v4
        with:
          name: collect-sub
          path: data/collectSub.txt
          if-no-files-found: ignore

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"
          if [[ -s data/collectSub.txt ]] && ! git diff --cached --exit-code; then
            git add data/collectSub.txt
            git commit -m "Update node speed test results [skip ci]"
            git push origin main
          else
            echo "No valid changes to commit."
          fi
