name: Proxy Tester Workflow

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  test-proxies:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 使用 Python 3.11（可根据需要调整）

      # 安装 Python 依赖
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 下载 sing-box 可执行文件
      - name: Install sing-box
        run: |
          mkdir -p clash_bin
          curl -L -o clash_bin/sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-linux-amd64.tar.gz
          tar -xzf clash_bin/sing-box.tar.gz -C clash_bin
          mv clash_bin/sing-box-*/sing-box clash_bin/sing-box
          chmod +x clash_bin/sing-box

      # 运行 Python 脚本
      - name: Run proxy tester script
        run: python main.py

      # 检查输出文件并提交更改
      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/collectSub.txt
          git commit -m "Update proxy test results" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 清理（可选）
      - name: Clean up
        if: always()
        run: |
          rm -rf clash_bin/sing-box.tar.gz
