name: 测试

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_node_connectivity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        token: ${{ secrets.BOT }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/speed_test.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl netcat-openbsd dnsutils jq

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Make script executable
      run: chmod +x speed_test.sh

    - name: Run node connectivity test
      env:
        GH_TOKEN_FOR_PUSH: ${{ secrets.BOT }}
        DEBUG: true
        PARALLEL_JOBS: 30
      run: ./speed_test.sh || { echo "Script failed"; exit 1; }

    - name: Check temporary files (debug)
      if: always()
      run: |
        echo "Listing all files in /tmp:"
        ls -l /tmp/ || echo "No files in /tmp"
        echo "Checking temporary files:"
        find /tmp -type f -name 'tmp*' -exec sh -c 'echo "File: {}"; cat {}; echo ""' \;

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: node-connectivity-results
        path: |
          node_connectivity_results.log
          data/sub.txt
          data/failed_nodes.log
        retention-days: 7
