name: 测试

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC 凌晨 3:00 运行
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_node_connectivity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        token: ${{ secrets.BOT }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl netcat-openbsd dnsutils jq

    - name: Make script executable
      run: chmod +x speed_test.sh

    - name: Run node connectivity test
      env:
        GH_TOKEN_FOR_PUSH: ${{ secrets.BOT }}
        DEBUG: false # 可手动设置为 true 启用调试日志
      run: ./speed_test.sh

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: node-connectivity-results
        path: node_connectivity_results.log
        retention-days: 7
