name: 下载YAML文件内容

on:
  workflow_dispatch:

jobs:
  download_yaml_files:
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
      GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
      GITHUB_TOKEN: ${{ secrets.BOT }}  # 你在Secrets中设置的BOT token
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          pip install requests

      - name: 运行脚本
        run: |
          python node.py

      - name: 查看结果
        run: cat data/ji.txt
