name: Convert to YAML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests pyyaml
    - name: Run conversion script
      run: python convert_to_yaml.py
    - name: Commit YAML files
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add input/*.yml
        git commit -m "Update individual YAML configs" || echo "No changes to commit"
        git push
