name: Test and Process Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发工作流

jobs:
  test_and_deduplicate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install requests # 安装requests库用于网络请求

    - name: Create data directory if not exists
      run: mkdir -p data

    - name: Run node testing and deduplication script
      run: python scripts/enhance_nodes.py # 调用更新后的脚本名称

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions Bot
        author_email: actions@github.com
        message: 'Docs: Auto-test and deduplicate nodes'
        add: 'data/enhanced_nodes.txt'
