name: Proxy Node Converter Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  convert-proxies:
    runs-on: ubuntu-latest # 在 Ubuntu 虚拟机上运行

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 使用 Python 3.10

      # 安装 Playwright 依赖 (系统库)
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
            libxrandr2 libgbm1 libasound2t64 libpango-1.0-0 libcairo2

      # 安装 Python 依赖 (包括 lxml 和其他必要的库)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pyyaml beautifulsoup4 fake-useragent playwright lxml

      # 安装 Chromium 浏览器
      - name: Install Chromium browser
        run: python -m playwright install chromium

      # 创建输出目录
      - name: Create output directories
        run: |
          mkdir -p data/nodes

      # 运行代理节点转换脚本
      - name: Run proxy converter script
        run: |
          python cc6_modified.py \
            --sources sources.list \
            --nodes-output-dir data/nodes \
            --stats-output data/node_counts.csv \
            --max-concurrency 50 \
            --timeout 30 \
            --use-browser

      # 提交输出文件到仓库 (包括数据/缓存文件)
      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/ # 添加 data 目录下的所有生成文件 (nodes, stats, cache)
          # 检查是否有改动，有则提交
          git diff --quiet && git diff --staged --quiet || git commit -m "Update proxy nodes, stats, and cache"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自动提供的 GitHub Token
