name: Run GitHub Node Search

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00（CST 08:00）
  workflow_dispatch:

jobs:
  search-and-extract:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 设置 30 分钟超时

    env:
      TZ: Asia/Shanghai
      BOT: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp requests pyyaml pytz

      - name: Run URL search
        run: python search_urls.py

      - name: Run node extraction
        run: python extract_nodes.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            data/url.txt
            data/hy2.txt
            data/invalid_urls.txt
            data/search.log
            data/extract.log
