name: Search and Extract Nodes from GitHub

on:
  workflow_dispatch:
   
    inputs:
      search_query:
        description: 'Optional: Custom search query for GitHub Code Search'
        required: false
        default: ''

  schedule:
    # 每天凌晨2点（UTC时间）自动运行工作流
    # 您可以根据需要调整cron表达式
    - cron: '0 2 * * *' 

jobs:
  run_node_extractor:
    runs-on: ubuntu-latest # 在最新的Ubuntu Runner上运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # 如果您的Python脚本位于私有仓库中，并且您需要访问其他私有仓库进行搜索
      # 确保actions/checkout有足够的权限（例如，使用GITHUB_TOKEN或Personal Access Token）

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用Python 3的最新版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub PyYAML

    - name: Run Node Extraction Script
      env:
       
        BOT: ${{ secrets.GH_TOKEN }}
        CUSTOM_SEARCH_QUERY: ${{ github.event.inputs.search_query }} # 传递手动触发时的自定义查询
      run: |
        # 创建data目录，以防它不存在
        mkdir -p data

        # 运行您的Python脚本
        # 假设您的Python脚本名为 `extract_nodes.py`
        # 如果您在脚本中使用了 os.getenv("CUSTOM_SEARCH_QUERY")，它将优先使用手动触发时的输入
        # 否则，脚本将使用其内部定义的搜索逻辑
        python github_node_search.py
        
    - name: Upload extracted nodes as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extracted-nodes
        path: data/hy2.txt
        # 保留多久（天），默认是90天
        retention-days: 7
