name: Search and Extract Nodes from GitHub

on:
  workflow_dispatch:
    inputs:
      search_query_override:
        description: 'Optional: Custom search query to override script defaults (e.g., "my_specific_keyword in:file extension:json")'
        required: false
        default: ''

  schedule:
    - cron: '0 2 * * *' 

jobs:
  run_node_extractor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub PyYAML requests # <--- 新增 requests 库

    - name: Create data directory
      run: |
        mkdir -p data

    - name: Run Node Extraction Script
      env:
        BOT: ${{ secrets.BOT }} 
        OVERRIDE_SEARCH_QUERY: ${{ github.event.inputs.search_query_override }}
        PYTHONUNBUFFERED: "1" 
      run: |
        python github_node_search.py
        
    - name: Upload extracted nodes as artifact
      uses: actions:upload-artifact@v4
      with:
        name: extracted-nodes
        path: data/hy2.txt
        retention-days: 7
