name: Node Search Workflow

on:
  schedule:
    - cron: '0 2 * * *'  # 每天上海时间上午10点（UTC 02:00）
  workflow_dispatch:  # 支持手动触发

jobs:
  search-nodes:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为上海时间（CST，UTC+8）
      BOT: ${{ secrets.BOT }}  # 从 GitHub Secrets 加载 BOT token

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 使用 Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml aiohttp

    - name: Run node search script
      run: |
        python github_node_search.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        if [ -f data/hy2.txt ] || [ -f data/url.txt ]; then
          git add data/hy2.txt data/url.txt
          git commit -m "Update nodes and URLs [$(date -u '+%Y-%m-%dT%H:%M:%S+08:00')]" || true
          git push
        else
          echo "No output files to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于 git push
