name: IPTV URL Processor(频道提取)

# 触发条件
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */168 * * *'  # 每周运行一次

jobs:
  process_iptv: # 更改 Job 名称以反映其功能
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 适当调整超时时间，例如 3 小时，因为它需要处理大量 URL 和频道
    permissions:
      contents: write  # 授予写入权限，用于提交和推送更改

    steps:
      # 步骤 1：检查 BOT secret
      - name: 检查 BOT secret
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "错误：未设置 BOT secret，请在 GitHub Secrets 中配置"
            exit 1
          fi
        shell: bash

      # 步骤 2：检出代码
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史，便于 rebase
          token: ${{ secrets.TOKEN }}  # 使用 BOT secret 进行认证

      # 步骤 3：设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # 缓存 pip 依赖

      # 步骤 4：安装 Python 依赖 (根据 iptv_processor.py 的实际需求精简)
      - name: 安装 Python 依赖
        run: |
          pip install pyyaml requests cachetools tenacity
          # 确保安装了 tenacity，因为 fetch_url_content_with_retry 函数使用了它
          # 移除了 aiohttp, beautifulsoup4, psutil, dnspython, tqdm, aiofiles 等，因为 iptv_processor.py 不直接使用或简化了相关功能

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 步骤 5：运行 IPTV 处理脚本
      # 移除了安装和验证 FFmpeg (ffprobe) 的步骤，因为 iptv_processor.py 不再依赖它们
      - name: 运行 IPTV 处理脚本
        env:
          BOT: ${{ secrets.TOKEN }} # 将 GitHub token 传递给脚本
        run: python iptv_processor.py # 运行精简后的处理脚本

      # 步骤 6：保存日志和生成文件 (根据 iptv_processor.py 的输出调整)
      - name: 保存日志和生成文件
        uses: actions/upload-artifact@v4
        with:
          name: iptv-processed-results
          path: |
            logs/iptv_processor.log       # 捕获日志文件 (根据新脚本的日志文件命名约定调整)
            output/urls.txt               # 捕获更新后的 URL 列表
            output/*.m3u                  # 捕获最终的 IPTV M3U 文件
            output/uncategorized_channels.txt # 捕获未分类频道文件
            output/channels/              # 捕获分类频道文件目录
            # config/*.txt                  # 如果有其他想保存的config文件
            # config/*.json
          retention-days: 7
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
        if: always() # 无论成功失败都上传，方便调试

      # 步骤 7：检查文件更改
      - name: 检查文件更改
        id: check_changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "没有文件更改"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件更改"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      # 步骤 8：提交更改
      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --allow-empty -m "更新 IPTV URL 及频道列表 ($(date +'%Y-%m-%d %H:%M'))"

      # 步骤 9：推送更改 (优先合并)
      - name: 推送更改 (优先合并)
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git fetch origin main # 拉取远程 main 分支的最新状态
          # 尝试合并远程更改。如果合并失败（有冲突），则退出并报错。
          git merge origin/main -m "Merge remote changes before pushing" || (echo "错误：检测到合并冲突，请手动解决或检查日志" && exit 1)
          git push origin main # 推送合并后的更改
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # 步骤 10：发送运行结果通知
      - name: 发送运行结果通知
        run: |
          echo "IPTV URL 发现和处理工作流完成，状态: ${{ job.status }}"
          echo "请检查 artifact 中的日志文件以获取详细信息"
