# .github/workflows/speedtest.yml
name: Clash 速度测试与排序 (使用已上传的 clash-speedtest)

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，您可以根据需要调整

jobs:
  speed-test-and-sort:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 赋予 clash-speedtest 执行权限
      # 直接使用仓库中已上传的 clash-speedtest 文件
      run: |
        echo "赋予仓库中已上传的 'clash-speedtest' 执行权限..."
        chmod +x ./clash-speedtest
        echo "'clash-speedtest' 已设置为可执行文件。"
        # 验证文件是否存在
        if [ ! -f "./clash-speedtest" ]; then
          echo "错误: 未在仓库根目录找到 'clash-speedtest' 文件。请确保您已将其上传。"
          exit 1
        fi
      
    - name: 运行速度测试并生成排序后的配置文件
      # 直接调用仓库中已有的 clash-speedtest 工具，并使用其 -output 标志
      run: |
        echo "正在运行已上传的 'clash-speedtest'..."
        ./clash-speedtest \
          -c ./clash_config.yaml \
          -output ./clash.yaml \
          -download-size 50MB \
          -timeout 10s \
          -concurrent 4 # 并发测试可以加快速度，根据需要调整

        EXIT_CODE=$?
        echo "'clash-speedtest' 退出代码: ${EXIT_CODE}"
        if [ "$EXIT_CODE" -ne 0 ]; then
          echo "错误: 'clash-speedtest' 返回了非零退出代码。请检查其输出日志。"
          exit 1
        fi
        echo "--- 速度测试运行结束 ---"

    - name: 验证生成的 clash.yaml 文件
      id: check_file
      run: |
        echo "正在验证 'clash.yaml' 文件是否存在..."
        ls -la
        
        if [ -f "clash.yaml" ]; then
          echo "'clash.yaml' 文件已找到！内容预览:"
          echo "文件大小: $(du -h clash.yaml | awk '{print $1}')"
          head -n 20 clash.yaml # 打印文件前20行供检查
        else
          echo "严重错误: 'clash.yaml' 文件未能由 'clash-speedtest' 生成。"
          exit 1 # 如果文件未生成，强制作业失败
        fi
      # 此步骤仅在上一步成功时运行
      if: success()

    - name: 提交并推送排序后的配置文件
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "更新 Clash 配置：节点已按速度排序 (via 已上传的 clash-speedtest)"
        files: clash.yaml # 指定要提交的文件
        branch: main # 确保您的主分支名称是 'main' (或 'master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 仅当文件成功生成并验证后才尝试提交
      if: success() && steps.check_file.outcome == 'success'
