# .github/workflows/speedtest.yml
name: Clash Speed Test and Sort

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，您可以根据需要调整

jobs:
  speed-test-and-sort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make Speedtest Tool Executable
      # 因为 speedtest-clash 已经存在于仓库中，我们只需要赋予它执行权限
      run: chmod +x ./speedtest-clash

    - name: Run Speed Test and Sort
      # 执行速度测试并排序，然后保存到 clash.yaml
      run: |
        ./speedtest-clash \
          --config ./clash_config.yaml \
          --output ./clash.yaml \
          --sort-by download --order desc \
          --sort-by latency --order asc \
          --size 50M \
          --timeout 10s

    - name: Commit and Push Sorted Config
      # 将排序后的 clash.yaml 文件提交回仓库
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update Clash config with sorted nodes by speed and latency"
        files: clash.yaml
        branch: main # 确保您的主分支名称正确，可能是 master 或 main
