name: Node Connectivity Test

on:
  push:
   
     
  workflow_dispatch: # 允许手动触发

jobs:
  test_nodes:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 设置最大运行时间为 6 小时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests dnspython # <--- 新增 dnspython 安装

    - name: Run node connectivity test script
      run: python speed_test.py

    - name: Commit and push connected nodes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update connected nodes list after connectivity test"
        files: data/connected_nodes.txt
