# .github/workflows/speedtest.yml
name: Clash Speed Test - Part 1 (Log Generation)

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (adjust as needed)

jobs:
  speed-test-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make Speedtest Tool Executable
      run: chmod +x ./speedtest-clash

    - name: Run Speed Test and Capture All Output to Log File
      # Run speedtest-clash and redirect its full output (stdout + stderr) to speedtest_output.log
      # This ensures all messages, including the JSON line, are captured.
      run: |
        echo "Starting speedtest-clash and capturing all output..."
        ./speedtest-clash \
          -c ./clash_config.yaml \
          -output /dev/null \
          -sort b \
          -size 52428800 \
          -timeout 10s > speedtest_output.log 2>&1
        
        EXIT_CODE=$?
        echo "speedtest-clash exited with code: ${EXIT_CODE}"
        echo "--- End of speedtest-clash run ---"
        
        # Verify the log file was created and show its content
        echo "--- Content of speedtest_output.log ---"
        if [ -f "speedtest_output.log" ]; then
          cat speedtest_output.log
        else
          echo "Error: speedtest_output.log was not created!"
          exit 1
        fi
        echo "---------------------------------------"
      id: run_speedtest_and_log # Give this step an ID

    - name: Commit Generated Log File (for inspection)
      # This step is temporary, just to easily inspect speedtest_output.log
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Debug: Add speedtest_output.log for inspection"
        files: speedtest_output.log # Commit the generated log file
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Only commit if the previous step succeeded and the log file exists
      if: success() && steps.run_speedtest_and_log.outcome == 'success' && -f 'speedtest_output.log'
