# .github/workflows/speedtest.yml
name: Clash Speed Test and Sort

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，您可以根据需要调整

jobs:
  speed-test-and-sort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make Speedtest Tool Executable
      run: chmod +x ./speedtest-clash

    - name: Run Speed Test and Sort
      # 执行速度测试并排序，然后保存到 clash.yaml
      run: |
        echo "Starting speedtest-clash..."
        ./speedtest-clash \
          -c ./clash_config.yaml \
          -output ./clash.yaml \
          -sort b \
          -size 52428800 \
          -timeout 10s
        # 捕获 speedtest-clash 的退出码
        EXIT_CODE=$?
        echo "speedtest-clash exited with code: ${EXIT_CODE}"
        echo "--- End of speedtest-clash run ---"

    - name: Check if clash.yaml exists and its content
      run: |
        echo "Checking for clash.yaml file..."
        if [ -f "clash.yaml" ]; then
          echo "clash.yaml found!"
          echo "File size: $(du -h clash.yaml | awk '{print $1}')"
          echo "First 10 lines of clash.yaml:"
          head -n 10 clash.yaml
          echo "--- End of clash.yaml content ---"
        else
          echo "clash.yaml NOT found after speedtest-clash run."
        fi
        echo "Listing current directory contents:"
        ls -la
      # 即使上一步失败，也强制运行此步骤，以便查看调试信息
      if: always()

    - name: Commit and Push Sorted Config
      # 将排序后的 clash.yaml 文件提交回仓库
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update Clash config with sorted nodes by speed"
        files: clash.yaml
        branch: main
      # 仅当 clash.yaml 文件存在时才尝试提交
      if: success() && steps.check_file.outputs.file_exists == 'true'
      id: commit_step # 为后续步骤添加 ID 以便引用
