name: Node Connectivity Test

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y dnsutils curl jq

      - name: Install Python dependencies
        run: |
          pip install requests pyyaml

      - name: Install Sing-Box
        run: |
          echo "开始安装 Sing-Box..."
          # 尝试获取 Sing-Box 版本，最多重试 3 次
          for i in {1..3}; do
            echo "尝试 $i 次获取 Sing-Box 版本..."
            # 使用 curl 获取最新发布信息，并保存原始响应
            RAW_RESPONSE=$(curl -s --retry 3 https://api.github.com/repos/SagerNet/sing-box/releases/latest)
            echo "原始 API 响应内容 (用于调试):"
            echo "$RAW_RESPONSE" | head -n 20 # 只显示前 20 行，避免日志过长
            
            # 从原始响应中提取 tag_name
            SING_BOX_VERSION=$(echo "$RAW_RESPONSE" | jq -r '.tag_name')
            echo "提取到的 Sing-Box 版本: $SING_BOX_VERSION" # 调试：查看提取的版本

            # 检查版本是否成功提取
            if [ -n "$SING_BOX_VERSION" ]; then
              echo "成功获取到 Sing-Box 版本: $SING_BOX_VERSION"
              break # 成功获取，退出循环
            else
              echo "重试 $i 次：未能获取 Sing-Box 版本或版本为空。等待 5 秒后重试..."
              sleep 5
            fi
          done

          # 如果经过多次重试仍未获取到版本，则报错退出
          [ -z "$SING_BOX_VERSION" ] && { echo "错误：多次重试后仍无法获取 Sing-Box 版本。请检查 GitHub API 状态或网络连接。"; exit 1; }

          # 构建下载 URL
          SING_BOX_URL="https://github.com/SagerNet/sing-box/releases/download/${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION#v}-linux-amd64.tar.gz"
          echo "正在从 $SING_BOX_URL 下载 Sing-Box..."
          
          # 下载 Sing-Box
          curl -sL --retry 3 "$SING_BOX_URL" -o sing-box.tar.gz || { echo "错误：下载 Sing-Box 失败"; exit 1; }
          
          # 验证是否为有效的 gzip 压缩包
          file sing-box.tar.gz | grep -q "gzip compressed data" || { echo "错误：下载的文件不是有效的 gzip 压缩包。"; exit 1; }
          
          # 解压
          tar -xzf sing-box.tar.gz || { echo "错误：解压 Sing-Box 归档文件失败。"; exit 1; }
          
          # 查找 Sing-Box 二进制文件并移动到 /usr/local/bin
          SING_BOX_BINARY=$(find . -type f -name sing-box)
          [ -z "$SING_BOX_BINARY" ] && { echo "错误：在归档文件中未找到 Sing-Box 二进制文件。"; exit 1; }
          sudo mv "$SING_BOX_BINARY" /usr/local/bin/sing-box
          sudo chmod +x /usr/local/bin/sing-box
          
          # 清理下载文件
          rm -rf sing-box.tar.gz sing-box-*
          
          # 验证 Sing-Box 安装
          sing-box version || { echo "错误：Sing-Box 安装失败或无法执行。"; exit 1; }
          echo "Sing-Box 安装成功！"

      - name: Install Xray Core
        run: |
          echo "开始安装 Xray Core..."
          curl -L --retry 3 https://github.com/XTLS/Xray-install/raw/main/install-release.sh -o /tmp/install-xray.sh
          [ -s /tmp/install-xray.sh ] || { echo "错误：下载 Xray 安装脚本失败"; exit 1; }
          chmod +x /tmp/install-xray.sh
          sudo bash /tmp/install-xray.sh
          rm -f /tmp/install-xray.sh
          xray version || { echo "错误：Xray 安装失败"; exit 1; }
          echo "Xray Core 安装成功！"

      - name: Run speed test script
        run: |
          echo "正在运行速度测试脚本..."
          
          # ----> 关键诊断步骤：检查 sing-box 和 xray 的实际状态 <----
          echo "--- 诊断 /usr/local/bin/sing-box ---"
          ls -l /usr/local/bin/sing-box || echo "ls 失败: 文件不存在或无权限"
          which sing-box || echo "which 失败: sing-box 不在 PATH 中可找到"
          /usr/local/bin/sing-box version || echo "直接执行 sing-box 失败"

          echo "--- 诊断 /usr/local/bin/xray ---"
          ls -l /usr/local/bin/xray || echo "ls 失败: 文件不存在或无权限"
          which xray || echo "which 失败: xray 不在 PATH 中可找到"
          /usr/local/bin/xray version || echo "直接执行 xray 失败"
          echo "-------------------------------------"

          # 确保 /usr/local/bin 在 PATH 中 (虽然你已经在 Python 脚本中指定了完整路径，但保留此行仍有助于确保 shell 环境的一致性)
          export PATH="/usr/local/bin:$PATH"
          
          # 运行 Python 脚本 (假设 Python 脚本中已将 sing-box 和 xray 的调用改为完整路径)
          chmod +x speed_test.py
          python3 speed_test.py
          echo "速度测试脚本运行完成。"

      - name: Commit and push results
        run: |
          echo "正在提交并推送结果..."
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # 检查是否有文件发生变化，避免空提交
          git diff --quiet --exit-code data/sub.txt data/failed_nodes.txt node_connectivity_results.log unparsed_nodes.log || git add data/sub.txt data/failed_nodes.txt node_connectivity_results.log unparsed_nodes.log
          git commit -m "Update node test results $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "没有需要提交的更改。"
          git push
        env:
          # 使用你的自定义秘密令牌名称
          GITHUB_TOKEN: ${{ secrets.BOT }}
        echo "结果提交并推送完成。"
