name: Speed Test sh

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }} # 使用默认 GITHUB_TOKEN

      - name: Set up Bash and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils netcat-openbsd curl coreutils jq parallel

      - name: Run speed test
        run: |
          chmod +x speed_test.sh
          ./speed_test.sh 2>&1 | tee speed_test_output.log
          if [ $? -ne 0 ]; then
            echo "Speed test script failed. Check logs for details."
            cat speed_test_output.log
            exit 1
          fi

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch origin
          # Stash any local changes to avoid rebase conflicts
          git stash push --include-untracked
          git pull origin main --rebase
          git stash pop || true # Restore changes, ignore if no stash
          # Add files if they exist
          [ -f data/sub.txt ] && git add data/sub.txt || echo "data/sub.txt not found, skipping"
          [ -f data/failed_proxies.json ] && git add data/failed_proxies.json || echo "data/failed_proxies.json not found, skipping"
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update speed test results - $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - name: Upload logs
        if: always() # 即使失败也上传日志
        uses: actions/upload-artifact@v4
        with:
          name: speed-test-logs
          path: |
            node_connectivity_results.log
            speed_test_output.log
