# .github/workflows/speedtest.yml
name: Clash Speed Test and Sort

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，您可以根据需要调整

jobs:
  speed-test-and-sort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make Speedtest Tool Executable
      run: chmod +x ./speedtest-clash

    - name: Run Speed Test and Sort
      # 只按带宽（下载速度）排序
      run: |
        ./speedtest-clash \
          -c ./clash_config.yaml \
          -output ./clash.yaml \
          -sort b \
          -size 52428800 \
          -timeout 10s
        # -sort b 表示按带宽（下载速度）排序，通常默认是降序（从大到小）。
        # 50MB 转换为字节是 50 * 1024 * 1024 = 52428800 字节。
