name: Node Connectivity Test

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at UTC 00:00
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y dnsutils curl jq

      - name: Install Python dependencies
        run: |
          pip install requests pyaml

      - name: Install Sing-Box
        run: |
          # Retry fetching version 3 times
          for i in {1..3}; do
            SING_BOX_VERSION=$(curl -s --retry 3 https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.tag_name') && break
            echo "Retry $i: Failed to fetch Sing-Box version"
            sleep 1
          done
          [ -z "$SING_BOX_VERSION" ] && { echo "Error: Could not fetch Sing-Box version"; exit 1; }
          SING_BOX_URL="https://github.com/SagerNet/sing-box/releases/download/${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION:1}-linux-amd64.tar.gz"
          curl -sL --retry 3 "$SING_BOX_URL" -o sing-box.tar.gz
          # Verify gzip format
          file sing-box.tar.gz | grep -q "gzip compressed data" || { echo "Error: Downloaded file is not a valid gzip archive"; exit 1; }
          tar -xzf sing-box.tar.gz
          sudo mv sing-box-*/sing-box /usr/local/bin/
          rm -rf sing-box.tar.gz sing-box-*
          sing-box version

      - name: Install Xray Core
        run: |
          # Download script to a temporary file
          curl -L --retry 3 https://github.com/XTLS/Xray-install/raw/main/install-release.sh -o /tmp/install-xray.sh
          # Verify file exists and is not empty
          [ -s /tmp/install-xray.sh ] || { echo "Error: Failed to download Xray install script"; exit 1; }
          chmod +x /tmp/install-xray.sh
          sudo bash /tmp/install-xray.sh
          rm -f /tmp/install-xray.sh
          xray version

      - name: Run speed test script
        run: |
          chmod +x speed_test.py
          python3 speed_test.py

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/sub.txt data/failed_nodes.txt node_connectivity_results.log unparsed_nodes.log
          git commit -m "Update node test results $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
        env:
          BOT: ${{ secrets.BOT }}  # Renamed token
