name: clash-speedtest

on:
  push:
    paths:
      - '.github/workflows/starudream.yml'
      
  schedule:
    - cron: '0 */3 * * *'
  # 允许手动触发
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run-speedtest:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
      
      - name: 下载并安装 clash-speedtest 工具
        run: |
          # 下载最新的 Linux AMD64 版本
          wget https://github.com/starudream/clash-speedtest/releases/download/v3.0.1/clash-speedtest_v3.0.1_linux_amd64.tar.gz
          
          # 解压文件
          tar -xzvf clash-speedtest_v3.0.1_linux_amd64.tar.gz
          
          # 将可执行文件移动到 PATH 目录
          sudo mv clash-speedtest /usr/local/bin/

      - name: 备份上次运行结果
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          if [ -f "clash.yaml" ]; then
            cp clash.yaml sc/clash_$TIMESTAMP.yaml
            echo "已成功备份 clash.yaml 到 sc/clash_$TIMESTAMP.yaml"
          else
            echo "clash.yaml 文件不存在，跳过备份。"
          fi
      
      - name: 运行测速并筛选节点
        run: |
          clash-speedtest -y \
                          -i ".*" \
                          -o clash.yaml \
                          --clash-proxy "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/clash_config.yaml" \
                          --threads 15
      
      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          git add clash.yaml sc/
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update and filter Clash nodes via speedtest"
            
            for i in {1..3}; do
              git pull --rebase
              git push && break
              sleep 5
            done
          else
            echo "没有节点更改，无需提交。"
          fi
