
name: Stream Quality Check

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:     # 支持手动触发
  push:
    branches:
      - main
    paths:
      - 'stream_quality_checker.py'
      - 'config/config.yaml'
      - 'output/iptv_list.txt'

jobs:
  check-stream-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run Stream Quality Checker
        env:
          BOT: ${{ secrets.BOT }}
        run: |
          python stream_quality_checker.py

      - name: Commit High Quality IPTV List
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add output/high_quality_iptv.txt
          git commit -m "Update high_quality_iptv.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
