name: Process IPTV URLs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  process-urls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3]  # 分 4 片
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run URL processing script
      run: python scripts/process_urls.py --shard ${{ matrix.shard }} --total-shards 4

    - name: Commit and push shard results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/*.txt output/timestamps.json
        git commit -m "Update processed URLs for shard ${{ matrix.shard }}" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-results:
    runs-on: ubuntu-latest
    needs: process-urls
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Merge results
      run: python scripts/merge_results.py

    - name: Commit and push final playlist
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/final_playlist.txt
        git commit -m "Update final merged playlist" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
