name: Process IPTV URLs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  process-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run URL processing script
      run: python scripts/process_urls.py

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/list.txt output/mpeg.txt output/failed.txt output/timestamps.json output/*.txt
        git commit -m "Update processed URLs and categorized results" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
