name: Validate IPTV Channels

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行一次 (可根据需要调整)
  workflow_dispatch: # 允许手动触发

jobs:
  validate-channels:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境中运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests # 安装 Python 依赖
        sudo apt-get update
        sudo apt-get install -y ffmpeg # 安装 FFmpeg

    - name: Create output directory
      run: mkdir -p output

    - name: Copy iptv_list.txt to output directory (if it's not already there)
     
      run: |
        if [ -f iptv_list.txt ]; then
          cp iptv_list.txt output/iptv_list.txt
        else
          echo "Warning: iptv_list.txt not found in root. Please ensure it's in the output directory or adjust this step."
          # Optionally create a dummy file if it doesn't exist to prevent script failure
          echo "Placeholder,http://example.com/null.m3u8" > output/iptv_list.txt
        fi

    - name: Run IPTV validation script
     
      run: python stream_quality_checker.py

    - name: Commit and push updated list
      # 仅在有更改时才提交
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        # 确保添加了 output/high_quality_iptv.txt 和 output/iptv_validation.log
        git add output/high_quality_iptv.txt output/iptv_validation.log
        git diff --cached --exit-code || git commit -m "Auto-update: High-quality IPTV list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的 token
