name: Validate IPTV Channels

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行一次 (可根据需要调整)
  workflow_dispatch: # 允许手动触发

jobs:
  validate-channels:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境中运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests # 安装 Python 依赖
        sudo apt-get update
        sudo apt-get install -y ffmpeg # 安装 FFmpeg

    - name: Create output directory (if it doesn't exist)
   
      run: mkdir -p output

    - name: Run IPTV validation script
      run: python stream_quality_checker.py

    - name: Commit and push updated list
      # 仅在有更改时才提交
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        # 强制添加 high_quality_iptv.txt 和 iptv_validation.log，以处理 .gitignore 的问题
        git add -f output/high_quality_iptv.txt output/iptv_validation.log
        git diff --cached --exit-code || git commit -m "Auto-update: High-quality IPTV list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的 token
