name: Test Nodes and Update Results

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以便提交

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx aiodns aiofiles psutil
          pip freeze > dependency_versions.txt

      - name: Download Xray
        run: |
          wget -q https://github.com/XTLS/Xray-core/releases/download/v1.8.4/Xray-linux-64.zip
          unzip -q Xray-linux-64.zip -d .
          chmod +x xray
          mkdir -p data
          wget -q -O data/geoip-lite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget -q -O data/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

      - name: Check disk space and permissions
        run: |
          df -h
          ls -ld data/
          touch data/test.txt && rm data/test.txt

      - name: Run Node Tester Script
        run: |
          export TEST_TIMEOUT=15
          export LOG_LEVEL=DEBUG
          export XRAY_PATH=$(pwd)/xray
          export XRAY_GEOIP_PATH=$(pwd)/data/geoip-lite.dat
          export XRAY_GEOSITE_PATH=$(pwd)/data/geosite.dat
          export BATCH_SIZE=10
          python test_nodes.py | tee test_output.log
          SUCCESS_COUNT=$(grep "最终成功节点数:" test_output.log | awk '{print $NF}' || echo "0")
          echo "successful_nodes_count=${SUCCESS_COUNT}" >> $GITHUB_OUTPUT

      - name: Check generated files
        run: |
          echo "Listing files in data directory:"
          ls -la data/
          echo "Content of sub.txt:"
          cat data/sub.txt || echo "sub.txt is empty or not found"
          echo "Content of success_count.txt:"
          cat data/success_count.txt || echo "success_count.txt is empty or not found"

      - name: Commit and Push results
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/sub.txt data/success_count.txt data/history_results.json data/dns_cache.json data/geoip-lite.dat data/geosite.dat
          git commit -m "Update node test results" || echo "No changes to commit"
          git push origin main
        if: always()  # Always attempt to commit, even if no changes

      - name: Upload test logs and dependencies
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            test_output.log
            dependency_versions.txt
            data/sub.txt
            data/success_count.txt
            data/history_results.json
            data/dns_cache.json
            data/geoip-lite.dat
            data/geosite.dat
            data/*.json
          retention-days: 7
          if-no-files-found: warn
