name: 测试代理节点

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp tqdm

      - name: 下载 sing-box
        run: |
          SINGBOX_VERSION="1.10.1"
          wget -q https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          mv sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box .
          chmod +x sing-box
          rm -rf sing-box-${SINGBOX_VERSION}-linux-amd64*
          ./sing-box version

      - name: 运行节点测试
        run: python test_proxy_nodes.py

      - name: 上传结果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            all.txt
            data/test.log
            data/singbox.log
