name: Test and Publish Nodes

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: test-nodes
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test_nodes:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install httpx==0.27.2 aiodns==3.2.0 aiofiles==24.1.0 psutil==6.0.0

      - name: 初始化 sub.txt
        run: echo "# Initial sub.txt" > data/sub.txt

      - name: 缓存 ss.txt
        uses: actions/cache@v4
        with:
          path: data/ss.txt
          key: ss-txt-${{ hashFiles('data/ss.txt') }}

      - name: 运行节点测试脚本
        run: |
          start_time=$(date +%s)
          python test_nodes.py
          end_time=$(date +%s)
          echo "Test script took $((end_time - start_time)) seconds"
        env:
          PYTHONUNBUFFERED: "1"
          DEBUG_LOG: "true"

      - name: 验证 sub.txt
        run: |
          line_count=$(wc -l < data/sub.txt)
          file_size=$(ls -l data/sub.txt | awk '{print $5}')
          echo "sub.txt: $line_count lines, $file_size bytes"
          if [ "$line_count" -gt 512 ] || [ "$file_size" -gt 524288 ]; then
            echo "Error: sub.txt is too large or has too many lines"
            exit 1
          fi
          head -n 10 data/sub.txt || echo "sub.txt is empty"

      - name: 统计成功节点
        run: |
          python -c "import json; with open('data/history_results.json', 'r') as f: results = json.load(f); successful = [k for k, v in results.items() if v['status'] == 'Successful']; print(f'Successful nodes in history_results.json: {len(successful)}')"

      - name: 提交并推送更新的数据文件
        if: success()
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data/sub.txt data/history_results.json data/dns_cache.json
          git commit -m "Update test results and sub.txt [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
