name: Test Proxy Nodes
on: [push]
jobs:
  test-nodes:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        timeout-minutes: 5
      - run: |
          python -m pip install --upgrade pip
          pip install aiohttp tqdm psutil
        timeout-minutes: 5
      - run: |
          SINGBOX_VERSION="1.10.1"
          wget -q https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          mv sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box .
          chmod +x sing-box
          rm -rf sing-box-${SINGBOX_VERSION}-linux-amd64*
          ./sing-box version
        timeout-minutes: 5
      - run: python test_proxy_nodes.py
        timeout-minutes: 50
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add all.txt data/failed.txt data/test.log data/singbox.log
          git commit -m "Update test results" || echo "No changes to commit"
          git push
        timeout-minutes: 5
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            all.txt
            data/failed.txt
            data/test.log
            data/singbox.log
        timeout-minutes: 5
