name: Update IPTV List

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次 (UTC时间)

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 或更高版本，如 '3.10', '3.11'

      - name: Install dependencies
        run: pip install requests PyYAML # 额外安装 PyYAML

      - name: Run IPTV Tester script # 修改这里
        run: python iptv_tester.py # 修改这里

      - name: Commit and Push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tv.list.txt
          git commit -m "Auto update tv.list.txt [skip ci]" || echo "No changes to commit"
          git push
