name: Test Nodes Workflow

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1日0点
  workflow_dispatch:  # 手动触发

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install pyyaml requests pysocks tqdm

      - name: Install binary dependencies
        run: |
          mkdir -p bin
          # 下载 Xray
          curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
          unzip xray.zip -d bin
          chmod +x bin/xray
          # 下载 trojan-go
          curl -L https://github.com/p4gefau1t/trojan-go/releases/latest/download/trojan-go-linux-amd64.zip -o trojan-go.zip
          unzip trojan-go.zip -d bin
          chmod +x bin/trojan-go
          # 下载 Hysteria
          curl -L https://github.com/HyNetwork/hysteria/releases/latest/download/hysteria-linux-amd64 -o bin/hysteria
          chmod +x bin/hysteria
          # 下载 Shadowsocks
          curl -L https://github.com/shadowsocks/shadowsocks-rust/releases/latest/download/shadowsocks-x86_64-unknown-linux-gnu.tar.xz -o ss.tar.xz
          tar -xf ss.tar.xz -C bin
          chmod +x bin/ss-local

      - name: Run test script
        env:
          XRAY_PATH: ./bin/xray
          TROJAN_GO_PATH: ./bin/trojan-go
          HYSTERIA_PATH: ./bin/hysteria
          SS_LOCAL_PATH: ./bin/ss-local
        run: python test_nodes.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add node_test_results.yaml node_test_results.csv node_test.log
          git commit -m "Update node test results" || echo "No changes"
          git push
