name: Test Nodes Workflow

on:
  push:
    paths:
      - 'test_nodes.py'
      - '.github/workflows/test_nodes.yaml'
  schedule:
    - cron: '0 0 1 * *'  # 每月1日0点
  workflow_dispatch:  # 手动触发

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 升级到最新版本

      - name: Set up Python
        uses: actions/setup-python@v5  # 升级到最新版本
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install pyyaml requests pysocks tqdm

      - name: Install binary dependencies
        run: |
          set -e
          mkdir -p bin
          
          echo "Extracting Xray from local file..."
          unzip -o Xray-linux-64.zip -d bin
          chmod +x bin/xray
          
          echo "Extracting trojan-go from local file..."
          unzip -o trojan-go-linux-amd64.zip -d bin
          chmod +x bin/trojan-go
          
          echo "Extracting Hysteria from local file..."
          mv hysteria-linux-amd64 bin/hysteria
          chmod +x bin/hysteria
          
          echo "Extracting Shadowsocks-rust from local file..."
          tar -xf shadowsocks-v1.23.5.x86_64-unknown-linux-gnu.tar.xz -C bin
          
          # 调试：列出解压后的文件结构
          echo "Listing files in bin directory..."
          ls -R bin
          
          # 查找 ss-local 或 sslocal
          echo "Locating ss-local or sslocal..."
          ss_local_path=$(find . -name "ss-local" -o -name "sslocal" | head -n 1)
          if [ -z "$ss_local_path" ]; then
            echo "Error: ss-local or sslocal not found"
            exit 1
          fi
          mv "$ss_local_path" bin/ss-local
          chmod +x bin/ss-local
          
          # 清理压缩包
          rm -f Xray-linux-64.zip trojan-go-linux-amd64.zip hysteria-linux-amd64 shadowsocks-v1.23.5.x86_64-unknown-linux-gnu.tar.xz
          echo "All binaries extracted successfully from the repository."

      - name: Run test script
        env:
          XRAY_PATH: ./bin/xray
          TROJAN_GO_PATH: ./bin/trojan-go
          HYSTERIA_PATH: ./bin/hysteria
          SS_LOCAL_PATH: ./bin/ss-local
        run: python test_nodes.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add node_test_results.yaml node_test_results.csv node_test.log
          git commit -m "Update node test results" || echo "No changes"
          git push

      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-test-log
          path: node_test.log
          retention-days: 7
