name: Test Proxy Nodes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  test-nodes:
    # 将 runs-on 从 ubuntu-latest 改为 ubuntu-22.04
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          # 安装 Python 依赖
          pip install requests
          
          # 安装 Speedtest CLI (新版命令为 speedtest)
          # 这是官方推荐的通过 apt 仓库安装的方式，适用于 Ubuntu 22.04
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl gnupg2
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install -y speedtest
          
          # 安装 netcat (用于测试本地代理端口)
          sudo apt-get install -y netcat-traditional

      - name: Run node test script
        run: python test_nodes.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: data/collectSub.txt
