name: Test Proxy Nodes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp tqdm

      - name: Download sing-box
        run: |
          SINGBOX_VERSION="1.10.1"
          wget -q https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          mv sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box .
          chmod +x sing-box
          rm -rf sing-box-${SINGBOX_VERSION}-linux-amd64*
          ./sing-box version  # 验证安装

      - name: Run proxy node test
        run: python test_proxy_nodes.py

      - name: Upload results
        if: always()  # 即使失败也上传日志
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            all.txt
            data/test.log
            data/singbox.log
