name: Test Nodes and Commit Results

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行
  workflow_dispatch:  # 允许手动触发

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install httpx aiodns aiofiles psutil

    - name: Check working directory
      run: |
        pwd
        ls -la

    - name: Run node tester script
      run: python test_nodes.py

    - name: Commit and Push changes
      run: |
        ls -la data/  # 确认文件存在
        git add data/sub.txt data/history_results.json data/dns_cache.json data/success_count.txt
        git status
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git commit -m "Update test results" || echo
