name: Test Proxy Nodes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          # 安装 Python 依赖
          pip install requests
          # 安装 Speedtest CLI (新版命令为 speedtest)
          # 注意：官方推荐的安装方式，而不是通过 pip 或 apt
          # 参见 https://www.speedtest.net/apps/cli
          curl -s https://install.speedtest.net/app/cli/install.deb | sudo bash
          
          # 安装 netcat (用于测试本地代理端口) 和 curl
          sudo apt-get update
          sudo apt-get install -y netcat-traditional curl

      - name: Run node test script
        run: python test_nodes.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: data/collectSub.txt
