name: Test Proxy Nodes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests speedtest-cli
          sudo apt-get update
          sudo apt-get install -y curl
      - name: Run node test script
        run: python test_nodes.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: data/collectSub.txt
