name: Process M3U URLs

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  process-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 可以根据需要选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    - name: Create necessary directories if not exists
      run: |
        mkdir -p output # 确保 output 目录存在
        mkdir -p scripts # 确保 scripts 目录存在，如果脚本已在仓库中则不是严格必须

    - name: Run M3U Processor
      run: python scripts/process_m3u.py # 更改为新的脚本路径

    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        # 添加所有需要更新的文件，包括 url_hashes.json
        git add output/list.txt output/failed_urls.txt config/urls.txt output/successful_urls.txt output/url_hashes.json
        git commit -m "Automated: Update M3U playlists, successful/failed URLs, and content hashes" || echo "No changes to commit"
        git push
