name: Test IPTV Streams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-streams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: |
        pip install requests

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Copy IPTV list (if not already in repo)
      # This step assumes iptv_list.txt is either already committed
      # or you will manually place it in the repository.
      # If you're fetching it from a URL, you'd add a curl/wget command here.
      run: |
        # As per user request, fetching from a URL
        curl -o iptv_list.txt https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/output/iptv_list.txt
      shell: bash

    - name: Run stream test script
      run: python test_stream.py

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: ffprobe-results
        path: output/
