name: tvbox_search

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
env:
  TZ: Asia/Shanghai # 添加时区环境变量
  
jobs:
  scrape-interfaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml aiohttp

      - name: Run interface scraper script
        env:
          BOT: ${{ secrets.BOT }}  
        run: python tvbox_search.py  

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add box/
          git commit -m "feat: automatically scrape and update TVbox interfaces" || echo "No changes to commit"
          git pull --rebase origin main
          git push
