name: Download TVBox Configs

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = 上海时间 00:00
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 运行脚本
        env:
          BOT: ${{ secrets.BOT }}
        run: python download_tvbox_configs.py

      - name: 提交并推送更改
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add tvbox/*
          git add tvbox/last_search_timestamp.txt
          git commit -m "更新 TVBox 配置文件" || echo "没有新文件需要提交"
          git push
