name: IPTV 频道更新

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */8 * * *'  # 每天 UTC 0:00、8:00、16:00

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT }}

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: 安装 Python 依赖
        run: pip install requests pyyaml aiohttp tenacity

      - name: 安装 FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: 运行 IPTV 爬取脚本
        env:
          BOT: ${{ secrets.BOT }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          CONFIG_PATH: config/config.yaml
          LOG_LEVEL: INFO
        run: python tv.py

      - name: 检查文件更改
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 保存结果
        uses: actions/upload-artifact@v4
        with:
          name: iptv-results
          path: |
            *.txt
            config/*.txt
            iptv_crawler.log
          retention-days: 7
          if-no-files-found: warn

      - name: 提交和推送更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "更新 IPTV 频道列表 ($(date +'%Y-%m-%d %H:%M'))"
          git fetch origin
          git rebase origin/main || (git rebase --abort && git pull origin/main --no-rebase)
          git push origin main --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
