
name: Deduplicate Clash Proxies

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  deduplicate:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置工作流超时为 10 分钟

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    # 下载 YAML 文件
    - name: Download YAML files
      run: |
        curl -o link.yaml "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/link.yaml"
        curl -o link1.yaml "https://raw.githubusercontent.com/qjlxg/VT/refs/heads/main/link%20(1).yaml"

    # 运行去重脚本
    - name: Run deduplication script
      run: |
        python deduplicate.py

    # 上传 artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deduplication-results
        path: |
          unique_link.yaml
          unique_link1.yaml
          compare_link.log
          compare_link1.log
          stats.txt

    # 打印统计信息
    - name: Display statistics
      run: |
        if [ -f stats.txt ]; then
          cat stats.txt
        else
          echo "stats.txt 未找到，脚本可能失败"
        fi
