name: IPTV Channel Processor (频道处理)

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */168 * * *'  # 每周运行一次

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write

    steps:
      - name: 检查 BOT secret
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "错误：未设置 BOT secret，请在 GitHub Secrets 中配置"
            exit 1
          fi
        shell: bash

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 安装 Python 依赖
        run: |
          pip install --no-cache-dir requests pyyaml tenacity cachetools
          pip list | grep -E 'requests|pyyaml|tenacity|cachetools'
        shell: bash

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 运行 IPTV 频道处理脚本
        run: |
          echo "当前目录内容："
          ls -la
          python Viptv_processor.py
        shell: bash

      - name: 保存日志和生成文件
        uses: actions/upload-artifact@v4
        with:
          name: iptv-results
          path: |
            iptv_list_temp.txt
            Viptv_processor.log
            config/
            urls.txt
          retention-days: 7
          if-no-files-found: warn
          compression-level: 6
        if: always()

      - name: 检查文件更改
        id: check_changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "没有文件更改"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件更改"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "更新 IPTV 频道列表 ($(date +'%Y-%m-%d %H:%M'))"
        shell: bash

      - name: 推送更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git fetch origin main
          git merge origin/main -m "合并远程更改" || (echo "错误：合并冲突，请手动解决" && exit 1)
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash

      - name: 发送运行结果通知
        run: |
          echo "IPTV 频道处理工作流完成，状态: ${{ job.status }}"
          echo "请检查 artifact 中的 Viptv_processor.log 获取详情"
        shell: bash
